// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: wishes/v1/wishes.proto

package v1

import (
	context "context"
	request "github.com/arm-1234/protos/wishes/v1/request"
	response "github.com/arm-1234/protos/wishes/v1/response"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationWishesCreateWish = "/wishes.v1.Wishes/CreateWish"
const OperationWishesDeleteWish = "/wishes.v1.Wishes/DeleteWish"
const OperationWishesDeleteWishPhoto = "/wishes.v1.Wishes/DeleteWishPhoto"
const OperationWishesExtendWish = "/wishes.v1.Wishes/ExtendWish"
const OperationWishesGetTemplateSchema = "/wishes.v1.Wishes/GetTemplateSchema"
const OperationWishesGetWish = "/wishes.v1.Wishes/GetWish"
const OperationWishesGetWishStats = "/wishes.v1.Wishes/GetWishStats"
const OperationWishesListMyWishes = "/wishes.v1.Wishes/ListMyWishes"
const OperationWishesListTemplates = "/wishes.v1.Wishes/ListTemplates"
const OperationWishesListWishResponses = "/wishes.v1.Wishes/ListWishResponses"
const OperationWishesMarkResponsesSeen = "/wishes.v1.Wishes/MarkResponsesSeen"
const OperationWishesPublishWish = "/wishes.v1.Wishes/PublishWish"
const OperationWishesReportCard = "/wishes.v1.Wishes/ReportCard"
const OperationWishesRevokeWish = "/wishes.v1.Wishes/RevokeWish"
const OperationWishesSaveDraft = "/wishes.v1.Wishes/SaveDraft"
const OperationWishesSendWish = "/wishes.v1.Wishes/SendWish"
const OperationWishesSubmitResponse = "/wishes.v1.Wishes/SubmitResponse"
const OperationWishesUpdateWish = "/wishes.v1.Wishes/UpdateWish"
const OperationWishesUploadWishPhoto = "/wishes.v1.Wishes/UploadWishPhoto"

type WishesHTTPServer interface {
	CreateWish(context.Context, *request.CreateWishRequest) (*response.CreateWishResponse, error)
	DeleteWish(context.Context, *request.DeleteWishRequest) (*response.DeleteWishResponse, error)
	DeleteWishPhoto(context.Context, *request.DeleteWishPhotoRequest) (*response.DeleteWishPhotoResponse, error)
	ExtendWish(context.Context, *request.ExtendWishRequest) (*response.ExtendWishResponse, error)
	GetTemplateSchema(context.Context, *request.GetTemplateSchemaRequest) (*response.GetTemplateSchemaResponse, error)
	GetWish(context.Context, *request.GetWishRequest) (*response.GetWishResponse, error)
	GetWishStats(context.Context, *request.GetWishStatsRequest) (*response.GetWishStatsResponse, error)
	ListMyWishes(context.Context, *request.ListMyWishesRequest) (*response.ListMyWishesResponse, error)
	ListTemplates(context.Context, *request.ListTemplatesRequest) (*response.ListTemplatesResponse, error)
	ListWishResponses(context.Context, *request.ListWishResponsesRequest) (*response.ListWishResponsesResponse, error)
	MarkResponsesSeen(context.Context, *request.MarkResponsesSeenRequest) (*response.MarkResponsesSeenResponse, error)
	PublishWish(context.Context, *request.PublishWishRequest) (*response.PublishWishResponse, error)
	ReportCard(context.Context, *request.ReportCardRequest) (*response.ReportCardResponse, error)
	RevokeWish(context.Context, *request.RevokeWishRequest) (*response.RevokeWishResponse, error)
	SaveDraft(context.Context, *request.SaveDraftRequest) (*response.SaveDraftResponse, error)
	SendWish(context.Context, *request.SendWishRequest) (*response.SendWishResponse, error)
	SubmitResponse(context.Context, *request.SubmitResponseRequest) (*response.SubmitResponseResponse, error)
	UpdateWish(context.Context, *request.UpdateWishRequest) (*response.UpdateWishResponse, error)
	UploadWishPhoto(context.Context, *request.UploadWishPhotoRequest) (*response.UploadWishPhotoResponse, error)
}

func RegisterWishesHTTPServer(s *http.Server, srv WishesHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/wishes", _Wishes_CreateWish0_HTTP_Handler(srv))
	r.GET("/v1/wishes", _Wishes_ListMyWishes0_HTTP_Handler(srv))
	r.GET("/v1/wishes:stats", _Wishes_GetWishStats0_HTTP_Handler(srv))
	r.GET("/v1/wishes:schema", _Wishes_GetTemplateSchema0_HTTP_Handler(srv))
	r.POST("/v1/cards/{card_id}:respond", _Wishes_SubmitResponse0_HTTP_Handler(srv))
	r.POST("/v1/cards/{card_id}:report", _Wishes_ReportCard0_HTTP_Handler(srv))
	r.GET("/v1/wishes:templates", _Wishes_ListTemplates0_HTTP_Handler(srv))
	r.POST("/v1/wishes:draft", _Wishes_SaveDraft0_HTTP_Handler(srv))
	r.GET("/v1/wishes/{wish_id}", _Wishes_GetWish0_HTTP_Handler(srv))
	r.PATCH("/v1/wishes/{wish_id}", _Wishes_UpdateWish0_HTTP_Handler(srv))
	r.POST("/v1/wishes/{wish_id}:publish", _Wishes_PublishWish0_HTTP_Handler(srv))
	r.DELETE("/v1/wishes/{wish_id}", _Wishes_DeleteWish0_HTTP_Handler(srv))
	r.POST("/v1/wishes/{wish_id}/photos", _Wishes_UploadWishPhoto0_HTTP_Handler(srv))
	r.DELETE("/v1/wishes/{wish_id}/photos/{idx}", _Wishes_DeleteWishPhoto0_HTTP_Handler(srv))
	r.POST("/v1/wishes/{wish_id}:extend", _Wishes_ExtendWish0_HTTP_Handler(srv))
	r.POST("/v1/wishes/{wish_id}:revoke", _Wishes_RevokeWish0_HTTP_Handler(srv))
	r.POST("/v1/wishes/{wish_id}:send", _Wishes_SendWish0_HTTP_Handler(srv))
	r.GET("/v1/wishes/{wish_id}/responses", _Wishes_ListWishResponses0_HTTP_Handler(srv))
	r.POST("/v1/wishes/{wish_id}/responses:seen", _Wishes_MarkResponsesSeen0_HTTP_Handler(srv))
}

func _Wishes_CreateWish0_HTTP_Handler(srv WishesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.CreateWishRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWishesCreateWish)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateWish(ctx, req.(*request.CreateWishRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.CreateWishResponse)
		return ctx.Result(200, reply)
	}
}

func _Wishes_ListMyWishes0_HTTP_Handler(srv WishesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.ListMyWishesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWishesListMyWishes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMyWishes(ctx, req.(*request.ListMyWishesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.ListMyWishesResponse)
		return ctx.Result(200, reply)
	}
}

func _Wishes_GetWishStats0_HTTP_Handler(srv WishesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.GetWishStatsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWishesGetWishStats)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetWishStats(ctx, req.(*request.GetWishStatsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.GetWishStatsResponse)
		return ctx.Result(200, reply)
	}
}

func _Wishes_GetTemplateSchema0_HTTP_Handler(srv WishesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.GetTemplateSchemaRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWishesGetTemplateSchema)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTemplateSchema(ctx, req.(*request.GetTemplateSchemaRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.GetTemplateSchemaResponse)
		return ctx.Result(200, reply)
	}
}

func _Wishes_SubmitResponse0_HTTP_Handler(srv WishesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.SubmitResponseRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWishesSubmitResponse)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubmitResponse(ctx, req.(*request.SubmitResponseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.SubmitResponseResponse)
		return ctx.Result(200, reply)
	}
}

func _Wishes_ReportCard0_HTTP_Handler(srv WishesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.ReportCardRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWishesReportCard)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReportCard(ctx, req.(*request.ReportCardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.ReportCardResponse)
		return ctx.Result(200, reply)
	}
}

func _Wishes_ListTemplates0_HTTP_Handler(srv WishesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.ListTemplatesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWishesListTemplates)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTemplates(ctx, req.(*request.ListTemplatesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.ListTemplatesResponse)
		return ctx.Result(200, reply)
	}
}

func _Wishes_SaveDraft0_HTTP_Handler(srv WishesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.SaveDraftRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWishesSaveDraft)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SaveDraft(ctx, req.(*request.SaveDraftRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.SaveDraftResponse)
		return ctx.Result(200, reply)
	}
}

func _Wishes_GetWish0_HTTP_Handler(srv WishesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.GetWishRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWishesGetWish)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetWish(ctx, req.(*request.GetWishRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.GetWishResponse)
		return ctx.Result(200, reply)
	}
}

func _Wishes_UpdateWish0_HTTP_Handler(srv WishesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.UpdateWishRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWishesUpdateWish)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateWish(ctx, req.(*request.UpdateWishRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.UpdateWishResponse)
		return ctx.Result(200, reply)
	}
}

func _Wishes_PublishWish0_HTTP_Handler(srv WishesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.PublishWishRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWishesPublishWish)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PublishWish(ctx, req.(*request.PublishWishRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.PublishWishResponse)
		return ctx.Result(200, reply)
	}
}

func _Wishes_DeleteWish0_HTTP_Handler(srv WishesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.DeleteWishRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWishesDeleteWish)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteWish(ctx, req.(*request.DeleteWishRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.DeleteWishResponse)
		return ctx.Result(200, reply)
	}
}

func _Wishes_UploadWishPhoto0_HTTP_Handler(srv WishesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.UploadWishPhotoRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWishesUploadWishPhoto)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UploadWishPhoto(ctx, req.(*request.UploadWishPhotoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.UploadWishPhotoResponse)
		return ctx.Result(200, reply)
	}
}

func _Wishes_DeleteWishPhoto0_HTTP_Handler(srv WishesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.DeleteWishPhotoRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWishesDeleteWishPhoto)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteWishPhoto(ctx, req.(*request.DeleteWishPhotoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.DeleteWishPhotoResponse)
		return ctx.Result(200, reply)
	}
}

func _Wishes_ExtendWish0_HTTP_Handler(srv WishesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.ExtendWishRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWishesExtendWish)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExtendWish(ctx, req.(*request.ExtendWishRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.ExtendWishResponse)
		return ctx.Result(200, reply)
	}
}

func _Wishes_RevokeWish0_HTTP_Handler(srv WishesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.RevokeWishRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWishesRevokeWish)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RevokeWish(ctx, req.(*request.RevokeWishRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.RevokeWishResponse)
		return ctx.Result(200, reply)
	}
}

func _Wishes_SendWish0_HTTP_Handler(srv WishesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.SendWishRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWishesSendWish)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendWish(ctx, req.(*request.SendWishRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.SendWishResponse)
		return ctx.Result(200, reply)
	}
}

func _Wishes_ListWishResponses0_HTTP_Handler(srv WishesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.ListWishResponsesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWishesListWishResponses)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListWishResponses(ctx, req.(*request.ListWishResponsesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.ListWishResponsesResponse)
		return ctx.Result(200, reply)
	}
}

func _Wishes_MarkResponsesSeen0_HTTP_Handler(srv WishesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.MarkResponsesSeenRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWishesMarkResponsesSeen)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MarkResponsesSeen(ctx, req.(*request.MarkResponsesSeenRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.MarkResponsesSeenResponse)
		return ctx.Result(200, reply)
	}
}

type WishesHTTPClient interface {
	CreateWish(ctx context.Context, req *request.CreateWishRequest, opts ...http.CallOption) (rsp *response.CreateWishResponse, err error)
	DeleteWish(ctx context.Context, req *request.DeleteWishRequest, opts ...http.CallOption) (rsp *response.DeleteWishResponse, err error)
	DeleteWishPhoto(ctx context.Context, req *request.DeleteWishPhotoRequest, opts ...http.CallOption) (rsp *response.DeleteWishPhotoResponse, err error)
	ExtendWish(ctx context.Context, req *request.ExtendWishRequest, opts ...http.CallOption) (rsp *response.ExtendWishResponse, err error)
	GetTemplateSchema(ctx context.Context, req *request.GetTemplateSchemaRequest, opts ...http.CallOption) (rsp *response.GetTemplateSchemaResponse, err error)
	GetWish(ctx context.Context, req *request.GetWishRequest, opts ...http.CallOption) (rsp *response.GetWishResponse, err error)
	GetWishStats(ctx context.Context, req *request.GetWishStatsRequest, opts ...http.CallOption) (rsp *response.GetWishStatsResponse, err error)
	ListMyWishes(ctx context.Context, req *request.ListMyWishesRequest, opts ...http.CallOption) (rsp *response.ListMyWishesResponse, err error)
	ListTemplates(ctx context.Context, req *request.ListTemplatesRequest, opts ...http.CallOption) (rsp *response.ListTemplatesResponse, err error)
	ListWishResponses(ctx context.Context, req *request.ListWishResponsesRequest, opts ...http.CallOption) (rsp *response.ListWishResponsesResponse, err error)
	MarkResponsesSeen(ctx context.Context, req *request.MarkResponsesSeenRequest, opts ...http.CallOption) (rsp *response.MarkResponsesSeenResponse, err error)
	PublishWish(ctx context.Context, req *request.PublishWishRequest, opts ...http.CallOption) (rsp *response.PublishWishResponse, err error)
	ReportCard(ctx context.Context, req *request.ReportCardRequest, opts ...http.CallOption) (rsp *response.ReportCardResponse, err error)
	RevokeWish(ctx context.Context, req *request.RevokeWishRequest, opts ...http.CallOption) (rsp *response.RevokeWishResponse, err error)
	SaveDraft(ctx context.Context, req *request.SaveDraftRequest, opts ...http.CallOption) (rsp *response.SaveDraftResponse, err error)
	SendWish(ctx context.Context, req *request.SendWishRequest, opts ...http.CallOption) (rsp *response.SendWishResponse, err error)
	SubmitResponse(ctx context.Context, req *request.SubmitResponseRequest, opts ...http.CallOption) (rsp *response.SubmitResponseResponse, err error)
	UpdateWish(ctx context.Context, req *request.UpdateWishRequest, opts ...http.CallOption) (rsp *response.UpdateWishResponse, err error)
	UploadWishPhoto(ctx context.Context, req *request.UploadWishPhotoRequest, opts ...http.CallOption) (rsp *response.UploadWishPhotoResponse, err error)
}

type WishesHTTPClientImpl struct {
	cc *http.Client
}

func NewWishesHTTPClient(client *http.Client) WishesHTTPClient {
	return &WishesHTTPClientImpl{client}
}

func (c *WishesHTTPClientImpl) CreateWish(ctx context.Context, in *request.CreateWishRequest, opts ...http.CallOption) (*response.CreateWishResponse, error) {
	var out response.CreateWishResponse
	pattern := "/v1/wishes"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWishesCreateWish))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WishesHTTPClientImpl) DeleteWish(ctx context.Context, in *request.DeleteWishRequest, opts ...http.CallOption) (*response.DeleteWishResponse, error) {
	var out response.DeleteWishResponse
	pattern := "/v1/wishes/{wish_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWishesDeleteWish))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WishesHTTPClientImpl) DeleteWishPhoto(ctx context.Context, in *request.DeleteWishPhotoRequest, opts ...http.CallOption) (*response.DeleteWishPhotoResponse, error) {
	var out response.DeleteWishPhotoResponse
	pattern := "/v1/wishes/{wish_id}/photos/{idx}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWishesDeleteWishPhoto))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WishesHTTPClientImpl) ExtendWish(ctx context.Context, in *request.ExtendWishRequest, opts ...http.CallOption) (*response.ExtendWishResponse, error) {
	var out response.ExtendWishResponse
	pattern := "/v1/wishes/{wish_id}:extend"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWishesExtendWish))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WishesHTTPClientImpl) GetTemplateSchema(ctx context.Context, in *request.GetTemplateSchemaRequest, opts ...http.CallOption) (*response.GetTemplateSchemaResponse, error) {
	var out response.GetTemplateSchemaResponse
	pattern := "/v1/wishes:schema"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWishesGetTemplateSchema))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WishesHTTPClientImpl) GetWish(ctx context.Context, in *request.GetWishRequest, opts ...http.CallOption) (*response.GetWishResponse, error) {
	var out response.GetWishResponse
	pattern := "/v1/wishes/{wish_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWishesGetWish))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WishesHTTPClientImpl) GetWishStats(ctx context.Context, in *request.GetWishStatsRequest, opts ...http.CallOption) (*response.GetWishStatsResponse, error) {
	var out response.GetWishStatsResponse
	pattern := "/v1/wishes:stats"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWishesGetWishStats))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WishesHTTPClientImpl) ListMyWishes(ctx context.Context, in *request.ListMyWishesRequest, opts ...http.CallOption) (*response.ListMyWishesResponse, error) {
	var out response.ListMyWishesResponse
	pattern := "/v1/wishes"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWishesListMyWishes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WishesHTTPClientImpl) ListTemplates(ctx context.Context, in *request.ListTemplatesRequest, opts ...http.CallOption) (*response.ListTemplatesResponse, error) {
	var out response.ListTemplatesResponse
	pattern := "/v1/wishes:templates"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWishesListTemplates))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WishesHTTPClientImpl) ListWishResponses(ctx context.Context, in *request.ListWishResponsesRequest, opts ...http.CallOption) (*response.ListWishResponsesResponse, error) {
	var out response.ListWishResponsesResponse
	pattern := "/v1/wishes/{wish_id}/responses"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWishesListWishResponses))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WishesHTTPClientImpl) MarkResponsesSeen(ctx context.Context, in *request.MarkResponsesSeenRequest, opts ...http.CallOption) (*response.MarkResponsesSeenResponse, error) {
	var out response.MarkResponsesSeenResponse
	pattern := "/v1/wishes/{wish_id}/responses:seen"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWishesMarkResponsesSeen))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WishesHTTPClientImpl) PublishWish(ctx context.Context, in *request.PublishWishRequest, opts ...http.CallOption) (*response.PublishWishResponse, error) {
	var out response.PublishWishResponse
	pattern := "/v1/wishes/{wish_id}:publish"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWishesPublishWish))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WishesHTTPClientImpl) ReportCard(ctx context.Context, in *request.ReportCardRequest, opts ...http.CallOption) (*response.ReportCardResponse, error) {
	var out response.ReportCardResponse
	pattern := "/v1/cards/{card_id}:report"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWishesReportCard))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WishesHTTPClientImpl) RevokeWish(ctx context.Context, in *request.RevokeWishRequest, opts ...http.CallOption) (*response.RevokeWishResponse, error) {
	var out response.RevokeWishResponse
	pattern := "/v1/wishes/{wish_id}:revoke"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWishesRevokeWish))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WishesHTTPClientImpl) SaveDraft(ctx context.Context, in *request.SaveDraftRequest, opts ...http.CallOption) (*response.SaveDraftResponse, error) {
	var out response.SaveDraftResponse
	pattern := "/v1/wishes:draft"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWishesSaveDraft))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WishesHTTPClientImpl) SendWish(ctx context.Context, in *request.SendWishRequest, opts ...http.CallOption) (*response.SendWishResponse, error) {
	var out response.SendWishResponse
	pattern := "/v1/wishes/{wish_id}:send"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWishesSendWish))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WishesHTTPClientImpl) SubmitResponse(ctx context.Context, in *request.SubmitResponseRequest, opts ...http.CallOption) (*response.SubmitResponseResponse, error) {
	var out response.SubmitResponseResponse
	pattern := "/v1/cards/{card_id}:respond"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWishesSubmitResponse))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WishesHTTPClientImpl) UpdateWish(ctx context.Context, in *request.UpdateWishRequest, opts ...http.CallOption) (*response.UpdateWishResponse, error) {
	var out response.UpdateWishResponse
	pattern := "/v1/wishes/{wish_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWishesUpdateWish))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *WishesHTTPClientImpl) UploadWishPhoto(ctx context.Context, in *request.UploadWishPhotoRequest, opts ...http.CallOption) (*response.UploadWishPhotoResponse, error) {
	var out response.UploadWishPhotoResponse
	pattern := "/v1/wishes/{wish_id}/photos"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWishesUploadWishPhoto))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
