// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: wishes/v1/wishes.proto

package v1

import (
	request "github.com/arm-1234/protos/wishes/v1/request"
	response "github.com/arm-1234/protos/wishes/v1/response"
	_ "github.com/go-kratos/kratos/v2/errors"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_WISHES_UNSPECIFIED      ErrorReason = 0
	ErrorReason_WISHES_INVALID_REQUEST  ErrorReason = 1
	ErrorReason_WISHES_UNAUTHENTICATED  ErrorReason = 2
	ErrorReason_WISHES_FORBIDDEN        ErrorReason = 3
	ErrorReason_WISH_NOT_FOUND          ErrorReason = 10
	ErrorReason_WISH_NOT_OWNED          ErrorReason = 11
	ErrorReason_WISH_ALREADY_REVOKED    ErrorReason = 12
	ErrorReason_WISH_EXPIRED            ErrorReason = 13
	ErrorReason_WISH_LIMIT_REACHED      ErrorReason = 14
	ErrorReason_WISH_NOT_DRAFT          ErrorReason = 15
	ErrorReason_WISH_ALREADY_PUBLISHED  ErrorReason = 16
	ErrorReason_TEMPLATE_NOT_FOUND      ErrorReason = 20
	ErrorReason_TEMPLATE_CONFIG_INVALID ErrorReason = 21
	ErrorReason_PHOTO_REJECTED          ErrorReason = 22
	ErrorReason_PHOTO_TOO_LARGE         ErrorReason = 23
	ErrorReason_RESPONSE_NOT_ALLOWED    ErrorReason = 32
	ErrorReason_RESPONSE_RATE_LIMITED   ErrorReason = 33
	ErrorReason_DELIVERY_FAILED         ErrorReason = 30
	ErrorReason_DELIVERY_RATE_LIMITED   ErrorReason = 31
	ErrorReason_RENDERER_UNAVAILABLE    ErrorReason = 40
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:  "WISHES_UNSPECIFIED",
		1:  "WISHES_INVALID_REQUEST",
		2:  "WISHES_UNAUTHENTICATED",
		3:  "WISHES_FORBIDDEN",
		10: "WISH_NOT_FOUND",
		11: "WISH_NOT_OWNED",
		12: "WISH_ALREADY_REVOKED",
		13: "WISH_EXPIRED",
		14: "WISH_LIMIT_REACHED",
		15: "WISH_NOT_DRAFT",
		16: "WISH_ALREADY_PUBLISHED",
		20: "TEMPLATE_NOT_FOUND",
		21: "TEMPLATE_CONFIG_INVALID",
		22: "PHOTO_REJECTED",
		23: "PHOTO_TOO_LARGE",
		32: "RESPONSE_NOT_ALLOWED",
		33: "RESPONSE_RATE_LIMITED",
		30: "DELIVERY_FAILED",
		31: "DELIVERY_RATE_LIMITED",
		40: "RENDERER_UNAVAILABLE",
	}
	ErrorReason_value = map[string]int32{
		"WISHES_UNSPECIFIED":      0,
		"WISHES_INVALID_REQUEST":  1,
		"WISHES_UNAUTHENTICATED":  2,
		"WISHES_FORBIDDEN":        3,
		"WISH_NOT_FOUND":          10,
		"WISH_NOT_OWNED":          11,
		"WISH_ALREADY_REVOKED":    12,
		"WISH_EXPIRED":            13,
		"WISH_LIMIT_REACHED":      14,
		"WISH_NOT_DRAFT":          15,
		"WISH_ALREADY_PUBLISHED":  16,
		"TEMPLATE_NOT_FOUND":      20,
		"TEMPLATE_CONFIG_INVALID": 21,
		"PHOTO_REJECTED":          22,
		"PHOTO_TOO_LARGE":         23,
		"RESPONSE_NOT_ALLOWED":    32,
		"RESPONSE_RATE_LIMITED":   33,
		"DELIVERY_FAILED":         30,
		"DELIVERY_RATE_LIMITED":   31,
		"RENDERER_UNAVAILABLE":    40,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_wishes_v1_wishes_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_wishes_v1_wishes_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_wishes_v1_wishes_proto_rawDescGZIP(), []int{0}
}

var File_wishes_v1_wishes_proto protoreflect.FileDescriptor

const file_wishes_v1_wishes_proto_rawDesc = "" +
	"\n" +
	"\x16wishes/v1/wishes.proto\x12\twishes.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x13errors/errors.proto\x1a&wishes/v1/request/wishes_request.proto\x1a(wishes/v1/response/wishes_response.proto*\xea\x04\n" +
	"\vErrorReason\x12\x1c\n" +
	"\x12WISHES_UNSPECIFIED\x10\x00\x1a\x04\xa8E\xf4\x03\x12 \n" +
	"\x16WISHES_INVALID_REQUEST\x10\x01\x1a\x04\xa8E\x90\x03\x12 \n" +
	"\x16WISHES_UNAUTHENTICATED\x10\x02\x1a\x04\xa8E\x91\x03\x12\x1a\n" +
	"\x10WISHES_FORBIDDEN\x10\x03\x1a\x04\xa8E\x93\x03\x12\x18\n" +
	"\x0eWISH_NOT_FOUND\x10\n" +
	"\x1a\x04\xa8E\x94\x03\x12\x18\n" +
	"\x0eWISH_NOT_OWNED\x10\v\x1a\x04\xa8E\x93\x03\x12\x1e\n" +
	"\x14WISH_ALREADY_REVOKED\x10\f\x1a\x04\xa8E\x99\x03\x12\x16\n" +
	"\fWISH_EXPIRED\x10\r\x1a\x04\xa8E\x9a\x03\x12\x1c\n" +
	"\x12WISH_LIMIT_REACHED\x10\x0e\x1a\x04\xa8E\xad\x03\x12\x18\n" +
	"\x0eWISH_NOT_DRAFT\x10\x0f\x1a\x04\xa8E\x99\x03\x12 \n" +
	"\x16WISH_ALREADY_PUBLISHED\x10\x10\x1a\x04\xa8E\x99\x03\x12\x1c\n" +
	"\x12TEMPLATE_NOT_FOUND\x10\x14\x1a\x04\xa8E\x94\x03\x12!\n" +
	"\x17TEMPLATE_CONFIG_INVALID\x10\x15\x1a\x04\xa8E\x90\x03\x12\x18\n" +
	"\x0ePHOTO_REJECTED\x10\x16\x1a\x04\xa8E\xa6\x03\x12\x19\n" +
	"\x0fPHOTO_TOO_LARGE\x10\x17\x1a\x04\xa8E\x9d\x03\x12\x1e\n" +
	"\x14RESPONSE_NOT_ALLOWED\x10 \x1a\x04\xa8E\x99\x03\x12\x1f\n" +
	"\x15RESPONSE_RATE_LIMITED\x10!\x1a\x04\xa8E\xad\x03\x12\x19\n" +
	"\x0fDELIVERY_FAILED\x10\x1e\x1a\x04\xa8E\xf6\x03\x12\x1f\n" +
	"\x15DELIVERY_RATE_LIMITED\x10\x1f\x1a\x04\xa8E\xad\x03\x12\x1e\n" +
	"\x14RENDERER_UNAVAILABLE\x10(\x1a\x04\xa8E\xf7\x03\x1a\x04\xa0E\xf4\x032\xe7\x13\n" +
	"\x06Wishes\x12q\n" +
	"\n" +
	"CreateWish\x12$.wishes.v1.request.CreateWishRequest\x1a&.wishes.v1.response.CreateWishResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/wishes\x12t\n" +
	"\fListMyWishes\x12&.wishes.v1.request.ListMyWishesRequest\x1a(.wishes.v1.response.ListMyWishesResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/wishes\x12z\n" +
	"\fGetWishStats\x12&.wishes.v1.request.GetWishStatsRequest\x1a(.wishes.v1.response.GetWishStatsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/wishes:stats\x12\x8a\x01\n" +
	"\x11GetTemplateSchema\x12+.wishes.v1.request.GetTemplateSchemaRequest\x1a-.wishes.v1.response.GetTemplateSchemaResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/wishes:schema\x12\x8e\x01\n" +
	"\x0eSubmitResponse\x12(.wishes.v1.request.SubmitResponseRequest\x1a*.wishes.v1.response.SubmitResponseResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/cards/{card_id}:respond\x12\x81\x01\n" +
	"\n" +
	"ReportCard\x12$.wishes.v1.request.ReportCardRequest\x1a&.wishes.v1.response.ReportCardResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/cards/{card_id}:report\x12\x81\x01\n" +
	"\rListTemplates\x12'.wishes.v1.request.ListTemplatesRequest\x1a).wishes.v1.response.ListTemplatesResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/wishes:templates\x12t\n" +
	"\tSaveDraft\x12#.wishes.v1.request.SaveDraftRequest\x1a%.wishes.v1.response.SaveDraftResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/wishes:draft\x12o\n" +
	"\aGetWish\x12!.wishes.v1.request.GetWishRequest\x1a#.wishes.v1.response.GetWishResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/wishes/{wish_id}\x12{\n" +
	"\n" +
	"UpdateWish\x12$.wishes.v1.request.UpdateWishRequest\x1a&.wishes.v1.response.UpdateWishResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*2\x14/v1/wishes/{wish_id}\x12\x86\x01\n" +
	"\vPublishWish\x12%.wishes.v1.request.PublishWishRequest\x1a'.wishes.v1.response.PublishWishResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/wishes/{wish_id}:publish\x12x\n" +
	"\n" +
	"DeleteWish\x12$.wishes.v1.request.DeleteWishRequest\x1a&.wishes.v1.response.DeleteWishResponse\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/v1/wishes/{wish_id}\x12\x91\x01\n" +
	"\x0fUploadWishPhoto\x12).wishes.v1.request.UploadWishPhotoRequest\x1a+.wishes.v1.response.UploadWishPhotoResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/wishes/{wish_id}/photos\x12\x94\x01\n" +
	"\x0fDeleteWishPhoto\x12).wishes.v1.request.DeleteWishPhotoRequest\x1a+.wishes.v1.response.DeleteWishPhotoResponse\")\x82\xd3\xe4\x93\x02#*!/v1/wishes/{wish_id}/photos/{idx}\x12\x82\x01\n" +
	"\n" +
	"ExtendWish\x12$.wishes.v1.request.ExtendWishRequest\x1a&.wishes.v1.response.ExtendWishResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/wishes/{wish_id}:extend\x12\x82\x01\n" +
	"\n" +
	"RevokeWish\x12$.wishes.v1.request.RevokeWishRequest\x1a&.wishes.v1.response.RevokeWishResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/wishes/{wish_id}:revoke\x12z\n" +
	"\bSendWish\x12\".wishes.v1.request.SendWishRequest\x1a$.wishes.v1.response.SendWishResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/wishes/{wish_id}:send\x12\x97\x01\n" +
	"\x11ListWishResponses\x12+.wishes.v1.request.ListWishResponsesRequest\x1a-.wishes.v1.response.ListWishResponsesResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/wishes/{wish_id}/responses\x12\x9f\x01\n" +
	"\x11MarkResponsesSeen\x12+.wishes.v1.request.MarkResponsesSeenRequest\x1a-.wishes.v1.response.MarkResponsesSeenResponse\".\x82\xd3\xe4\x93\x02(:\x01*\"#/v1/wishes/{wish_id}/responses:seenB)Z'github.com/arm-1234/protos/wishes/v1;v1b\x06proto3"

var (
	file_wishes_v1_wishes_proto_rawDescOnce sync.Once
	file_wishes_v1_wishes_proto_rawDescData []byte
)

func file_wishes_v1_wishes_proto_rawDescGZIP() []byte {
	file_wishes_v1_wishes_proto_rawDescOnce.Do(func() {
		file_wishes_v1_wishes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wishes_v1_wishes_proto_rawDesc), len(file_wishes_v1_wishes_proto_rawDesc)))
	})
	return file_wishes_v1_wishes_proto_rawDescData
}

var file_wishes_v1_wishes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wishes_v1_wishes_proto_goTypes = []any{
	(ErrorReason)(0),                           // 0: wishes.v1.ErrorReason
	(*request.CreateWishRequest)(nil),          // 1: wishes.v1.request.CreateWishRequest
	(*request.ListMyWishesRequest)(nil),        // 2: wishes.v1.request.ListMyWishesRequest
	(*request.GetWishStatsRequest)(nil),        // 3: wishes.v1.request.GetWishStatsRequest
	(*request.GetTemplateSchemaRequest)(nil),   // 4: wishes.v1.request.GetTemplateSchemaRequest
	(*request.SubmitResponseRequest)(nil),      // 5: wishes.v1.request.SubmitResponseRequest
	(*request.ReportCardRequest)(nil),          // 6: wishes.v1.request.ReportCardRequest
	(*request.ListTemplatesRequest)(nil),       // 7: wishes.v1.request.ListTemplatesRequest
	(*request.SaveDraftRequest)(nil),           // 8: wishes.v1.request.SaveDraftRequest
	(*request.GetWishRequest)(nil),             // 9: wishes.v1.request.GetWishRequest
	(*request.UpdateWishRequest)(nil),          // 10: wishes.v1.request.UpdateWishRequest
	(*request.PublishWishRequest)(nil),         // 11: wishes.v1.request.PublishWishRequest
	(*request.DeleteWishRequest)(nil),          // 12: wishes.v1.request.DeleteWishRequest
	(*request.UploadWishPhotoRequest)(nil),     // 13: wishes.v1.request.UploadWishPhotoRequest
	(*request.DeleteWishPhotoRequest)(nil),     // 14: wishes.v1.request.DeleteWishPhotoRequest
	(*request.ExtendWishRequest)(nil),          // 15: wishes.v1.request.ExtendWishRequest
	(*request.RevokeWishRequest)(nil),          // 16: wishes.v1.request.RevokeWishRequest
	(*request.SendWishRequest)(nil),            // 17: wishes.v1.request.SendWishRequest
	(*request.ListWishResponsesRequest)(nil),   // 18: wishes.v1.request.ListWishResponsesRequest
	(*request.MarkResponsesSeenRequest)(nil),   // 19: wishes.v1.request.MarkResponsesSeenRequest
	(*response.CreateWishResponse)(nil),        // 20: wishes.v1.response.CreateWishResponse
	(*response.ListMyWishesResponse)(nil),      // 21: wishes.v1.response.ListMyWishesResponse
	(*response.GetWishStatsResponse)(nil),      // 22: wishes.v1.response.GetWishStatsResponse
	(*response.GetTemplateSchemaResponse)(nil), // 23: wishes.v1.response.GetTemplateSchemaResponse
	(*response.SubmitResponseResponse)(nil),    // 24: wishes.v1.response.SubmitResponseResponse
	(*response.ReportCardResponse)(nil),        // 25: wishes.v1.response.ReportCardResponse
	(*response.ListTemplatesResponse)(nil),     // 26: wishes.v1.response.ListTemplatesResponse
	(*response.SaveDraftResponse)(nil),         // 27: wishes.v1.response.SaveDraftResponse
	(*response.GetWishResponse)(nil),           // 28: wishes.v1.response.GetWishResponse
	(*response.UpdateWishResponse)(nil),        // 29: wishes.v1.response.UpdateWishResponse
	(*response.PublishWishResponse)(nil),       // 30: wishes.v1.response.PublishWishResponse
	(*response.DeleteWishResponse)(nil),        // 31: wishes.v1.response.DeleteWishResponse
	(*response.UploadWishPhotoResponse)(nil),   // 32: wishes.v1.response.UploadWishPhotoResponse
	(*response.DeleteWishPhotoResponse)(nil),   // 33: wishes.v1.response.DeleteWishPhotoResponse
	(*response.ExtendWishResponse)(nil),        // 34: wishes.v1.response.ExtendWishResponse
	(*response.RevokeWishResponse)(nil),        // 35: wishes.v1.response.RevokeWishResponse
	(*response.SendWishResponse)(nil),          // 36: wishes.v1.response.SendWishResponse
	(*response.ListWishResponsesResponse)(nil), // 37: wishes.v1.response.ListWishResponsesResponse
	(*response.MarkResponsesSeenResponse)(nil), // 38: wishes.v1.response.MarkResponsesSeenResponse
}
var file_wishes_v1_wishes_proto_depIdxs = []int32{
	1,  // 0: wishes.v1.Wishes.CreateWish:input_type -> wishes.v1.request.CreateWishRequest
	2,  // 1: wishes.v1.Wishes.ListMyWishes:input_type -> wishes.v1.request.ListMyWishesRequest
	3,  // 2: wishes.v1.Wishes.GetWishStats:input_type -> wishes.v1.request.GetWishStatsRequest
	4,  // 3: wishes.v1.Wishes.GetTemplateSchema:input_type -> wishes.v1.request.GetTemplateSchemaRequest
	5,  // 4: wishes.v1.Wishes.SubmitResponse:input_type -> wishes.v1.request.SubmitResponseRequest
	6,  // 5: wishes.v1.Wishes.ReportCard:input_type -> wishes.v1.request.ReportCardRequest
	7,  // 6: wishes.v1.Wishes.ListTemplates:input_type -> wishes.v1.request.ListTemplatesRequest
	8,  // 7: wishes.v1.Wishes.SaveDraft:input_type -> wishes.v1.request.SaveDraftRequest
	9,  // 8: wishes.v1.Wishes.GetWish:input_type -> wishes.v1.request.GetWishRequest
	10, // 9: wishes.v1.Wishes.UpdateWish:input_type -> wishes.v1.request.UpdateWishRequest
	11, // 10: wishes.v1.Wishes.PublishWish:input_type -> wishes.v1.request.PublishWishRequest
	12, // 11: wishes.v1.Wishes.DeleteWish:input_type -> wishes.v1.request.DeleteWishRequest
	13, // 12: wishes.v1.Wishes.UploadWishPhoto:input_type -> wishes.v1.request.UploadWishPhotoRequest
	14, // 13: wishes.v1.Wishes.DeleteWishPhoto:input_type -> wishes.v1.request.DeleteWishPhotoRequest
	15, // 14: wishes.v1.Wishes.ExtendWish:input_type -> wishes.v1.request.ExtendWishRequest
	16, // 15: wishes.v1.Wishes.RevokeWish:input_type -> wishes.v1.request.RevokeWishRequest
	17, // 16: wishes.v1.Wishes.SendWish:input_type -> wishes.v1.request.SendWishRequest
	18, // 17: wishes.v1.Wishes.ListWishResponses:input_type -> wishes.v1.request.ListWishResponsesRequest
	19, // 18: wishes.v1.Wishes.MarkResponsesSeen:input_type -> wishes.v1.request.MarkResponsesSeenRequest
	20, // 19: wishes.v1.Wishes.CreateWish:output_type -> wishes.v1.response.CreateWishResponse
	21, // 20: wishes.v1.Wishes.ListMyWishes:output_type -> wishes.v1.response.ListMyWishesResponse
	22, // 21: wishes.v1.Wishes.GetWishStats:output_type -> wishes.v1.response.GetWishStatsResponse
	23, // 22: wishes.v1.Wishes.GetTemplateSchema:output_type -> wishes.v1.response.GetTemplateSchemaResponse
	24, // 23: wishes.v1.Wishes.SubmitResponse:output_type -> wishes.v1.response.SubmitResponseResponse
	25, // 24: wishes.v1.Wishes.ReportCard:output_type -> wishes.v1.response.ReportCardResponse
	26, // 25: wishes.v1.Wishes.ListTemplates:output_type -> wishes.v1.response.ListTemplatesResponse
	27, // 26: wishes.v1.Wishes.SaveDraft:output_type -> wishes.v1.response.SaveDraftResponse
	28, // 27: wishes.v1.Wishes.GetWish:output_type -> wishes.v1.response.GetWishResponse
	29, // 28: wishes.v1.Wishes.UpdateWish:output_type -> wishes.v1.response.UpdateWishResponse
	30, // 29: wishes.v1.Wishes.PublishWish:output_type -> wishes.v1.response.PublishWishResponse
	31, // 30: wishes.v1.Wishes.DeleteWish:output_type -> wishes.v1.response.DeleteWishResponse
	32, // 31: wishes.v1.Wishes.UploadWishPhoto:output_type -> wishes.v1.response.UploadWishPhotoResponse
	33, // 32: wishes.v1.Wishes.DeleteWishPhoto:output_type -> wishes.v1.response.DeleteWishPhotoResponse
	34, // 33: wishes.v1.Wishes.ExtendWish:output_type -> wishes.v1.response.ExtendWishResponse
	35, // 34: wishes.v1.Wishes.RevokeWish:output_type -> wishes.v1.response.RevokeWishResponse
	36, // 35: wishes.v1.Wishes.SendWish:output_type -> wishes.v1.response.SendWishResponse
	37, // 36: wishes.v1.Wishes.ListWishResponses:output_type -> wishes.v1.response.ListWishResponsesResponse
	38, // 37: wishes.v1.Wishes.MarkResponsesSeen:output_type -> wishes.v1.response.MarkResponsesSeenResponse
	19, // [19:38] is the sub-list for method output_type
	0,  // [0:19] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_wishes_v1_wishes_proto_init() }
func file_wishes_v1_wishes_proto_init() {
	if File_wishes_v1_wishes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wishes_v1_wishes_proto_rawDesc), len(file_wishes_v1_wishes_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wishes_v1_wishes_proto_goTypes,
		DependencyIndexes: file_wishes_v1_wishes_proto_depIdxs,
		EnumInfos:         file_wishes_v1_wishes_proto_enumTypes,
	}.Build()
	File_wishes_v1_wishes_proto = out.File
	file_wishes_v1_wishes_proto_goTypes = nil
	file_wishes_v1_wishes_proto_depIdxs = nil
}
