syntax = "proto3";

package clinic.v1.types.enums;

option go_package = "github.com/arm-1234/protos/clinic/v1/types/enums;enums";

enum ServiceCategory {
  SERVICE_CATEGORY_UNSPECIFIED = 0;
  SERVICE_CATEGORY_DIAGNOSTIC_AUDIOLOGY = 1;
  SERVICE_CATEGORY_PEDIATRIC_AUDIOLOGY = 2;
  SERVICE_CATEGORY_VESTIBULAR = 3;
  SERVICE_CATEGORY_TINNITUS = 4;
  SERVICE_CATEGORY_HEARING_AID = 5;
  SERVICE_CATEGORY_COCHLEAR_IMPLANT = 6;
  SERVICE_CATEGORY_SPEECH_LANGUAGE = 7;
  SERVICE_CATEGORY_VOICE_SWALLOWING = 8;
  SERVICE_CATEGORY_CAPD = 9;
  SERVICE_CATEGORY_GENERAL = 10;
}
