// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: identity/v1/identity.proto

package v1

import (
	context "context"
	request "github.com/arm-1234/protos/identity/v1/request"
	response "github.com/arm-1234/protos/identity/v1/response"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationIdentityAuthenticateWithProvider = "/identity.v1.Identity/AuthenticateWithProvider"
const OperationIdentityGetMe = "/identity.v1.Identity/GetMe"
const OperationIdentityLoginWithPhone = "/identity.v1.Identity/LoginWithPhone"
const OperationIdentityRegisterMerchant = "/identity.v1.Identity/RegisterMerchant"
const OperationIdentityRegisterUser = "/identity.v1.Identity/RegisterUser"

type IdentityHTTPServer interface {
	// AuthenticateWithProvider AuthenticateWithProvider maps a partner/IdP identity to a local user
	// (creating it on first sight) and returns a token.
	AuthenticateWithProvider(context.Context, *request.AuthenticateWithProviderRequest) (*response.AuthResponse, error)
	// GetMe GetMe returns the authenticated caller's user record.
	GetMe(context.Context, *request.GetMeRequest) (*response.GetMeResponse, error)
	// LoginWithPhone LoginWithPhone issues a token for an existing user (stub: no OTP yet).
	LoginWithPhone(context.Context, *request.LoginWithPhoneRequest) (*response.AuthResponse, error)
	// RegisterMerchant RegisterMerchant creates a merchant user + their store and returns a token.
	RegisterMerchant(context.Context, *request.RegisterMerchantRequest) (*response.RegisterMerchantResponse, error)
	// RegisterUser RegisterUser creates a normal shopper account and returns a token.
	RegisterUser(context.Context, *request.RegisterUserRequest) (*response.AuthResponse, error)
}

func RegisterIdentityHTTPServer(s *http.Server, srv IdentityHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/auth/users:register", _Identity_RegisterUser0_HTTP_Handler(srv))
	r.POST("/v1/auth/merchants:register", _Identity_RegisterMerchant0_HTTP_Handler(srv))
	r.POST("/v1/auth/login", _Identity_LoginWithPhone0_HTTP_Handler(srv))
	r.POST("/v1/auth/external", _Identity_AuthenticateWithProvider0_HTTP_Handler(srv))
	r.GET("/v1/auth/me", _Identity_GetMe0_HTTP_Handler(srv))
}

func _Identity_RegisterUser0_HTTP_Handler(srv IdentityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.RegisterUserRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIdentityRegisterUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RegisterUser(ctx, req.(*request.RegisterUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.AuthResponse)
		return ctx.Result(200, reply)
	}
}

func _Identity_RegisterMerchant0_HTTP_Handler(srv IdentityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.RegisterMerchantRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIdentityRegisterMerchant)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RegisterMerchant(ctx, req.(*request.RegisterMerchantRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.RegisterMerchantResponse)
		return ctx.Result(200, reply)
	}
}

func _Identity_LoginWithPhone0_HTTP_Handler(srv IdentityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.LoginWithPhoneRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIdentityLoginWithPhone)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LoginWithPhone(ctx, req.(*request.LoginWithPhoneRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.AuthResponse)
		return ctx.Result(200, reply)
	}
}

func _Identity_AuthenticateWithProvider0_HTTP_Handler(srv IdentityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.AuthenticateWithProviderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIdentityAuthenticateWithProvider)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AuthenticateWithProvider(ctx, req.(*request.AuthenticateWithProviderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.AuthResponse)
		return ctx.Result(200, reply)
	}
}

func _Identity_GetMe0_HTTP_Handler(srv IdentityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.GetMeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIdentityGetMe)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMe(ctx, req.(*request.GetMeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.GetMeResponse)
		return ctx.Result(200, reply)
	}
}

type IdentityHTTPClient interface {
	// AuthenticateWithProvider AuthenticateWithProvider maps a partner/IdP identity to a local user
	// (creating it on first sight) and returns a token.
	AuthenticateWithProvider(ctx context.Context, req *request.AuthenticateWithProviderRequest, opts ...http.CallOption) (rsp *response.AuthResponse, err error)
	// GetMe GetMe returns the authenticated caller's user record.
	GetMe(ctx context.Context, req *request.GetMeRequest, opts ...http.CallOption) (rsp *response.GetMeResponse, err error)
	// LoginWithPhone LoginWithPhone issues a token for an existing user (stub: no OTP yet).
	LoginWithPhone(ctx context.Context, req *request.LoginWithPhoneRequest, opts ...http.CallOption) (rsp *response.AuthResponse, err error)
	// RegisterMerchant RegisterMerchant creates a merchant user + their store and returns a token.
	RegisterMerchant(ctx context.Context, req *request.RegisterMerchantRequest, opts ...http.CallOption) (rsp *response.RegisterMerchantResponse, err error)
	// RegisterUser RegisterUser creates a normal shopper account and returns a token.
	RegisterUser(ctx context.Context, req *request.RegisterUserRequest, opts ...http.CallOption) (rsp *response.AuthResponse, err error)
}

type IdentityHTTPClientImpl struct {
	cc *http.Client
}

func NewIdentityHTTPClient(client *http.Client) IdentityHTTPClient {
	return &IdentityHTTPClientImpl{client}
}

// AuthenticateWithProvider AuthenticateWithProvider maps a partner/IdP identity to a local user
// (creating it on first sight) and returns a token.
func (c *IdentityHTTPClientImpl) AuthenticateWithProvider(ctx context.Context, in *request.AuthenticateWithProviderRequest, opts ...http.CallOption) (*response.AuthResponse, error) {
	var out response.AuthResponse
	pattern := "/v1/auth/external"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIdentityAuthenticateWithProvider))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetMe GetMe returns the authenticated caller's user record.
func (c *IdentityHTTPClientImpl) GetMe(ctx context.Context, in *request.GetMeRequest, opts ...http.CallOption) (*response.GetMeResponse, error) {
	var out response.GetMeResponse
	pattern := "/v1/auth/me"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIdentityGetMe))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// LoginWithPhone LoginWithPhone issues a token for an existing user (stub: no OTP yet).
func (c *IdentityHTTPClientImpl) LoginWithPhone(ctx context.Context, in *request.LoginWithPhoneRequest, opts ...http.CallOption) (*response.AuthResponse, error) {
	var out response.AuthResponse
	pattern := "/v1/auth/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIdentityLoginWithPhone))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RegisterMerchant RegisterMerchant creates a merchant user + their store and returns a token.
func (c *IdentityHTTPClientImpl) RegisterMerchant(ctx context.Context, in *request.RegisterMerchantRequest, opts ...http.CallOption) (*response.RegisterMerchantResponse, error) {
	var out response.RegisterMerchantResponse
	pattern := "/v1/auth/merchants:register"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIdentityRegisterMerchant))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RegisterUser RegisterUser creates a normal shopper account and returns a token.
func (c *IdentityHTTPClientImpl) RegisterUser(ctx context.Context, in *request.RegisterUserRequest, opts ...http.CallOption) (*response.AuthResponse, error) {
	var out response.AuthResponse
	pattern := "/v1/auth/users:register"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIdentityRegisterUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
