// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: identity/v1/identity.proto

package v1

import (
	context "context"
	request "github.com/arm-1234/protos/identity/v1/request"
	response "github.com/arm-1234/protos/identity/v1/response"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationIdentityAuthenticateWithProvider = "/identity.v1.Identity/AuthenticateWithProvider"
const OperationIdentityConfirmPhoneChange = "/identity.v1.Identity/ConfirmPhoneChange"
const OperationIdentityGetMe = "/identity.v1.Identity/GetMe"
const OperationIdentityLoginWithIdentifier = "/identity.v1.Identity/LoginWithIdentifier"
const OperationIdentityLoginWithPhone = "/identity.v1.Identity/LoginWithPhone"
const OperationIdentityRegisterMerchant = "/identity.v1.Identity/RegisterMerchant"
const OperationIdentityRegisterPushToken = "/identity.v1.Identity/RegisterPushToken"
const OperationIdentityRegisterUser = "/identity.v1.Identity/RegisterUser"
const OperationIdentityRequestOtp = "/identity.v1.Identity/RequestOtp"
const OperationIdentityRequestPhoneChange = "/identity.v1.Identity/RequestPhoneChange"
const OperationIdentitySetPassword = "/identity.v1.Identity/SetPassword"
const OperationIdentityUpdateProfile = "/identity.v1.Identity/UpdateProfile"
const OperationIdentityVerifyOtp = "/identity.v1.Identity/VerifyOtp"

type IdentityHTTPServer interface {
	AuthenticateWithProvider(context.Context, *request.AuthenticateWithProviderRequest) (*response.AuthResponse, error)
	ConfirmPhoneChange(context.Context, *request.ConfirmPhoneChangeRequest) (*response.GetMeResponse, error)
	GetMe(context.Context, *request.GetMeRequest) (*response.GetMeResponse, error)
	// LoginWithIdentifier Password login by email or phone. LoginWithPhone is kept for existing
	// merchant-store clients; new clients should call this.
	LoginWithIdentifier(context.Context, *request.LoginWithIdentifierRequest) (*response.AuthResponse, error)
	LoginWithPhone(context.Context, *request.LoginWithPhoneRequest) (*response.AuthResponse, error)
	RegisterMerchant(context.Context, *request.RegisterMerchantRequest) (*response.RegisterMerchantResponse, error)
	RegisterPushToken(context.Context, *request.RegisterPushTokenRequest) (*response.RegisterPushTokenResponse, error)
	RegisterUser(context.Context, *request.RegisterUserRequest) (*response.AuthResponse, error)
	RequestOtp(context.Context, *request.RequestOtpRequest) (*response.RequestOtpResponse, error)
	RequestPhoneChange(context.Context, *request.RequestPhoneChangeRequest) (*response.RequestOtpResponse, error)
	SetPassword(context.Context, *request.SetPasswordRequest) (*response.AuthResponse, error)
	UpdateProfile(context.Context, *request.UpdateProfileRequest) (*response.GetMeResponse, error)
	VerifyOtp(context.Context, *request.VerifyOtpRequest) (*response.AuthResponse, error)
}

func RegisterIdentityHTTPServer(s *http.Server, srv IdentityHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/auth/users:register", _Identity_RegisterUser0_HTTP_Handler(srv))
	r.POST("/v1/auth/merchants:register", _Identity_RegisterMerchant0_HTTP_Handler(srv))
	r.POST("/v1/auth/login", _Identity_LoginWithPhone0_HTTP_Handler(srv))
	r.POST("/v1/auth/login:identifier", _Identity_LoginWithIdentifier0_HTTP_Handler(srv))
	r.POST("/v1/auth/password:set", _Identity_SetPassword0_HTTP_Handler(srv))
	r.PATCH("/v1/auth/me", _Identity_UpdateProfile0_HTTP_Handler(srv))
	r.POST("/v1/auth/external", _Identity_AuthenticateWithProvider0_HTTP_Handler(srv))
	r.GET("/v1/auth/me", _Identity_GetMe0_HTTP_Handler(srv))
	r.POST("/v1/push/register", _Identity_RegisterPushToken0_HTTP_Handler(srv))
	r.POST("/v1/auth/otp:request", _Identity_RequestOtp0_HTTP_Handler(srv))
	r.POST("/v1/auth/otp:verify", _Identity_VerifyOtp0_HTTP_Handler(srv))
	r.POST("/v1/me/phone:request", _Identity_RequestPhoneChange0_HTTP_Handler(srv))
	r.POST("/v1/me/phone:confirm", _Identity_ConfirmPhoneChange0_HTTP_Handler(srv))
}

func _Identity_RegisterUser0_HTTP_Handler(srv IdentityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.RegisterUserRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIdentityRegisterUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RegisterUser(ctx, req.(*request.RegisterUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.AuthResponse)
		return ctx.Result(200, reply)
	}
}

func _Identity_RegisterMerchant0_HTTP_Handler(srv IdentityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.RegisterMerchantRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIdentityRegisterMerchant)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RegisterMerchant(ctx, req.(*request.RegisterMerchantRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.RegisterMerchantResponse)
		return ctx.Result(200, reply)
	}
}

func _Identity_LoginWithPhone0_HTTP_Handler(srv IdentityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.LoginWithPhoneRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIdentityLoginWithPhone)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LoginWithPhone(ctx, req.(*request.LoginWithPhoneRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.AuthResponse)
		return ctx.Result(200, reply)
	}
}

func _Identity_LoginWithIdentifier0_HTTP_Handler(srv IdentityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.LoginWithIdentifierRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIdentityLoginWithIdentifier)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LoginWithIdentifier(ctx, req.(*request.LoginWithIdentifierRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.AuthResponse)
		return ctx.Result(200, reply)
	}
}

func _Identity_SetPassword0_HTTP_Handler(srv IdentityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.SetPasswordRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIdentitySetPassword)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetPassword(ctx, req.(*request.SetPasswordRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.AuthResponse)
		return ctx.Result(200, reply)
	}
}

func _Identity_UpdateProfile0_HTTP_Handler(srv IdentityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.UpdateProfileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIdentityUpdateProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateProfile(ctx, req.(*request.UpdateProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.GetMeResponse)
		return ctx.Result(200, reply)
	}
}

func _Identity_AuthenticateWithProvider0_HTTP_Handler(srv IdentityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.AuthenticateWithProviderRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIdentityAuthenticateWithProvider)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AuthenticateWithProvider(ctx, req.(*request.AuthenticateWithProviderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.AuthResponse)
		return ctx.Result(200, reply)
	}
}

func _Identity_GetMe0_HTTP_Handler(srv IdentityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.GetMeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIdentityGetMe)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMe(ctx, req.(*request.GetMeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.GetMeResponse)
		return ctx.Result(200, reply)
	}
}

func _Identity_RegisterPushToken0_HTTP_Handler(srv IdentityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.RegisterPushTokenRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIdentityRegisterPushToken)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RegisterPushToken(ctx, req.(*request.RegisterPushTokenRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.RegisterPushTokenResponse)
		return ctx.Result(200, reply)
	}
}

func _Identity_RequestOtp0_HTTP_Handler(srv IdentityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.RequestOtpRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIdentityRequestOtp)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RequestOtp(ctx, req.(*request.RequestOtpRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.RequestOtpResponse)
		return ctx.Result(200, reply)
	}
}

func _Identity_VerifyOtp0_HTTP_Handler(srv IdentityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.VerifyOtpRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIdentityVerifyOtp)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.VerifyOtp(ctx, req.(*request.VerifyOtpRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.AuthResponse)
		return ctx.Result(200, reply)
	}
}

func _Identity_RequestPhoneChange0_HTTP_Handler(srv IdentityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.RequestPhoneChangeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIdentityRequestPhoneChange)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RequestPhoneChange(ctx, req.(*request.RequestPhoneChangeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.RequestOtpResponse)
		return ctx.Result(200, reply)
	}
}

func _Identity_ConfirmPhoneChange0_HTTP_Handler(srv IdentityHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.ConfirmPhoneChangeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIdentityConfirmPhoneChange)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ConfirmPhoneChange(ctx, req.(*request.ConfirmPhoneChangeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.GetMeResponse)
		return ctx.Result(200, reply)
	}
}

type IdentityHTTPClient interface {
	AuthenticateWithProvider(ctx context.Context, req *request.AuthenticateWithProviderRequest, opts ...http.CallOption) (rsp *response.AuthResponse, err error)
	ConfirmPhoneChange(ctx context.Context, req *request.ConfirmPhoneChangeRequest, opts ...http.CallOption) (rsp *response.GetMeResponse, err error)
	GetMe(ctx context.Context, req *request.GetMeRequest, opts ...http.CallOption) (rsp *response.GetMeResponse, err error)
	// LoginWithIdentifier Password login by email or phone. LoginWithPhone is kept for existing
	// merchant-store clients; new clients should call this.
	LoginWithIdentifier(ctx context.Context, req *request.LoginWithIdentifierRequest, opts ...http.CallOption) (rsp *response.AuthResponse, err error)
	LoginWithPhone(ctx context.Context, req *request.LoginWithPhoneRequest, opts ...http.CallOption) (rsp *response.AuthResponse, err error)
	RegisterMerchant(ctx context.Context, req *request.RegisterMerchantRequest, opts ...http.CallOption) (rsp *response.RegisterMerchantResponse, err error)
	RegisterPushToken(ctx context.Context, req *request.RegisterPushTokenRequest, opts ...http.CallOption) (rsp *response.RegisterPushTokenResponse, err error)
	RegisterUser(ctx context.Context, req *request.RegisterUserRequest, opts ...http.CallOption) (rsp *response.AuthResponse, err error)
	RequestOtp(ctx context.Context, req *request.RequestOtpRequest, opts ...http.CallOption) (rsp *response.RequestOtpResponse, err error)
	RequestPhoneChange(ctx context.Context, req *request.RequestPhoneChangeRequest, opts ...http.CallOption) (rsp *response.RequestOtpResponse, err error)
	SetPassword(ctx context.Context, req *request.SetPasswordRequest, opts ...http.CallOption) (rsp *response.AuthResponse, err error)
	UpdateProfile(ctx context.Context, req *request.UpdateProfileRequest, opts ...http.CallOption) (rsp *response.GetMeResponse, err error)
	VerifyOtp(ctx context.Context, req *request.VerifyOtpRequest, opts ...http.CallOption) (rsp *response.AuthResponse, err error)
}

type IdentityHTTPClientImpl struct {
	cc *http.Client
}

func NewIdentityHTTPClient(client *http.Client) IdentityHTTPClient {
	return &IdentityHTTPClientImpl{client}
}

func (c *IdentityHTTPClientImpl) AuthenticateWithProvider(ctx context.Context, in *request.AuthenticateWithProviderRequest, opts ...http.CallOption) (*response.AuthResponse, error) {
	var out response.AuthResponse
	pattern := "/v1/auth/external"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIdentityAuthenticateWithProvider))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IdentityHTTPClientImpl) ConfirmPhoneChange(ctx context.Context, in *request.ConfirmPhoneChangeRequest, opts ...http.CallOption) (*response.GetMeResponse, error) {
	var out response.GetMeResponse
	pattern := "/v1/me/phone:confirm"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIdentityConfirmPhoneChange))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IdentityHTTPClientImpl) GetMe(ctx context.Context, in *request.GetMeRequest, opts ...http.CallOption) (*response.GetMeResponse, error) {
	var out response.GetMeResponse
	pattern := "/v1/auth/me"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationIdentityGetMe))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// LoginWithIdentifier Password login by email or phone. LoginWithPhone is kept for existing
// merchant-store clients; new clients should call this.
func (c *IdentityHTTPClientImpl) LoginWithIdentifier(ctx context.Context, in *request.LoginWithIdentifierRequest, opts ...http.CallOption) (*response.AuthResponse, error) {
	var out response.AuthResponse
	pattern := "/v1/auth/login:identifier"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIdentityLoginWithIdentifier))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IdentityHTTPClientImpl) LoginWithPhone(ctx context.Context, in *request.LoginWithPhoneRequest, opts ...http.CallOption) (*response.AuthResponse, error) {
	var out response.AuthResponse
	pattern := "/v1/auth/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIdentityLoginWithPhone))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IdentityHTTPClientImpl) RegisterMerchant(ctx context.Context, in *request.RegisterMerchantRequest, opts ...http.CallOption) (*response.RegisterMerchantResponse, error) {
	var out response.RegisterMerchantResponse
	pattern := "/v1/auth/merchants:register"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIdentityRegisterMerchant))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IdentityHTTPClientImpl) RegisterPushToken(ctx context.Context, in *request.RegisterPushTokenRequest, opts ...http.CallOption) (*response.RegisterPushTokenResponse, error) {
	var out response.RegisterPushTokenResponse
	pattern := "/v1/push/register"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIdentityRegisterPushToken))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IdentityHTTPClientImpl) RegisterUser(ctx context.Context, in *request.RegisterUserRequest, opts ...http.CallOption) (*response.AuthResponse, error) {
	var out response.AuthResponse
	pattern := "/v1/auth/users:register"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIdentityRegisterUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IdentityHTTPClientImpl) RequestOtp(ctx context.Context, in *request.RequestOtpRequest, opts ...http.CallOption) (*response.RequestOtpResponse, error) {
	var out response.RequestOtpResponse
	pattern := "/v1/auth/otp:request"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIdentityRequestOtp))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IdentityHTTPClientImpl) RequestPhoneChange(ctx context.Context, in *request.RequestPhoneChangeRequest, opts ...http.CallOption) (*response.RequestOtpResponse, error) {
	var out response.RequestOtpResponse
	pattern := "/v1/me/phone:request"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIdentityRequestPhoneChange))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IdentityHTTPClientImpl) SetPassword(ctx context.Context, in *request.SetPasswordRequest, opts ...http.CallOption) (*response.AuthResponse, error) {
	var out response.AuthResponse
	pattern := "/v1/auth/password:set"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIdentitySetPassword))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IdentityHTTPClientImpl) UpdateProfile(ctx context.Context, in *request.UpdateProfileRequest, opts ...http.CallOption) (*response.GetMeResponse, error) {
	var out response.GetMeResponse
	pattern := "/v1/auth/me"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIdentityUpdateProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *IdentityHTTPClientImpl) VerifyOtp(ctx context.Context, in *request.VerifyOtpRequest, opts ...http.CallOption) (*response.AuthResponse, error) {
	var out response.AuthResponse
	pattern := "/v1/auth/otp:verify"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIdentityVerifyOtp))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
