// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsIdentityUnspecified(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_IDENTITY_UNSPECIFIED.String() && e.Code == 500
}

func ErrorIdentityUnspecified(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_IDENTITY_UNSPECIFIED.String(), fmt.Sprintf(format, args...))
}

func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_NOT_FOUND.String() && e.Code == 404
}

func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_USER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsUserAlreadyExists(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_ALREADY_EXISTS.String() && e.Code == 409
}

func ErrorUserAlreadyExists(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_USER_ALREADY_EXISTS.String(), fmt.Sprintf(format, args...))
}

func IsIdentityInvalidRequest(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_IDENTITY_INVALID_REQUEST.String() && e.Code == 400
}

func ErrorIdentityInvalidRequest(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_IDENTITY_INVALID_REQUEST.String(), fmt.Sprintf(format, args...))
}

func IsIdentityUnauthenticated(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_IDENTITY_UNAUTHENTICATED.String() && e.Code == 401
}

func ErrorIdentityUnauthenticated(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_IDENTITY_UNAUTHENTICATED.String(), fmt.Sprintf(format, args...))
}

func IsIdentityInvalidCredentials(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_IDENTITY_INVALID_CREDENTIALS.String() && e.Code == 401
}

func ErrorIdentityInvalidCredentials(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_IDENTITY_INVALID_CREDENTIALS.String(), fmt.Sprintf(format, args...))
}

func IsIdentityPasswordRequired(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_IDENTITY_PASSWORD_REQUIRED.String() && e.Code == 409
}

func ErrorIdentityPasswordRequired(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_IDENTITY_PASSWORD_REQUIRED.String(), fmt.Sprintf(format, args...))
}

func IsIdentityOtpInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_IDENTITY_OTP_INVALID.String() && e.Code == 401
}

func ErrorIdentityOtpInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_IDENTITY_OTP_INVALID.String(), fmt.Sprintf(format, args...))
}

func IsIdentityOtpExpired(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_IDENTITY_OTP_EXPIRED.String() && e.Code == 410
}

func ErrorIdentityOtpExpired(format string, args ...interface{}) *errors.Error {
	return errors.New(410, ErrorReason_IDENTITY_OTP_EXPIRED.String(), fmt.Sprintf(format, args...))
}

func IsIdentityOtpRateLimited(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_IDENTITY_OTP_RATE_LIMITED.String() && e.Code == 429
}

func ErrorIdentityOtpRateLimited(format string, args ...interface{}) *errors.Error {
	return errors.New(429, ErrorReason_IDENTITY_OTP_RATE_LIMITED.String(), fmt.Sprintf(format, args...))
}

func IsIdentityOtpDeliveryFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_IDENTITY_OTP_DELIVERY_FAILED.String() && e.Code == 502
}

func ErrorIdentityOtpDeliveryFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(502, ErrorReason_IDENTITY_OTP_DELIVERY_FAILED.String(), fmt.Sprintf(format, args...))
}

func IsIdentityWrongApp(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_IDENTITY_WRONG_APP.String() && e.Code == 403
}

func ErrorIdentityWrongApp(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ErrorReason_IDENTITY_WRONG_APP.String(), fmt.Sprintf(format, args...))
}
