// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsIdentityUnspecified(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_IDENTITY_UNSPECIFIED.String() && e.Code == 500
}

func ErrorIdentityUnspecified(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_IDENTITY_UNSPECIFIED.String(), fmt.Sprintf(format, args...))
}

func IsUserNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_NOT_FOUND.String() && e.Code == 404
}

func ErrorUserNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_USER_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsUserAlreadyExists(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_ALREADY_EXISTS.String() && e.Code == 409
}

func ErrorUserAlreadyExists(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_USER_ALREADY_EXISTS.String(), fmt.Sprintf(format, args...))
}

func IsIdentityInvalidRequest(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_IDENTITY_INVALID_REQUEST.String() && e.Code == 400
}

func ErrorIdentityInvalidRequest(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_IDENTITY_INVALID_REQUEST.String(), fmt.Sprintf(format, args...))
}

func IsIdentityUnauthenticated(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_IDENTITY_UNAUTHENTICATED.String() && e.Code == 401
}

func ErrorIdentityUnauthenticated(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_IDENTITY_UNAUTHENTICATED.String(), fmt.Sprintf(format, args...))
}
