// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: review/v1/response/review_response.proto

package response

import (
	types "github.com/arm-1234/protos/review/v1/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpsertReviewResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Review             *types.ReviewInfo      `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	ProductRatingAvg   float64                `protobuf:"fixed64,2,opt,name=product_rating_avg,json=productRatingAvg,proto3" json:"product_rating_avg,omitempty"`
	ProductRatingCount int64                  `protobuf:"varint,3,opt,name=product_rating_count,json=productRatingCount,proto3" json:"product_rating_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpsertReviewResponse) Reset() {
	*x = UpsertReviewResponse{}
	mi := &file_review_v1_response_review_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertReviewResponse) ProtoMessage() {}

func (x *UpsertReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_response_review_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertReviewResponse.ProtoReflect.Descriptor instead.
func (*UpsertReviewResponse) Descriptor() ([]byte, []int) {
	return file_review_v1_response_review_response_proto_rawDescGZIP(), []int{0}
}

func (x *UpsertReviewResponse) GetReview() *types.ReviewInfo {
	if x != nil {
		return x.Review
	}
	return nil
}

func (x *UpsertReviewResponse) GetProductRatingAvg() float64 {
	if x != nil {
		return x.ProductRatingAvg
	}
	return 0
}

func (x *UpsertReviewResponse) GetProductRatingCount() int64 {
	if x != nil {
		return x.ProductRatingCount
	}
	return 0
}

type GetMyReviewResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// review is unset if the caller has not reviewed this product.
	Review        *types.ReviewInfo `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	HasReviewed   bool              `protobuf:"varint,2,opt,name=has_reviewed,json=hasReviewed,proto3" json:"has_reviewed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyReviewResponse) Reset() {
	*x = GetMyReviewResponse{}
	mi := &file_review_v1_response_review_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyReviewResponse) ProtoMessage() {}

func (x *GetMyReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_response_review_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyReviewResponse.ProtoReflect.Descriptor instead.
func (*GetMyReviewResponse) Descriptor() ([]byte, []int) {
	return file_review_v1_response_review_response_proto_rawDescGZIP(), []int{1}
}

func (x *GetMyReviewResponse) GetReview() *types.ReviewInfo {
	if x != nil {
		return x.Review
	}
	return nil
}

func (x *GetMyReviewResponse) GetHasReviewed() bool {
	if x != nil {
		return x.HasReviewed
	}
	return false
}

type ListReviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*types.ReviewInfo    `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	PageNumber    int64                  `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int64                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	TotalRecords  int64                  `protobuf:"varint,5,opt,name=total_records,json=totalRecords,proto3" json:"total_records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsResponse) Reset() {
	*x = ListReviewsResponse{}
	mi := &file_review_v1_response_review_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsResponse) ProtoMessage() {}

func (x *ListReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_v1_response_review_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsResponse.ProtoReflect.Descriptor instead.
func (*ListReviewsResponse) Descriptor() ([]byte, []int) {
	return file_review_v1_response_review_response_proto_rawDescGZIP(), []int{2}
}

func (x *ListReviewsResponse) GetReviews() []*types.ReviewInfo {
	if x != nil {
		return x.Reviews
	}
	return nil
}

func (x *ListReviewsResponse) GetPageNumber() int64 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ListReviewsResponse) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListReviewsResponse) GetTotalPages() int64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *ListReviewsResponse) GetTotalRecords() int64 {
	if x != nil {
		return x.TotalRecords
	}
	return 0
}

var File_review_v1_response_review_response_proto protoreflect.FileDescriptor

const file_review_v1_response_review_response_proto_rawDesc = "" +
	"\n" +
	"(review/v1/response/review_response.proto\x12\x12review.v1.response\x1a\x1creview/v1/types/review.proto\"\xab\x01\n" +
	"\x14UpsertReviewResponse\x123\n" +
	"\x06review\x18\x01 \x01(\v2\x1b.review.v1.types.ReviewInfoR\x06review\x12,\n" +
	"\x12product_rating_avg\x18\x02 \x01(\x01R\x10productRatingAvg\x120\n" +
	"\x14product_rating_count\x18\x03 \x01(\x03R\x12productRatingCount\"m\n" +
	"\x13GetMyReviewResponse\x123\n" +
	"\x06review\x18\x01 \x01(\v2\x1b.review.v1.types.ReviewInfoR\x06review\x12!\n" +
	"\fhas_reviewed\x18\x02 \x01(\bR\vhasReviewed\"\xd0\x01\n" +
	"\x13ListReviewsResponse\x125\n" +
	"\areviews\x18\x01 \x03(\v2\x1b.review.v1.types.ReviewInfoR\areviews\x12\x1f\n" +
	"\vpage_number\x18\x02 \x01(\x03R\n" +
	"pageNumber\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x03R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x03R\n" +
	"totalPages\x12#\n" +
	"\rtotal_records\x18\x05 \x01(\x03R\ftotalRecordsB8Z6github.com/arm-1234/protos/review/v1/response;responseb\x06proto3"

var (
	file_review_v1_response_review_response_proto_rawDescOnce sync.Once
	file_review_v1_response_review_response_proto_rawDescData []byte
)

func file_review_v1_response_review_response_proto_rawDescGZIP() []byte {
	file_review_v1_response_review_response_proto_rawDescOnce.Do(func() {
		file_review_v1_response_review_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_review_v1_response_review_response_proto_rawDesc), len(file_review_v1_response_review_response_proto_rawDesc)))
	})
	return file_review_v1_response_review_response_proto_rawDescData
}

var file_review_v1_response_review_response_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_review_v1_response_review_response_proto_goTypes = []any{
	(*UpsertReviewResponse)(nil), // 0: review.v1.response.UpsertReviewResponse
	(*GetMyReviewResponse)(nil),  // 1: review.v1.response.GetMyReviewResponse
	(*ListReviewsResponse)(nil),  // 2: review.v1.response.ListReviewsResponse
	(*types.ReviewInfo)(nil),     // 3: review.v1.types.ReviewInfo
}
var file_review_v1_response_review_response_proto_depIdxs = []int32{
	3, // 0: review.v1.response.UpsertReviewResponse.review:type_name -> review.v1.types.ReviewInfo
	3, // 1: review.v1.response.GetMyReviewResponse.review:type_name -> review.v1.types.ReviewInfo
	3, // 2: review.v1.response.ListReviewsResponse.reviews:type_name -> review.v1.types.ReviewInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_review_v1_response_review_response_proto_init() }
func file_review_v1_response_review_response_proto_init() {
	if File_review_v1_response_review_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_review_v1_response_review_response_proto_rawDesc), len(file_review_v1_response_review_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_review_v1_response_review_response_proto_goTypes,
		DependencyIndexes: file_review_v1_response_review_response_proto_depIdxs,
		MessageInfos:      file_review_v1_response_review_response_proto_msgTypes,
	}.Build()
	File_review_v1_response_review_response_proto = out.File
	file_review_v1_response_review_response_proto_goTypes = nil
	file_review_v1_response_review_response_proto_depIdxs = nil
}
