// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: wishes/v1/types/response.proto

package types

import (
	enums "github.com/arm-1234/protos/wishes/v1/types/enums"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WishResponseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseId    string                 `protobuf:"bytes,1,opt,name=response_id,json=responseId,proto3" json:"response_id,omitempty"`
	WishId        string                 `protobuf:"bytes,2,opt,name=wish_id,json=wishId,proto3" json:"wish_id,omitempty"`
	Kind          enums.ResponseKind     `protobuf:"varint,3,opt,name=kind,proto3,enum=wishes.v1.types.enums.ResponseKind" json:"kind,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SeenAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=seen_at,json=seenAt,proto3" json:"seen_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WishResponseInfo) Reset() {
	*x = WishResponseInfo{}
	mi := &file_wishes_v1_types_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WishResponseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WishResponseInfo) ProtoMessage() {}

func (x *WishResponseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_types_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WishResponseInfo.ProtoReflect.Descriptor instead.
func (*WishResponseInfo) Descriptor() ([]byte, []int) {
	return file_wishes_v1_types_response_proto_rawDescGZIP(), []int{0}
}

func (x *WishResponseInfo) GetResponseId() string {
	if x != nil {
		return x.ResponseId
	}
	return ""
}

func (x *WishResponseInfo) GetWishId() string {
	if x != nil {
		return x.WishId
	}
	return ""
}

func (x *WishResponseInfo) GetKind() enums.ResponseKind {
	if x != nil {
		return x.Kind
	}
	return enums.ResponseKind(0)
}

func (x *WishResponseInfo) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *WishResponseInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WishResponseInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WishResponseInfo) GetSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SeenAt
	}
	return nil
}

var File_wishes_v1_types_response_proto protoreflect.FileDescriptor

const file_wishes_v1_types_response_proto_rawDesc = "" +
	"\n" +
	"\x1ewishes/v1/types/response.proto\x12\x0fwishes.v1.types\x1a\x1fgoogle/protobuf/timestamp.proto\x1a)wishes/v1/types/enums/response_kind.proto\"\xa5\x02\n" +
	"\x10WishResponseInfo\x12\x1f\n" +
	"\vresponse_id\x18\x01 \x01(\tR\n" +
	"responseId\x12\x17\n" +
	"\awish_id\x18\x02 \x01(\tR\x06wishId\x127\n" +
	"\x04kind\x18\x03 \x01(\x0e2#.wishes.v1.types.enums.ResponseKindR\x04kind\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x123\n" +
	"\aseen_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x06seenAtB2Z0github.com/arm-1234/protos/wishes/v1/types;typesb\x06proto3"

var (
	file_wishes_v1_types_response_proto_rawDescOnce sync.Once
	file_wishes_v1_types_response_proto_rawDescData []byte
)

func file_wishes_v1_types_response_proto_rawDescGZIP() []byte {
	file_wishes_v1_types_response_proto_rawDescOnce.Do(func() {
		file_wishes_v1_types_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wishes_v1_types_response_proto_rawDesc), len(file_wishes_v1_types_response_proto_rawDesc)))
	})
	return file_wishes_v1_types_response_proto_rawDescData
}

var file_wishes_v1_types_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_wishes_v1_types_response_proto_goTypes = []any{
	(*WishResponseInfo)(nil),      // 0: wishes.v1.types.WishResponseInfo
	(enums.ResponseKind)(0),       // 1: wishes.v1.types.enums.ResponseKind
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_wishes_v1_types_response_proto_depIdxs = []int32{
	1, // 0: wishes.v1.types.WishResponseInfo.kind:type_name -> wishes.v1.types.enums.ResponseKind
	2, // 1: wishes.v1.types.WishResponseInfo.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: wishes.v1.types.WishResponseInfo.seen_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_wishes_v1_types_response_proto_init() }
func file_wishes_v1_types_response_proto_init() {
	if File_wishes_v1_types_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wishes_v1_types_response_proto_rawDesc), len(file_wishes_v1_types_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wishes_v1_types_response_proto_goTypes,
		DependencyIndexes: file_wishes_v1_types_response_proto_depIdxs,
		MessageInfos:      file_wishes_v1_types_response_proto_msgTypes,
	}.Build()
	File_wishes_v1_types_response_proto = out.File
	file_wishes_v1_types_response_proto_goTypes = nil
	file_wishes_v1_types_response_proto_depIdxs = nil
}
