syntax = "proto3";

package merchant.v1.types;

import "google/protobuf/timestamp.proto";
import "validate/validate.proto";
import "merchant/v1/types/enums/weekday.proto";

option go_package = "github.com/arm-1234/protos/merchant/v1/types;types";

message OpeningWindow {
  int32 open_minute = 1 [(validate.rules).int32 = {gte: 0, lte: 1439}];
  int32 close_minute = 2 [(validate.rules).int32 = {gte: 1, lte: 1440}];
}

message DayHours {
  merchant.v1.types.enums.Weekday day = 1 [(validate.rules).enum = {defined_only: true, not_in: [0]}];
  repeated OpeningWindow windows = 2 [(validate.rules).repeated = {max_items: 4}];
}

message StoreHours {
  repeated DayHours days = 1 [(validate.rules).repeated = {max_items: 7}];
}

message StoreAvailability {
  bool open_now = 1;
  bool manually_closed = 2;
  string next_change_label = 3;
  google.protobuf.Timestamp next_change_at = 4;
}
