// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: fitness/v1/types/enums/anti_cheat_status.proto

package enums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Outcome of the server-side anti-cheat evaluation of a walk session.
//
// ACCEPTED credits points immediately and irreversibly. FLAGGED also credits,
// but the ledger entry stays reversible for a review window and the session
// lands in the moderation queue, so a false positive never costs an honest
// user their points. REJECTED credits nothing.
type AntiCheatStatus int32

const (
	AntiCheatStatus_ANTI_CHEAT_STATUS_UNSPECIFIED AntiCheatStatus = 0
	AntiCheatStatus_ANTI_CHEAT_STATUS_ACCEPTED    AntiCheatStatus = 1
	AntiCheatStatus_ANTI_CHEAT_STATUS_FLAGGED     AntiCheatStatus = 2
	AntiCheatStatus_ANTI_CHEAT_STATUS_REJECTED    AntiCheatStatus = 3
	// Not enough samples to judge yet; session is still open.
	AntiCheatStatus_ANTI_CHEAT_STATUS_PENDING AntiCheatStatus = 4
)

// Enum value maps for AntiCheatStatus.
var (
	AntiCheatStatus_name = map[int32]string{
		0: "ANTI_CHEAT_STATUS_UNSPECIFIED",
		1: "ANTI_CHEAT_STATUS_ACCEPTED",
		2: "ANTI_CHEAT_STATUS_FLAGGED",
		3: "ANTI_CHEAT_STATUS_REJECTED",
		4: "ANTI_CHEAT_STATUS_PENDING",
	}
	AntiCheatStatus_value = map[string]int32{
		"ANTI_CHEAT_STATUS_UNSPECIFIED": 0,
		"ANTI_CHEAT_STATUS_ACCEPTED":    1,
		"ANTI_CHEAT_STATUS_FLAGGED":     2,
		"ANTI_CHEAT_STATUS_REJECTED":    3,
		"ANTI_CHEAT_STATUS_PENDING":     4,
	}
)

func (x AntiCheatStatus) Enum() *AntiCheatStatus {
	p := new(AntiCheatStatus)
	*p = x
	return p
}

func (x AntiCheatStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AntiCheatStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_fitness_v1_types_enums_anti_cheat_status_proto_enumTypes[0].Descriptor()
}

func (AntiCheatStatus) Type() protoreflect.EnumType {
	return &file_fitness_v1_types_enums_anti_cheat_status_proto_enumTypes[0]
}

func (x AntiCheatStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AntiCheatStatus.Descriptor instead.
func (AntiCheatStatus) EnumDescriptor() ([]byte, []int) {
	return file_fitness_v1_types_enums_anti_cheat_status_proto_rawDescGZIP(), []int{0}
}

var File_fitness_v1_types_enums_anti_cheat_status_proto protoreflect.FileDescriptor

const file_fitness_v1_types_enums_anti_cheat_status_proto_rawDesc = "" +
	"\n" +
	".fitness/v1/types/enums/anti_cheat_status.proto\x12\x16fitness.v1.types.enums*\xb2\x01\n" +
	"\x0fAntiCheatStatus\x12!\n" +
	"\x1dANTI_CHEAT_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aANTI_CHEAT_STATUS_ACCEPTED\x10\x01\x12\x1d\n" +
	"\x19ANTI_CHEAT_STATUS_FLAGGED\x10\x02\x12\x1e\n" +
	"\x1aANTI_CHEAT_STATUS_REJECTED\x10\x03\x12\x1d\n" +
	"\x19ANTI_CHEAT_STATUS_PENDING\x10\x04B9Z7github.com/arm-1234/protos/fitness/v1/types/enums;enumsb\x06proto3"

var (
	file_fitness_v1_types_enums_anti_cheat_status_proto_rawDescOnce sync.Once
	file_fitness_v1_types_enums_anti_cheat_status_proto_rawDescData []byte
)

func file_fitness_v1_types_enums_anti_cheat_status_proto_rawDescGZIP() []byte {
	file_fitness_v1_types_enums_anti_cheat_status_proto_rawDescOnce.Do(func() {
		file_fitness_v1_types_enums_anti_cheat_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fitness_v1_types_enums_anti_cheat_status_proto_rawDesc), len(file_fitness_v1_types_enums_anti_cheat_status_proto_rawDesc)))
	})
	return file_fitness_v1_types_enums_anti_cheat_status_proto_rawDescData
}

var file_fitness_v1_types_enums_anti_cheat_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fitness_v1_types_enums_anti_cheat_status_proto_goTypes = []any{
	(AntiCheatStatus)(0), // 0: fitness.v1.types.enums.AntiCheatStatus
}
var file_fitness_v1_types_enums_anti_cheat_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fitness_v1_types_enums_anti_cheat_status_proto_init() }
func file_fitness_v1_types_enums_anti_cheat_status_proto_init() {
	if File_fitness_v1_types_enums_anti_cheat_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fitness_v1_types_enums_anti_cheat_status_proto_rawDesc), len(file_fitness_v1_types_enums_anti_cheat_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fitness_v1_types_enums_anti_cheat_status_proto_goTypes,
		DependencyIndexes: file_fitness_v1_types_enums_anti_cheat_status_proto_depIdxs,
		EnumInfos:         file_fitness_v1_types_enums_anti_cheat_status_proto_enumTypes,
	}.Build()
	File_fitness_v1_types_enums_anti_cheat_status_proto = out.File
	file_fitness_v1_types_enums_anti_cheat_status_proto_goTypes = nil
	file_fitness_v1_types_enums_anti_cheat_status_proto_depIdxs = nil
}
