// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: fitness/v1/types/leaderboard.proto

package types

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	enums "github.com/arm-1234/protos/fitness/v1/types/enums"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = enums.CompetitionScope(0)
)

// Validate checks the field values on LeaderboardEntry with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *LeaderboardEntry) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LeaderboardEntry with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LeaderboardEntryMultiError, or nil if none found.
func (m *LeaderboardEntry) ValidateAll() error {
	return m.validate(true)
}

func (m *LeaderboardEntry) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Rank

	// no validation rules for UserId

	// no validation rules for DisplayName

	// no validation rules for AvatarUrl

	// no validation rules for Score

	if all {
		switch v := interface{}(m.GetRegion()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LeaderboardEntryValidationError{
					field:  "Region",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LeaderboardEntryValidationError{
					field:  "Region",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRegion()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LeaderboardEntryValidationError{
				field:  "Region",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for RankDelta

	// no validation rules for IsMe

	if len(errors) > 0 {
		return LeaderboardEntryMultiError(errors)
	}

	return nil
}

// LeaderboardEntryMultiError is an error wrapping multiple validation errors
// returned by LeaderboardEntry.ValidateAll() if the designated constraints
// aren't met.
type LeaderboardEntryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LeaderboardEntryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LeaderboardEntryMultiError) AllErrors() []error { return m }

// LeaderboardEntryValidationError is the validation error returned by
// LeaderboardEntry.Validate if the designated constraints aren't met.
type LeaderboardEntryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LeaderboardEntryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LeaderboardEntryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LeaderboardEntryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LeaderboardEntryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LeaderboardEntryValidationError) ErrorName() string { return "LeaderboardEntryValidationError" }

// Error satisfies the builtin error interface
func (e LeaderboardEntryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLeaderboardEntry.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LeaderboardEntryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LeaderboardEntryValidationError{}

// Validate checks the field values on LeaderboardInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *LeaderboardInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LeaderboardInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LeaderboardInfoMultiError, or nil if none found.
func (m *LeaderboardInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *LeaderboardInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Scope

	if all {
		switch v := interface{}(m.GetRegion()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LeaderboardInfoValidationError{
					field:  "Region",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LeaderboardInfoValidationError{
					field:  "Region",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRegion()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LeaderboardInfoValidationError{
				field:  "Region",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Period

	// no validation rules for PeriodKey

	// no validation rules for CompetitionId

	for idx, item := range m.GetEntries() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, LeaderboardInfoValidationError{
						field:  fmt.Sprintf("Entries[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, LeaderboardInfoValidationError{
						field:  fmt.Sprintf("Entries[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return LeaderboardInfoValidationError{
					field:  fmt.Sprintf("Entries[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetMyEntry()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LeaderboardInfoValidationError{
					field:  "MyEntry",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LeaderboardInfoValidationError{
					field:  "MyEntry",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMyEntry()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LeaderboardInfoValidationError{
				field:  "MyEntry",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for TotalParticipants

	if all {
		switch v := interface{}(m.GetRefreshedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LeaderboardInfoValidationError{
					field:  "RefreshedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LeaderboardInfoValidationError{
					field:  "RefreshedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRefreshedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LeaderboardInfoValidationError{
				field:  "RefreshedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return LeaderboardInfoMultiError(errors)
	}

	return nil
}

// LeaderboardInfoMultiError is an error wrapping multiple validation errors
// returned by LeaderboardInfo.ValidateAll() if the designated constraints
// aren't met.
type LeaderboardInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LeaderboardInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LeaderboardInfoMultiError) AllErrors() []error { return m }

// LeaderboardInfoValidationError is the validation error returned by
// LeaderboardInfo.Validate if the designated constraints aren't met.
type LeaderboardInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LeaderboardInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LeaderboardInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LeaderboardInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LeaderboardInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LeaderboardInfoValidationError) ErrorName() string { return "LeaderboardInfoValidationError" }

// Error satisfies the builtin error interface
func (e LeaderboardInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLeaderboardInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LeaderboardInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LeaderboardInfoValidationError{}

// Validate checks the field values on RegionStanding with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RegionStanding) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegionStanding with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RegionStandingMultiError,
// or nil if none found.
func (m *RegionStanding) ValidateAll() error {
	return m.validate(true)
}

func (m *RegionStanding) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Rank

	if all {
		switch v := interface{}(m.GetRegion()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RegionStandingValidationError{
					field:  "Region",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RegionStandingValidationError{
					field:  "Region",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRegion()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RegionStandingValidationError{
				field:  "Region",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for TotalScore

	// no validation rules for ParticipantCount

	// no validation rules for AverageScore

	if len(errors) > 0 {
		return RegionStandingMultiError(errors)
	}

	return nil
}

// RegionStandingMultiError is an error wrapping multiple validation errors
// returned by RegionStanding.ValidateAll() if the designated constraints
// aren't met.
type RegionStandingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegionStandingMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegionStandingMultiError) AllErrors() []error { return m }

// RegionStandingValidationError is the validation error returned by
// RegionStanding.Validate if the designated constraints aren't met.
type RegionStandingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegionStandingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegionStandingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegionStandingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegionStandingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegionStandingValidationError) ErrorName() string { return "RegionStandingValidationError" }

// Error satisfies the builtin error interface
func (e RegionStandingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegionStanding.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegionStandingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegionStandingValidationError{}
