// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: fitness/v1/types/walk_session.proto

package types

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	enums "github.com/arm-1234/protos/fitness/v1/types/enums"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = enums.ActivityType(0)
)

// Validate checks the field values on WalkSample with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *WalkSample) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WalkSample with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in WalkSampleMultiError, or
// nil if none found.
func (m *WalkSample) ValidateAll() error {
	return m.validate(true)
}

func (m *WalkSample) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Sequence

	// no validation rules for Latitude

	// no validation rules for Longitude

	// no validation rules for AccuracyMeters

	// no validation rules for AltitudeMeters

	// no validation rules for StepsDelta

	// no validation rules for SpeedMps

	if all {
		switch v := interface{}(m.GetRecordedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WalkSampleValidationError{
					field:  "RecordedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WalkSampleValidationError{
					field:  "RecordedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRecordedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WalkSampleValidationError{
				field:  "RecordedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for ActivityType

	// no validation rules for IsMockLocation

	// no validation rules for HeadingDegrees

	if len(errors) > 0 {
		return WalkSampleMultiError(errors)
	}

	return nil
}

// WalkSampleMultiError is an error wrapping multiple validation errors
// returned by WalkSample.ValidateAll() if the designated constraints aren't met.
type WalkSampleMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WalkSampleMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WalkSampleMultiError) AllErrors() []error { return m }

// WalkSampleValidationError is the validation error returned by
// WalkSample.Validate if the designated constraints aren't met.
type WalkSampleValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WalkSampleValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WalkSampleValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WalkSampleValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WalkSampleValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WalkSampleValidationError) ErrorName() string { return "WalkSampleValidationError" }

// Error satisfies the builtin error interface
func (e WalkSampleValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWalkSample.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WalkSampleValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WalkSampleValidationError{}

// Validate checks the field values on WalkSessionInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *WalkSessionInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WalkSessionInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// WalkSessionInfoMultiError, or nil if none found.
func (m *WalkSessionInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *WalkSessionInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SessionId

	// no validation rules for UserId

	// no validation rules for ChallengeId

	// no validation rules for CompetitionId

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetStartedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WalkSessionInfoValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WalkSessionInfoValidationError{
					field:  "StartedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WalkSessionInfoValidationError{
				field:  "StartedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetEndedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WalkSessionInfoValidationError{
					field:  "EndedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WalkSessionInfoValidationError{
					field:  "EndedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEndedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WalkSessionInfoValidationError{
				field:  "EndedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for DurationSeconds

	// no validation rules for CountedSteps

	// no validation rules for CountedDistanceMeters

	// no validation rules for RawSteps

	// no validation rules for RawDistanceMeters

	// no validation rules for AverageSpeedMps

	// no validation rules for MaxSpeedMps

	// no validation rules for SampleCount

	if all {
		switch v := interface{}(m.GetVerdict()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WalkSessionInfoValidationError{
					field:  "Verdict",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WalkSessionInfoValidationError{
					field:  "Verdict",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetVerdict()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WalkSessionInfoValidationError{
				field:  "Verdict",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for PointsAwarded

	if all {
		switch v := interface{}(m.GetDetectedRegion()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WalkSessionInfoValidationError{
					field:  "DetectedRegion",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WalkSessionInfoValidationError{
					field:  "DetectedRegion",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDetectedRegion()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WalkSessionInfoValidationError{
				field:  "DetectedRegion",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetStartPoint()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WalkSessionInfoValidationError{
					field:  "StartPoint",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WalkSessionInfoValidationError{
					field:  "StartPoint",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartPoint()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WalkSessionInfoValidationError{
				field:  "StartPoint",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetEndPoint()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WalkSessionInfoValidationError{
					field:  "EndPoint",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WalkSessionInfoValidationError{
					field:  "EndPoint",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEndPoint()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WalkSessionInfoValidationError{
				field:  "EndPoint",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for DeviceId

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WalkSessionInfoValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WalkSessionInfoValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WalkSessionInfoValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WalkSessionInfoValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WalkSessionInfoValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WalkSessionInfoValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return WalkSessionInfoMultiError(errors)
	}

	return nil
}

// WalkSessionInfoMultiError is an error wrapping multiple validation errors
// returned by WalkSessionInfo.ValidateAll() if the designated constraints
// aren't met.
type WalkSessionInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WalkSessionInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WalkSessionInfoMultiError) AllErrors() []error { return m }

// WalkSessionInfoValidationError is the validation error returned by
// WalkSessionInfo.Validate if the designated constraints aren't met.
type WalkSessionInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WalkSessionInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WalkSessionInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WalkSessionInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WalkSessionInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WalkSessionInfoValidationError) ErrorName() string { return "WalkSessionInfoValidationError" }

// Error satisfies the builtin error interface
func (e WalkSessionInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWalkSessionInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WalkSessionInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WalkSessionInfoValidationError{}
