// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: catalog/v1/catalog.proto

package v1

import (
	context "context"
	request "github.com/arm-1234/protos/catalog/v1/request"
	response "github.com/arm-1234/protos/catalog/v1/response"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Catalog_CreateProduct_FullMethodName            = "/catalog.v1.Catalog/CreateProduct"
	Catalog_BatchCreateProducts_FullMethodName      = "/catalog.v1.Catalog/BatchCreateProducts"
	Catalog_GetProduct_FullMethodName               = "/catalog.v1.Catalog/GetProduct"
	Catalog_UpdateProduct_FullMethodName            = "/catalog.v1.Catalog/UpdateProduct"
	Catalog_DeleteProduct_FullMethodName            = "/catalog.v1.Catalog/DeleteProduct"
	Catalog_SetInventory_FullMethodName             = "/catalog.v1.Catalog/SetInventory"
	Catalog_ListProducts_FullMethodName             = "/catalog.v1.Catalog/ListProducts"
	Catalog_CreateProductImageUpload_FullMethodName = "/catalog.v1.Catalog/CreateProductImageUpload"
)

// CatalogClient is the client API for Catalog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogClient interface {
	CreateProduct(ctx context.Context, in *request.CreateProductRequest, opts ...grpc.CallOption) (*response.CreateProductResponse, error)
	// BatchCreateProducts adds many products at once for the caller's merchant.
	BatchCreateProducts(ctx context.Context, in *request.BatchCreateProductsRequest, opts ...grpc.CallOption) (*response.BatchCreateProductsResponse, error)
	GetProduct(ctx context.Context, in *request.GetProductRequest, opts ...grpc.CallOption) (*response.GetProductResponse, error)
	UpdateProduct(ctx context.Context, in *request.UpdateProductRequest, opts ...grpc.CallOption) (*response.UpdateProductResponse, error)
	DeleteProduct(ctx context.Context, in *request.DeleteProductRequest, opts ...grpc.CallOption) (*response.DeleteProductResponse, error)
	SetInventory(ctx context.Context, in *request.SetInventoryRequest, opts ...grpc.CallOption) (*response.SetInventoryResponse, error)
	// ListProducts returns a merchant's products with filtering + sorting.
	ListProducts(ctx context.Context, in *request.ListProductsRequest, opts ...grpc.CallOption) (*response.ListProductsResponse, error)
	// CreateProductImageUpload returns a presigned URL for direct image upload.
	CreateProductImageUpload(ctx context.Context, in *request.CreateProductImageUploadRequest, opts ...grpc.CallOption) (*response.CreateProductImageUploadResponse, error)
}

type catalogClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogClient(cc grpc.ClientConnInterface) CatalogClient {
	return &catalogClient{cc}
}

func (c *catalogClient) CreateProduct(ctx context.Context, in *request.CreateProductRequest, opts ...grpc.CallOption) (*response.CreateProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.CreateProductResponse)
	err := c.cc.Invoke(ctx, Catalog_CreateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) BatchCreateProducts(ctx context.Context, in *request.BatchCreateProductsRequest, opts ...grpc.CallOption) (*response.BatchCreateProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.BatchCreateProductsResponse)
	err := c.cc.Invoke(ctx, Catalog_BatchCreateProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) GetProduct(ctx context.Context, in *request.GetProductRequest, opts ...grpc.CallOption) (*response.GetProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.GetProductResponse)
	err := c.cc.Invoke(ctx, Catalog_GetProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) UpdateProduct(ctx context.Context, in *request.UpdateProductRequest, opts ...grpc.CallOption) (*response.UpdateProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.UpdateProductResponse)
	err := c.cc.Invoke(ctx, Catalog_UpdateProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) DeleteProduct(ctx context.Context, in *request.DeleteProductRequest, opts ...grpc.CallOption) (*response.DeleteProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.DeleteProductResponse)
	err := c.cc.Invoke(ctx, Catalog_DeleteProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) SetInventory(ctx context.Context, in *request.SetInventoryRequest, opts ...grpc.CallOption) (*response.SetInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.SetInventoryResponse)
	err := c.cc.Invoke(ctx, Catalog_SetInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) ListProducts(ctx context.Context, in *request.ListProductsRequest, opts ...grpc.CallOption) (*response.ListProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.ListProductsResponse)
	err := c.cc.Invoke(ctx, Catalog_ListProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) CreateProductImageUpload(ctx context.Context, in *request.CreateProductImageUploadRequest, opts ...grpc.CallOption) (*response.CreateProductImageUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.CreateProductImageUploadResponse)
	err := c.cc.Invoke(ctx, Catalog_CreateProductImageUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServer is the server API for Catalog service.
// All implementations must embed UnimplementedCatalogServer
// for forward compatibility.
type CatalogServer interface {
	CreateProduct(context.Context, *request.CreateProductRequest) (*response.CreateProductResponse, error)
	// BatchCreateProducts adds many products at once for the caller's merchant.
	BatchCreateProducts(context.Context, *request.BatchCreateProductsRequest) (*response.BatchCreateProductsResponse, error)
	GetProduct(context.Context, *request.GetProductRequest) (*response.GetProductResponse, error)
	UpdateProduct(context.Context, *request.UpdateProductRequest) (*response.UpdateProductResponse, error)
	DeleteProduct(context.Context, *request.DeleteProductRequest) (*response.DeleteProductResponse, error)
	SetInventory(context.Context, *request.SetInventoryRequest) (*response.SetInventoryResponse, error)
	// ListProducts returns a merchant's products with filtering + sorting.
	ListProducts(context.Context, *request.ListProductsRequest) (*response.ListProductsResponse, error)
	// CreateProductImageUpload returns a presigned URL for direct image upload.
	CreateProductImageUpload(context.Context, *request.CreateProductImageUploadRequest) (*response.CreateProductImageUploadResponse, error)
	mustEmbedUnimplementedCatalogServer()
}

// UnimplementedCatalogServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogServer struct{}

func (UnimplementedCatalogServer) CreateProduct(context.Context, *request.CreateProductRequest) (*response.CreateProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProduct not implemented")
}
func (UnimplementedCatalogServer) BatchCreateProducts(context.Context, *request.BatchCreateProductsRequest) (*response.BatchCreateProductsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchCreateProducts not implemented")
}
func (UnimplementedCatalogServer) GetProduct(context.Context, *request.GetProductRequest) (*response.GetProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedCatalogServer) UpdateProduct(context.Context, *request.UpdateProductRequest) (*response.UpdateProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProduct not implemented")
}
func (UnimplementedCatalogServer) DeleteProduct(context.Context, *request.DeleteProductRequest) (*response.DeleteProductResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProduct not implemented")
}
func (UnimplementedCatalogServer) SetInventory(context.Context, *request.SetInventoryRequest) (*response.SetInventoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetInventory not implemented")
}
func (UnimplementedCatalogServer) ListProducts(context.Context, *request.ListProductsRequest) (*response.ListProductsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProducts not implemented")
}
func (UnimplementedCatalogServer) CreateProductImageUpload(context.Context, *request.CreateProductImageUploadRequest) (*response.CreateProductImageUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProductImageUpload not implemented")
}
func (UnimplementedCatalogServer) mustEmbedUnimplementedCatalogServer() {}
func (UnimplementedCatalogServer) testEmbeddedByValue()                 {}

// UnsafeCatalogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogServer will
// result in compilation errors.
type UnsafeCatalogServer interface {
	mustEmbedUnimplementedCatalogServer()
}

func RegisterCatalogServer(s grpc.ServiceRegistrar, srv CatalogServer) {
	// If the following call panics, it indicates UnimplementedCatalogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Catalog_ServiceDesc, srv)
}

func _Catalog_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_CreateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).CreateProduct(ctx, req.(*request.CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_BatchCreateProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.BatchCreateProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).BatchCreateProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_BatchCreateProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).BatchCreateProducts(ctx, req.(*request.BatchCreateProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_GetProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).GetProduct(ctx, req.(*request.GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.UpdateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_UpdateProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).UpdateProduct(ctx, req.(*request.UpdateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.DeleteProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_DeleteProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).DeleteProduct(ctx, req.(*request.DeleteProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_SetInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.SetInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).SetInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_SetInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).SetInventory(ctx, req.(*request.SetInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.ListProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_ListProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).ListProducts(ctx, req.(*request.ListProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_CreateProductImageUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.CreateProductImageUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).CreateProductImageUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_CreateProductImageUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).CreateProductImageUpload(ctx, req.(*request.CreateProductImageUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Catalog_ServiceDesc is the grpc.ServiceDesc for Catalog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Catalog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catalog.v1.Catalog",
	HandlerType: (*CatalogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProduct",
			Handler:    _Catalog_CreateProduct_Handler,
		},
		{
			MethodName: "BatchCreateProducts",
			Handler:    _Catalog_BatchCreateProducts_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _Catalog_GetProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _Catalog_UpdateProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _Catalog_DeleteProduct_Handler,
		},
		{
			MethodName: "SetInventory",
			Handler:    _Catalog_SetInventory_Handler,
		},
		{
			MethodName: "ListProducts",
			Handler:    _Catalog_ListProducts_Handler,
		},
		{
			MethodName: "CreateProductImageUpload",
			Handler:    _Catalog_CreateProductImageUpload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catalog/v1/catalog.proto",
}
