// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: wishes/v1/request/wishes_request.proto

package request

import (
	types "github.com/arm-1234/protos/wishes/v1/types"
	enums "github.com/arm-1234/protos/wishes/v1/types/enums"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      string                 `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	ExpiryDays    int32                  `protobuf:"varint,3,opt,name=expiry_days,json=expiryDays,proto3" json:"expiry_days,omitempty"`
	FromLabel     string                 `protobuf:"bytes,4,opt,name=from_label,json=fromLabel,proto3" json:"from_label,omitempty"`
	ToEmail       string                 `protobuf:"bytes,5,opt,name=to_email,json=toEmail,proto3" json:"to_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWishRequest) Reset() {
	*x = CreateWishRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWishRequest) ProtoMessage() {}

func (x *CreateWishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWishRequest.ProtoReflect.Descriptor instead.
func (*CreateWishRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWishRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *CreateWishRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateWishRequest) GetExpiryDays() int32 {
	if x != nil {
		return x.ExpiryDays
	}
	return 0
}

func (x *CreateWishRequest) GetFromLabel() string {
	if x != nil {
		return x.FromLabel
	}
	return ""
}

func (x *CreateWishRequest) GetToEmail() string {
	if x != nil {
		return x.ToEmail
	}
	return ""
}

type ListMyWishesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []enums.WishStatus     `protobuf:"varint,1,rep,packed,name=statuses,proto3,enum=wishes.v1.types.enums.WishStatus" json:"statuses,omitempty"`
	Template      string                 `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	SortBy        enums.WishSortBy       `protobuf:"varint,3,opt,name=sort_by,json=sortBy,proto3,enum=wishes.v1.types.enums.WishSortBy" json:"sort_by,omitempty"`
	PageNumber    int64                  `protobuf:"varint,4,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize      int64                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyWishesRequest) Reset() {
	*x = ListMyWishesRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyWishesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyWishesRequest) ProtoMessage() {}

func (x *ListMyWishesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyWishesRequest.ProtoReflect.Descriptor instead.
func (*ListMyWishesRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{1}
}

func (x *ListMyWishesRequest) GetStatuses() []enums.WishStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *ListMyWishesRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *ListMyWishesRequest) GetSortBy() enums.WishSortBy {
	if x != nil {
		return x.SortBy
	}
	return enums.WishSortBy(0)
}

func (x *ListMyWishesRequest) GetPageNumber() int64 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ListMyWishesRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetWishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WishId        string                 `protobuf:"bytes,1,opt,name=wish_id,json=wishId,proto3" json:"wish_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWishRequest) Reset() {
	*x = GetWishRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWishRequest) ProtoMessage() {}

func (x *GetWishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWishRequest.ProtoReflect.Descriptor instead.
func (*GetWishRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{2}
}

func (x *GetWishRequest) GetWishId() string {
	if x != nil {
		return x.WishId
	}
	return ""
}

type UpdateWishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WishId        string                 `protobuf:"bytes,1,opt,name=wish_id,json=wishId,proto3" json:"wish_id,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWishRequest) Reset() {
	*x = UpdateWishRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWishRequest) ProtoMessage() {}

func (x *UpdateWishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWishRequest.ProtoReflect.Descriptor instead.
func (*UpdateWishRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateWishRequest) GetWishId() string {
	if x != nil {
		return x.WishId
	}
	return ""
}

func (x *UpdateWishRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

type ExtendWishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WishId        string                 `protobuf:"bytes,1,opt,name=wish_id,json=wishId,proto3" json:"wish_id,omitempty"`
	ExpiryDays    int32                  `protobuf:"varint,2,opt,name=expiry_days,json=expiryDays,proto3" json:"expiry_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendWishRequest) Reset() {
	*x = ExtendWishRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendWishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendWishRequest) ProtoMessage() {}

func (x *ExtendWishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendWishRequest.ProtoReflect.Descriptor instead.
func (*ExtendWishRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{4}
}

func (x *ExtendWishRequest) GetWishId() string {
	if x != nil {
		return x.WishId
	}
	return ""
}

func (x *ExtendWishRequest) GetExpiryDays() int32 {
	if x != nil {
		return x.ExpiryDays
	}
	return 0
}

type RevokeWishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WishId        string                 `protobuf:"bytes,1,opt,name=wish_id,json=wishId,proto3" json:"wish_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeWishRequest) Reset() {
	*x = RevokeWishRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeWishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeWishRequest) ProtoMessage() {}

func (x *RevokeWishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeWishRequest.ProtoReflect.Descriptor instead.
func (*RevokeWishRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeWishRequest) GetWishId() string {
	if x != nil {
		return x.WishId
	}
	return ""
}

type SendWishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WishId        string                 `protobuf:"bytes,1,opt,name=wish_id,json=wishId,proto3" json:"wish_id,omitempty"`
	ToEmail       string                 `protobuf:"bytes,2,opt,name=to_email,json=toEmail,proto3" json:"to_email,omitempty"`
	FromLabel     string                 `protobuf:"bytes,3,opt,name=from_label,json=fromLabel,proto3" json:"from_label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendWishRequest) Reset() {
	*x = SendWishRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendWishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendWishRequest) ProtoMessage() {}

func (x *SendWishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendWishRequest.ProtoReflect.Descriptor instead.
func (*SendWishRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{6}
}

func (x *SendWishRequest) GetWishId() string {
	if x != nil {
		return x.WishId
	}
	return ""
}

func (x *SendWishRequest) GetToEmail() string {
	if x != nil {
		return x.ToEmail
	}
	return ""
}

func (x *SendWishRequest) GetFromLabel() string {
	if x != nil {
		return x.FromLabel
	}
	return ""
}

type ListWishResponsesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WishId        string                 `protobuf:"bytes,1,opt,name=wish_id,json=wishId,proto3" json:"wish_id,omitempty"`
	PageNumber    int64                  `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWishResponsesRequest) Reset() {
	*x = ListWishResponsesRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWishResponsesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWishResponsesRequest) ProtoMessage() {}

func (x *ListWishResponsesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWishResponsesRequest.ProtoReflect.Descriptor instead.
func (*ListWishResponsesRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{7}
}

func (x *ListWishResponsesRequest) GetWishId() string {
	if x != nil {
		return x.WishId
	}
	return ""
}

func (x *ListWishResponsesRequest) GetPageNumber() int64 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ListWishResponsesRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type MarkResponsesSeenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WishId        string                 `protobuf:"bytes,1,opt,name=wish_id,json=wishId,proto3" json:"wish_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkResponsesSeenRequest) Reset() {
	*x = MarkResponsesSeenRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkResponsesSeenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkResponsesSeenRequest) ProtoMessage() {}

func (x *MarkResponsesSeenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkResponsesSeenRequest.ProtoReflect.Descriptor instead.
func (*MarkResponsesSeenRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{8}
}

func (x *MarkResponsesSeenRequest) GetWishId() string {
	if x != nil {
		return x.WishId
	}
	return ""
}

type GetWishStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWishStatsRequest) Reset() {
	*x = GetWishStatsRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWishStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWishStatsRequest) ProtoMessage() {}

func (x *GetWishStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWishStatsRequest.ProtoReflect.Descriptor instead.
func (*GetWishStatsRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{9}
}

type ListTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{10}
}

type SaveDraftRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WishId        string                 `protobuf:"bytes,1,opt,name=wish_id,json=wishId,proto3" json:"wish_id,omitempty"`
	Template      string                 `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	ExpiryDays    int32                  `protobuf:"varint,4,opt,name=expiry_days,json=expiryDays,proto3" json:"expiry_days,omitempty"`
	FromLabel     string                 `protobuf:"bytes,5,opt,name=from_label,json=fromLabel,proto3" json:"from_label,omitempty"`
	ToEmail       string                 `protobuf:"bytes,6,opt,name=to_email,json=toEmail,proto3" json:"to_email,omitempty"`
	Step          string                 `protobuf:"bytes,7,opt,name=step,proto3" json:"step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveDraftRequest) Reset() {
	*x = SaveDraftRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveDraftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveDraftRequest) ProtoMessage() {}

func (x *SaveDraftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveDraftRequest.ProtoReflect.Descriptor instead.
func (*SaveDraftRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{11}
}

func (x *SaveDraftRequest) GetWishId() string {
	if x != nil {
		return x.WishId
	}
	return ""
}

func (x *SaveDraftRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *SaveDraftRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *SaveDraftRequest) GetExpiryDays() int32 {
	if x != nil {
		return x.ExpiryDays
	}
	return 0
}

func (x *SaveDraftRequest) GetFromLabel() string {
	if x != nil {
		return x.FromLabel
	}
	return ""
}

func (x *SaveDraftRequest) GetToEmail() string {
	if x != nil {
		return x.ToEmail
	}
	return ""
}

func (x *SaveDraftRequest) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

type PublishWishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WishId        string                 `protobuf:"bytes,1,opt,name=wish_id,json=wishId,proto3" json:"wish_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishWishRequest) Reset() {
	*x = PublishWishRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishWishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishWishRequest) ProtoMessage() {}

func (x *PublishWishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishWishRequest.ProtoReflect.Descriptor instead.
func (*PublishWishRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{12}
}

func (x *PublishWishRequest) GetWishId() string {
	if x != nil {
		return x.WishId
	}
	return ""
}

type DeleteWishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WishId        string                 `protobuf:"bytes,1,opt,name=wish_id,json=wishId,proto3" json:"wish_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWishRequest) Reset() {
	*x = DeleteWishRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWishRequest) ProtoMessage() {}

func (x *DeleteWishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWishRequest.ProtoReflect.Descriptor instead.
func (*DeleteWishRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteWishRequest) GetWishId() string {
	if x != nil {
		return x.WishId
	}
	return ""
}

type UploadWishPhotoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WishId        string                 `protobuf:"bytes,1,opt,name=wish_id,json=wishId,proto3" json:"wish_id,omitempty"`
	Idx           int32                  `protobuf:"varint,2,opt,name=idx,proto3" json:"idx,omitempty"`
	DataUrl       string                 `protobuf:"bytes,3,opt,name=data_url,json=dataUrl,proto3" json:"data_url,omitempty"`
	Width         int32                  `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadWishPhotoRequest) Reset() {
	*x = UploadWishPhotoRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadWishPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadWishPhotoRequest) ProtoMessage() {}

func (x *UploadWishPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadWishPhotoRequest.ProtoReflect.Descriptor instead.
func (*UploadWishPhotoRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{14}
}

func (x *UploadWishPhotoRequest) GetWishId() string {
	if x != nil {
		return x.WishId
	}
	return ""
}

func (x *UploadWishPhotoRequest) GetIdx() int32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *UploadWishPhotoRequest) GetDataUrl() string {
	if x != nil {
		return x.DataUrl
	}
	return ""
}

func (x *UploadWishPhotoRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *UploadWishPhotoRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type DeleteWishPhotoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WishId        string                 `protobuf:"bytes,1,opt,name=wish_id,json=wishId,proto3" json:"wish_id,omitempty"`
	Idx           int32                  `protobuf:"varint,2,opt,name=idx,proto3" json:"idx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWishPhotoRequest) Reset() {
	*x = DeleteWishPhotoRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWishPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWishPhotoRequest) ProtoMessage() {}

func (x *DeleteWishPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWishPhotoRequest.ProtoReflect.Descriptor instead.
func (*DeleteWishPhotoRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteWishPhotoRequest) GetWishId() string {
	if x != nil {
		return x.WishId
	}
	return ""
}

func (x *DeleteWishPhotoRequest) GetIdx() int32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

type SubmitResponseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Kind          enums.ResponseKind     `protobuf:"varint,2,opt,name=kind,proto3,enum=wishes.v1.types.enums.ResponseKind" json:"kind,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponseRequest) Reset() {
	*x = SubmitResponseRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponseRequest) ProtoMessage() {}

func (x *SubmitResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponseRequest.ProtoReflect.Descriptor instead.
func (*SubmitResponseRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{16}
}

func (x *SubmitResponseRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *SubmitResponseRequest) GetKind() enums.ResponseKind {
	if x != nil {
		return x.Kind
	}
	return enums.ResponseKind(0)
}

func (x *SubmitResponseRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SubmitResponseRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReportCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        string                 `protobuf:"bytes,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Reporter      string                 `protobuf:"bytes,3,opt,name=reporter,proto3" json:"reporter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportCardRequest) Reset() {
	*x = ReportCardRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportCardRequest) ProtoMessage() {}

func (x *ReportCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportCardRequest.ProtoReflect.Descriptor instead.
func (*ReportCardRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{17}
}

func (x *ReportCardRequest) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *ReportCardRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ReportCardRequest) GetReporter() string {
	if x != nil {
		return x.Reporter
	}
	return ""
}

type GetTemplateSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateSchemaRequest) Reset() {
	*x = GetTemplateSchemaRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateSchemaRequest) ProtoMessage() {}

func (x *GetTemplateSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetTemplateSchemaRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{18}
}

type GetPricingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPricingRequest) Reset() {
	*x = GetPricingRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPricingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPricingRequest) ProtoMessage() {}

func (x *GetPricingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPricingRequest.ProtoReflect.Descriptor instead.
func (*GetPricingRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{19}
}

type UpdatePricingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AmountMinor   int64                  `protobuf:"varint,1,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Note          string                 `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	MrpMinor      int64                  `protobuf:"varint,4,opt,name=mrp_minor,json=mrpMinor,proto3" json:"mrp_minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePricingRequest) Reset() {
	*x = UpdatePricingRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePricingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePricingRequest) ProtoMessage() {}

func (x *UpdatePricingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePricingRequest.ProtoReflect.Descriptor instead.
func (*UpdatePricingRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{20}
}

func (x *UpdatePricingRequest) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *UpdatePricingRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdatePricingRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *UpdatePricingRequest) GetMrpMinor() int64 {
	if x != nil {
		return x.MrpMinor
	}
	return 0
}

type ListPriceHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPriceHistoryRequest) Reset() {
	*x = ListPriceHistoryRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPriceHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPriceHistoryRequest) ProtoMessage() {}

func (x *ListPriceHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPriceHistoryRequest.ProtoReflect.Descriptor instead.
func (*ListPriceHistoryRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{21}
}

func (x *ListPriceHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WishId        string                 `protobuf:"bytes,1,opt,name=wish_id,json=wishId,proto3" json:"wish_id,omitempty"`
	CouponCode    string                 `protobuf:"bytes,2,opt,name=coupon_code,json=couponCode,proto3" json:"coupon_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{22}
}

func (x *CreateOrderRequest) GetWishId() string {
	if x != nil {
		return x.WishId
	}
	return ""
}

func (x *CreateOrderRequest) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{23}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type VerifyOrderPaymentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrderId          string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	GatewayPaymentId string                 `protobuf:"bytes,2,opt,name=gateway_payment_id,json=gatewayPaymentId,proto3" json:"gateway_payment_id,omitempty"`
	Signature        string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VerifyOrderPaymentRequest) Reset() {
	*x = VerifyOrderPaymentRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOrderPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOrderPaymentRequest) ProtoMessage() {}

func (x *VerifyOrderPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOrderPaymentRequest.ProtoReflect.Descriptor instead.
func (*VerifyOrderPaymentRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{24}
}

func (x *VerifyOrderPaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *VerifyOrderPaymentRequest) GetGatewayPaymentId() string {
	if x != nil {
		return x.GatewayPaymentId
	}
	return ""
}

func (x *VerifyOrderPaymentRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type CreateCouponRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	PercentOff    int32                  `protobuf:"varint,2,opt,name=percent_off,json=percentOff,proto3" json:"percent_off,omitempty"`
	ValidDays     int32                  `protobuf:"varint,3,opt,name=valid_days,json=validDays,proto3" json:"valid_days,omitempty"`
	Note          string                 `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCouponRequest) Reset() {
	*x = CreateCouponRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCouponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCouponRequest) ProtoMessage() {}

func (x *CreateCouponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCouponRequest.ProtoReflect.Descriptor instead.
func (*CreateCouponRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{25}
}

func (x *CreateCouponRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateCouponRequest) GetPercentOff() int32 {
	if x != nil {
		return x.PercentOff
	}
	return 0
}

func (x *CreateCouponRequest) GetValidDays() int32 {
	if x != nil {
		return x.ValidDays
	}
	return 0
}

func (x *CreateCouponRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type ListCouponsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCouponsRequest) Reset() {
	*x = ListCouponsRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCouponsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCouponsRequest) ProtoMessage() {}

func (x *ListCouponsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCouponsRequest.ProtoReflect.Descriptor instead.
func (*ListCouponsRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{26}
}

type SetCouponStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        enums.CouponStatus     `protobuf:"varint,2,opt,name=status,proto3,enum=wishes.v1.types.enums.CouponStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCouponStatusRequest) Reset() {
	*x = SetCouponStatusRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCouponStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCouponStatusRequest) ProtoMessage() {}

func (x *SetCouponStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCouponStatusRequest.ProtoReflect.Descriptor instead.
func (*SetCouponStatusRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{27}
}

func (x *SetCouponStatusRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SetCouponStatusRequest) GetStatus() enums.CouponStatus {
	if x != nil {
		return x.Status
	}
	return enums.CouponStatus(0)
}

type CheckCouponRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCouponRequest) Reset() {
	*x = CheckCouponRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCouponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCouponRequest) ProtoMessage() {}

func (x *CheckCouponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCouponRequest.ProtoReflect.Descriptor instead.
func (*CheckCouponRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{28}
}

func (x *CheckCouponRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ListTemplateSoundtracksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplateSoundtracksRequest) Reset() {
	*x = ListTemplateSoundtracksRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplateSoundtracksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplateSoundtracksRequest) ProtoMessage() {}

func (x *ListTemplateSoundtracksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplateSoundtracksRequest.ProtoReflect.Descriptor instead.
func (*ListTemplateSoundtracksRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{29}
}

type UpdateTemplateSoundtracksRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Template      string                  `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	Songs         []*types.SoundtrackSong `protobuf:"bytes,2,rep,name=songs,proto3" json:"songs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTemplateSoundtracksRequest) Reset() {
	*x = UpdateTemplateSoundtracksRequest{}
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTemplateSoundtracksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTemplateSoundtracksRequest) ProtoMessage() {}

func (x *UpdateTemplateSoundtracksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wishes_v1_request_wishes_request_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTemplateSoundtracksRequest.ProtoReflect.Descriptor instead.
func (*UpdateTemplateSoundtracksRequest) Descriptor() ([]byte, []int) {
	return file_wishes_v1_request_wishes_request_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateTemplateSoundtracksRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *UpdateTemplateSoundtracksRequest) GetSongs() []*types.SoundtrackSong {
	if x != nil {
		return x.Songs
	}
	return nil
}

var File_wishes_v1_request_wishes_request_proto protoreflect.FileDescriptor

const file_wishes_v1_request_wishes_request_proto_rawDesc = "" +
	"\n" +
	"&wishes/v1/request/wishes_request.proto\x12\x11wishes.v1.request\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x17validate/validate.proto\x1a'wishes/v1/types/enums/wish_status.proto\x1a(wishes/v1/types/enums/wish_sort_by.proto\x1a)wishes/v1/types/enums/response_kind.proto\x1a)wishes/v1/types/enums/coupon_status.proto\x1a\x1ewishes/v1/types/template.proto\"\x83\x02\n" +
	"\x11CreateWishRequest\x12<\n" +
	"\btemplate\x18\x01 \x01(\tB \xe2A\x01\x02\xfaB\x19r\x17\x10\x02\x18@2\x11^[a-z][a-z0-9-]*$R\btemplate\x12/\n" +
	"\x06config\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06config\x12,\n" +
	"\vexpiry_days\x18\x03 \x01(\x05B\v\xfaB\b\x1a\x06\x18\x0e(\x01@\x01R\n" +
	"expiryDays\x12*\n" +
	"\n" +
	"from_label\x18\x04 \x01(\tB\v\xfaB\br\x06\x18\x80\x01\xd0\x01\x01R\tfromLabel\x12%\n" +
	"\bto_email\x18\x05 \x01(\tB\n" +
	"\xfaB\ar\x05\xd0\x01\x01`\x01R\atoEmail\"\x81\x02\n" +
	"\x13ListMyWishesRequest\x12=\n" +
	"\bstatuses\x18\x01 \x03(\x0e2!.wishes.v1.types.enums.WishStatusR\bstatuses\x12&\n" +
	"\btemplate\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x18@\xd0\x01\x01R\btemplate\x12:\n" +
	"\asort_by\x18\x03 \x01(\x0e2!.wishes.v1.types.enums.WishSortByR\x06sortBy\x12\x1f\n" +
	"\vpage_number\x18\x04 \x01(\x03R\n" +
	"pageNumber\x12&\n" +
	"\tpage_size\x18\x05 \x01(\x03B\t\xfaB\x06\"\x04\x18d@\x01R\bpageSize\"6\n" +
	"\x0eGetWishRequest\x12$\n" +
	"\awish_id\x18\x01 \x01(\tB\v\xe2A\x01\x02\xfaB\x04r\x02\x10\x01R\x06wishId\"j\n" +
	"\x11UpdateWishRequest\x12$\n" +
	"\awish_id\x18\x01 \x01(\tB\v\xe2A\x01\x02\xfaB\x04r\x02\x10\x01R\x06wishId\x12/\n" +
	"\x06config\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06config\"i\n" +
	"\x11ExtendWishRequest\x12$\n" +
	"\awish_id\x18\x01 \x01(\tB\v\xe2A\x01\x02\xfaB\x04r\x02\x10\x01R\x06wishId\x12.\n" +
	"\vexpiry_days\x18\x02 \x01(\x05B\r\xe2A\x01\x02\xfaB\x06\x1a\x04\x18\x0e(\x01R\n" +
	"expiryDays\"9\n" +
	"\x11RevokeWishRequest\x12$\n" +
	"\awish_id\x18\x01 \x01(\tB\v\xe2A\x01\x02\xfaB\x04r\x02\x10\x01R\x06wishId\"\x8b\x01\n" +
	"\x0fSendWishRequest\x12$\n" +
	"\awish_id\x18\x01 \x01(\tB\v\xe2A\x01\x02\xfaB\x04r\x02\x10\x01R\x06wishId\x12&\n" +
	"\bto_email\x18\x02 \x01(\tB\v\xe2A\x01\x02\xfaB\x04r\x02`\x01R\atoEmail\x12*\n" +
	"\n" +
	"from_label\x18\x03 \x01(\tB\v\xfaB\br\x06\x18\x80\x01\xd0\x01\x01R\tfromLabel\"\x89\x01\n" +
	"\x18ListWishResponsesRequest\x12$\n" +
	"\awish_id\x18\x01 \x01(\tB\v\xe2A\x01\x02\xfaB\x04r\x02\x10\x01R\x06wishId\x12\x1f\n" +
	"\vpage_number\x18\x02 \x01(\x03R\n" +
	"pageNumber\x12&\n" +
	"\tpage_size\x18\x03 \x01(\x03B\t\xfaB\x06\"\x04\x18d@\x01R\bpageSize\"@\n" +
	"\x18MarkResponsesSeenRequest\x12$\n" +
	"\awish_id\x18\x01 \x01(\tB\v\xe2A\x01\x02\xfaB\x04r\x02\x10\x01R\x06wishId\"\x15\n" +
	"\x13GetWishStatsRequest\"\x16\n" +
	"\x14ListTemplatesRequest\"\xc7\x02\n" +
	"\x10SaveDraftRequest\x12#\n" +
	"\awish_id\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x18@\xd0\x01\x01R\x06wishId\x12<\n" +
	"\btemplate\x18\x02 \x01(\tB \xe2A\x01\x02\xfaB\x19r\x17\x10\x02\x18@2\x11^[a-z][a-z0-9-]*$R\btemplate\x12/\n" +
	"\x06config\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06config\x12,\n" +
	"\vexpiry_days\x18\x04 \x01(\x05B\v\xfaB\b\x1a\x06\x18\x0e(\x01@\x01R\n" +
	"expiryDays\x12*\n" +
	"\n" +
	"from_label\x18\x05 \x01(\tB\v\xfaB\br\x06\x18\x80\x01\xd0\x01\x01R\tfromLabel\x12%\n" +
	"\bto_email\x18\x06 \x01(\tB\n" +
	"\xfaB\ar\x05\xd0\x01\x01`\x01R\atoEmail\x12\x1e\n" +
	"\x04step\x18\a \x01(\tB\n" +
	"\xfaB\ar\x05\x18@\xd0\x01\x01R\x04step\":\n" +
	"\x12PublishWishRequest\x12$\n" +
	"\awish_id\x18\x01 \x01(\tB\v\xe2A\x01\x02\xfaB\x04r\x02\x10\x01R\x06wishId\"9\n" +
	"\x11DeleteWishRequest\x12$\n" +
	"\awish_id\x18\x01 \x01(\tB\v\xe2A\x01\x02\xfaB\x04r\x02\x10\x01R\x06wishId\"\xb5\x01\n" +
	"\x16UploadWishPhotoRequest\x12$\n" +
	"\awish_id\x18\x01 \x01(\tB\v\xe2A\x01\x02\xfaB\x04r\x02\x10\x01R\x06wishId\x12\x1b\n" +
	"\x03idx\x18\x02 \x01(\x05B\t\xfaB\x06\x1a\x04\x18\x02(\x00R\x03idx\x12*\n" +
	"\bdata_url\x18\x03 \x01(\tB\x0f\xe2A\x01\x02\xfaB\br\x06\x10 \x18\xe0\xdc*R\adataUrl\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x05R\x06height\"[\n" +
	"\x16DeleteWishPhotoRequest\x12$\n" +
	"\awish_id\x18\x01 \x01(\tB\v\xe2A\x01\x02\xfaB\x04r\x02\x10\x01R\x06wishId\x12\x1b\n" +
	"\x03idx\x18\x02 \x01(\x05B\t\xfaB\x06\x1a\x04\x18\x02(\x00R\x03idx\"\xc7\x01\n" +
	"\x15SubmitResponseRequest\x12&\n" +
	"\acard_id\x18\x01 \x01(\tB\r\xe2A\x01\x02\xfaB\x06r\x04\x10\x06\x18@R\x06cardId\x12=\n" +
	"\x04kind\x18\x02 \x01(\x0e2#.wishes.v1.types.enums.ResponseKindB\x04\xe2A\x01\x02R\x04kind\x12 \n" +
	"\x05value\x18\x03 \x01(\tB\n" +
	"\xfaB\ar\x05\x18@\xd0\x01\x01R\x05value\x12%\n" +
	"\amessage\x18\x04 \x01(\tB\v\xfaB\br\x06\x18\x90\x03\xd0\x01\x01R\amessage\"\x89\x01\n" +
	"\x11ReportCardRequest\x12&\n" +
	"\acard_id\x18\x01 \x01(\tB\r\xe2A\x01\x02\xfaB\x06r\x04\x10\x06\x18@R\x06cardId\x12#\n" +
	"\x06reason\x18\x02 \x01(\tB\v\xfaB\br\x06\x18\xe8\a\xd0\x01\x01R\x06reason\x12'\n" +
	"\breporter\x18\x03 \x01(\tB\v\xfaB\br\x06\x18\xc0\x02\xd0\x01\x01R\breporter\"\x1a\n" +
	"\x18GetTemplateSchemaRequest\"\x13\n" +
	"\x11GetPricingRequest\"\xc0\x01\n" +
	"\x14UpdatePricingRequest\x123\n" +
	"\famount_minor\x18\x01 \x01(\x03B\x10\xe2A\x01\x02\xfaB\t\"\a\x18\x80\xad\xe2\x04(\x00R\vamountMinor\x12'\n" +
	"\bcurrency\x18\x02 \x01(\tB\v\xfaB\br\x06\x98\x01\x03\xd0\x01\x01R\bcurrency\x12\x1f\n" +
	"\x04note\x18\x03 \x01(\tB\v\xfaB\br\x06\x18\xc8\x01\xd0\x01\x01R\x04note\x12)\n" +
	"\tmrp_minor\x18\x04 \x01(\x03B\f\xfaB\t\"\a\x18\x80\xad\xe2\x04(\x00R\bmrpMinor\":\n" +
	"\x17ListPriceHistoryRequest\x12\x1f\n" +
	"\x05limit\x18\x01 \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\x00R\x05limit\"|\n" +
	"\x12CreateOrderRequest\x12$\n" +
	"\awish_id\x18\x01 \x01(\tB\v\xe2A\x01\x02\xfaB\x04r\x02\x10\x01R\x06wishId\x12@\n" +
	"\vcoupon_code\x18\x02 \x01(\tB\x1f\xfaB\x1cr\x1a2\x15^[A-Za-z0-9_-]{3,32}$\xd0\x01\x01R\n" +
	"couponCode\"9\n" +
	"\x0fGetOrderRequest\x12&\n" +
	"\border_id\x18\x01 \x01(\tB\v\xe2A\x01\x02\xfaB\x04r\x02\x10\x01R\aorderId\"\xae\x01\n" +
	"\x19VerifyOrderPaymentRequest\x12&\n" +
	"\border_id\x18\x01 \x01(\tB\v\xe2A\x01\x02\xfaB\x04r\x02\x10\x01R\aorderId\x12;\n" +
	"\x12gateway_payment_id\x18\x02 \x01(\tB\r\xe2A\x01\x02\xfaB\x06r\x04\x10\x01\x18@R\x10gatewayPaymentId\x12,\n" +
	"\tsignature\x18\x03 \x01(\tB\x0e\xe2A\x01\x02\xfaB\ar\x05\x10\x01\x18\x80\x01R\tsignature\"\xcb\x01\n" +
	"\x13CreateCouponRequest\x124\n" +
	"\x04code\x18\x01 \x01(\tB \xe2A\x01\x02\xfaB\x19r\x172\x15^[A-Za-z0-9_-]{3,32}$R\x04code\x12.\n" +
	"\vpercent_off\x18\x02 \x01(\x05B\r\xe2A\x01\x02\xfaB\x06\x1a\x04\x18d(\x01R\n" +
	"percentOff\x12-\n" +
	"\n" +
	"valid_days\x18\x03 \x01(\x05B\x0e\xe2A\x01\x02\xfaB\a\x1a\x05\x18\xed\x02(\x01R\tvalidDays\x12\x1f\n" +
	"\x04note\x18\x04 \x01(\tB\v\xfaB\br\x06\x18\xc8\x01\xd0\x01\x01R\x04note\"\x14\n" +
	"\x12ListCouponsRequest\"\x9b\x01\n" +
	"\x16SetCouponStatusRequest\x124\n" +
	"\x04code\x18\x01 \x01(\tB \xe2A\x01\x02\xfaB\x19r\x172\x15^[A-Za-z0-9_-]{3,32}$R\x04code\x12K\n" +
	"\x06status\x18\x02 \x01(\x0e2#.wishes.v1.types.enums.CouponStatusB\x0e\xe2A\x01\x02\xfaB\a\x82\x01\x04\x18\x01\x18\x02R\x06status\"J\n" +
	"\x12CheckCouponRequest\x124\n" +
	"\x04code\x18\x01 \x01(\tB \xe2A\x01\x02\xfaB\x19r\x172\x15^[A-Za-z0-9_-]{3,32}$R\x04code\" \n" +
	"\x1eListTemplateSoundtracksRequest\"\xa8\x01\n" +
	" UpdateTemplateSoundtracksRequest\x12<\n" +
	"\btemplate\x18\x01 \x01(\tB \xe2A\x01\x02\xfaB\x19r\x17\x10\x02\x18@2\x11^[a-z][a-z0-9-]*$R\btemplate\x12F\n" +
	"\x05songs\x18\x02 \x03(\v2\x1f.wishes.v1.types.SoundtrackSongB\x0f\xfaB\f\x92\x01\t\x10\x14\"\x05\x8a\x01\x02\x10\x01R\x05songsB6Z4github.com/arm-1234/protos/wishes/v1/request;requestb\x06proto3"

var (
	file_wishes_v1_request_wishes_request_proto_rawDescOnce sync.Once
	file_wishes_v1_request_wishes_request_proto_rawDescData []byte
)

func file_wishes_v1_request_wishes_request_proto_rawDescGZIP() []byte {
	file_wishes_v1_request_wishes_request_proto_rawDescOnce.Do(func() {
		file_wishes_v1_request_wishes_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wishes_v1_request_wishes_request_proto_rawDesc), len(file_wishes_v1_request_wishes_request_proto_rawDesc)))
	})
	return file_wishes_v1_request_wishes_request_proto_rawDescData
}

var file_wishes_v1_request_wishes_request_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_wishes_v1_request_wishes_request_proto_goTypes = []any{
	(*CreateWishRequest)(nil),                // 0: wishes.v1.request.CreateWishRequest
	(*ListMyWishesRequest)(nil),              // 1: wishes.v1.request.ListMyWishesRequest
	(*GetWishRequest)(nil),                   // 2: wishes.v1.request.GetWishRequest
	(*UpdateWishRequest)(nil),                // 3: wishes.v1.request.UpdateWishRequest
	(*ExtendWishRequest)(nil),                // 4: wishes.v1.request.ExtendWishRequest
	(*RevokeWishRequest)(nil),                // 5: wishes.v1.request.RevokeWishRequest
	(*SendWishRequest)(nil),                  // 6: wishes.v1.request.SendWishRequest
	(*ListWishResponsesRequest)(nil),         // 7: wishes.v1.request.ListWishResponsesRequest
	(*MarkResponsesSeenRequest)(nil),         // 8: wishes.v1.request.MarkResponsesSeenRequest
	(*GetWishStatsRequest)(nil),              // 9: wishes.v1.request.GetWishStatsRequest
	(*ListTemplatesRequest)(nil),             // 10: wishes.v1.request.ListTemplatesRequest
	(*SaveDraftRequest)(nil),                 // 11: wishes.v1.request.SaveDraftRequest
	(*PublishWishRequest)(nil),               // 12: wishes.v1.request.PublishWishRequest
	(*DeleteWishRequest)(nil),                // 13: wishes.v1.request.DeleteWishRequest
	(*UploadWishPhotoRequest)(nil),           // 14: wishes.v1.request.UploadWishPhotoRequest
	(*DeleteWishPhotoRequest)(nil),           // 15: wishes.v1.request.DeleteWishPhotoRequest
	(*SubmitResponseRequest)(nil),            // 16: wishes.v1.request.SubmitResponseRequest
	(*ReportCardRequest)(nil),                // 17: wishes.v1.request.ReportCardRequest
	(*GetTemplateSchemaRequest)(nil),         // 18: wishes.v1.request.GetTemplateSchemaRequest
	(*GetPricingRequest)(nil),                // 19: wishes.v1.request.GetPricingRequest
	(*UpdatePricingRequest)(nil),             // 20: wishes.v1.request.UpdatePricingRequest
	(*ListPriceHistoryRequest)(nil),          // 21: wishes.v1.request.ListPriceHistoryRequest
	(*CreateOrderRequest)(nil),               // 22: wishes.v1.request.CreateOrderRequest
	(*GetOrderRequest)(nil),                  // 23: wishes.v1.request.GetOrderRequest
	(*VerifyOrderPaymentRequest)(nil),        // 24: wishes.v1.request.VerifyOrderPaymentRequest
	(*CreateCouponRequest)(nil),              // 25: wishes.v1.request.CreateCouponRequest
	(*ListCouponsRequest)(nil),               // 26: wishes.v1.request.ListCouponsRequest
	(*SetCouponStatusRequest)(nil),           // 27: wishes.v1.request.SetCouponStatusRequest
	(*CheckCouponRequest)(nil),               // 28: wishes.v1.request.CheckCouponRequest
	(*ListTemplateSoundtracksRequest)(nil),   // 29: wishes.v1.request.ListTemplateSoundtracksRequest
	(*UpdateTemplateSoundtracksRequest)(nil), // 30: wishes.v1.request.UpdateTemplateSoundtracksRequest
	(*structpb.Struct)(nil),                  // 31: google.protobuf.Struct
	(enums.WishStatus)(0),                    // 32: wishes.v1.types.enums.WishStatus
	(enums.WishSortBy)(0),                    // 33: wishes.v1.types.enums.WishSortBy
	(enums.ResponseKind)(0),                  // 34: wishes.v1.types.enums.ResponseKind
	(enums.CouponStatus)(0),                  // 35: wishes.v1.types.enums.CouponStatus
	(*types.SoundtrackSong)(nil),             // 36: wishes.v1.types.SoundtrackSong
}
var file_wishes_v1_request_wishes_request_proto_depIdxs = []int32{
	31, // 0: wishes.v1.request.CreateWishRequest.config:type_name -> google.protobuf.Struct
	32, // 1: wishes.v1.request.ListMyWishesRequest.statuses:type_name -> wishes.v1.types.enums.WishStatus
	33, // 2: wishes.v1.request.ListMyWishesRequest.sort_by:type_name -> wishes.v1.types.enums.WishSortBy
	31, // 3: wishes.v1.request.UpdateWishRequest.config:type_name -> google.protobuf.Struct
	31, // 4: wishes.v1.request.SaveDraftRequest.config:type_name -> google.protobuf.Struct
	34, // 5: wishes.v1.request.SubmitResponseRequest.kind:type_name -> wishes.v1.types.enums.ResponseKind
	35, // 6: wishes.v1.request.SetCouponStatusRequest.status:type_name -> wishes.v1.types.enums.CouponStatus
	36, // 7: wishes.v1.request.UpdateTemplateSoundtracksRequest.songs:type_name -> wishes.v1.types.SoundtrackSong
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_wishes_v1_request_wishes_request_proto_init() }
func file_wishes_v1_request_wishes_request_proto_init() {
	if File_wishes_v1_request_wishes_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wishes_v1_request_wishes_request_proto_rawDesc), len(file_wishes_v1_request_wishes_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wishes_v1_request_wishes_request_proto_goTypes,
		DependencyIndexes: file_wishes_v1_request_wishes_request_proto_depIdxs,
		MessageInfos:      file_wishes_v1_request_wishes_request_proto_msgTypes,
	}.Build()
	File_wishes_v1_request_wishes_request_proto = out.File
	file_wishes_v1_request_wishes_request_proto_goTypes = nil
	file_wishes_v1_request_wishes_request_proto_depIdxs = nil
}
