// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: payment/v1/types/enums/payout.proto

package enums

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayoutMode int32

const (
	PayoutMode_PAYOUT_MODE_UNSPECIFIED PayoutMode = 0
	PayoutMode_PAYOUT_MODE_SCHEDULED   PayoutMode = 1
	PayoutMode_PAYOUT_MODE_INSTANT     PayoutMode = 2
)

// Enum value maps for PayoutMode.
var (
	PayoutMode_name = map[int32]string{
		0: "PAYOUT_MODE_UNSPECIFIED",
		1: "PAYOUT_MODE_SCHEDULED",
		2: "PAYOUT_MODE_INSTANT",
	}
	PayoutMode_value = map[string]int32{
		"PAYOUT_MODE_UNSPECIFIED": 0,
		"PAYOUT_MODE_SCHEDULED":   1,
		"PAYOUT_MODE_INSTANT":     2,
	}
)

func (x PayoutMode) Enum() *PayoutMode {
	p := new(PayoutMode)
	*p = x
	return p
}

func (x PayoutMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayoutMode) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_v1_types_enums_payout_proto_enumTypes[0].Descriptor()
}

func (PayoutMode) Type() protoreflect.EnumType {
	return &file_payment_v1_types_enums_payout_proto_enumTypes[0]
}

func (x PayoutMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayoutMode.Descriptor instead.
func (PayoutMode) EnumDescriptor() ([]byte, []int) {
	return file_payment_v1_types_enums_payout_proto_rawDescGZIP(), []int{0}
}

type PayoutStatus int32

const (
	PayoutStatus_PAYOUT_STATUS_UNSPECIFIED PayoutStatus = 0
	PayoutStatus_PAYOUT_STATUS_PENDING     PayoutStatus = 1
	PayoutStatus_PAYOUT_STATUS_RELEASED    PayoutStatus = 2
	PayoutStatus_PAYOUT_STATUS_FAILED      PayoutStatus = 3
)

// Enum value maps for PayoutStatus.
var (
	PayoutStatus_name = map[int32]string{
		0: "PAYOUT_STATUS_UNSPECIFIED",
		1: "PAYOUT_STATUS_PENDING",
		2: "PAYOUT_STATUS_RELEASED",
		3: "PAYOUT_STATUS_FAILED",
	}
	PayoutStatus_value = map[string]int32{
		"PAYOUT_STATUS_UNSPECIFIED": 0,
		"PAYOUT_STATUS_PENDING":     1,
		"PAYOUT_STATUS_RELEASED":    2,
		"PAYOUT_STATUS_FAILED":      3,
	}
)

func (x PayoutStatus) Enum() *PayoutStatus {
	p := new(PayoutStatus)
	*p = x
	return p
}

func (x PayoutStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayoutStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_payment_v1_types_enums_payout_proto_enumTypes[1].Descriptor()
}

func (PayoutStatus) Type() protoreflect.EnumType {
	return &file_payment_v1_types_enums_payout_proto_enumTypes[1]
}

func (x PayoutStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayoutStatus.Descriptor instead.
func (PayoutStatus) EnumDescriptor() ([]byte, []int) {
	return file_payment_v1_types_enums_payout_proto_rawDescGZIP(), []int{1}
}

var File_payment_v1_types_enums_payout_proto protoreflect.FileDescriptor

const file_payment_v1_types_enums_payout_proto_rawDesc = "" +
	"\n" +
	"#payment/v1/types/enums/payout.proto\x12\x16payment.v1.types.enums*]\n" +
	"\n" +
	"PayoutMode\x12\x1b\n" +
	"\x17PAYOUT_MODE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PAYOUT_MODE_SCHEDULED\x10\x01\x12\x17\n" +
	"\x13PAYOUT_MODE_INSTANT\x10\x02*~\n" +
	"\fPayoutStatus\x12\x1d\n" +
	"\x19PAYOUT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PAYOUT_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16PAYOUT_STATUS_RELEASED\x10\x02\x12\x18\n" +
	"\x14PAYOUT_STATUS_FAILED\x10\x03B9Z7github.com/arm-1234/protos/payment/v1/types/enums;enumsb\x06proto3"

var (
	file_payment_v1_types_enums_payout_proto_rawDescOnce sync.Once
	file_payment_v1_types_enums_payout_proto_rawDescData []byte
)

func file_payment_v1_types_enums_payout_proto_rawDescGZIP() []byte {
	file_payment_v1_types_enums_payout_proto_rawDescOnce.Do(func() {
		file_payment_v1_types_enums_payout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_v1_types_enums_payout_proto_rawDesc), len(file_payment_v1_types_enums_payout_proto_rawDesc)))
	})
	return file_payment_v1_types_enums_payout_proto_rawDescData
}

var file_payment_v1_types_enums_payout_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_payment_v1_types_enums_payout_proto_goTypes = []any{
	(PayoutMode)(0),   // 0: payment.v1.types.enums.PayoutMode
	(PayoutStatus)(0), // 1: payment.v1.types.enums.PayoutStatus
}
var file_payment_v1_types_enums_payout_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payment_v1_types_enums_payout_proto_init() }
func file_payment_v1_types_enums_payout_proto_init() {
	if File_payment_v1_types_enums_payout_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_v1_types_enums_payout_proto_rawDesc), len(file_payment_v1_types_enums_payout_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payment_v1_types_enums_payout_proto_goTypes,
		DependencyIndexes: file_payment_v1_types_enums_payout_proto_depIdxs,
		EnumInfos:         file_payment_v1_types_enums_payout_proto_enumTypes,
	}.Build()
	File_payment_v1_types_enums_payout_proto = out.File
	file_payment_v1_types_enums_payout_proto_goTypes = nil
	file_payment_v1_types_enums_payout_proto_depIdxs = nil
}
