syntax = "proto3";

package payment.v1.types.enums;

option go_package = "github.com/arm-1234/protos/payment/v1/types/enums;enums";

enum WalletOwnerType {
  WALLET_OWNER_TYPE_UNSPECIFIED = 0;
  WALLET_OWNER_TYPE_MERCHANT = 1;
  WALLET_OWNER_TYPE_USER = 2;
  WALLET_OWNER_TYPE_PLATFORM = 3;
}

enum WalletEntryReason {
  WALLET_ENTRY_REASON_UNSPECIFIED = 0;
  WALLET_ENTRY_REASON_ORDER_SALE = 1;
  WALLET_ENTRY_REASON_PLATFORM_FEE = 2;
  WALLET_ENTRY_REASON_WITHDRAWAL = 3;
  WALLET_ENTRY_REASON_WITHDRAWAL_REVERSAL = 4;
  WALLET_ENTRY_REASON_REFUND = 5;
  WALLET_ENTRY_REASON_ADJUSTMENT = 6;
}

enum WalletBalanceState {
  WALLET_BALANCE_STATE_UNSPECIFIED = 0;
  WALLET_BALANCE_STATE_PENDING = 1;
  WALLET_BALANCE_STATE_AVAILABLE = 2;
}

enum WithdrawalStatus {
  WITHDRAWAL_STATUS_UNSPECIFIED = 0;
  WITHDRAWAL_STATUS_REQUESTED = 1;
  WITHDRAWAL_STATUS_PROCESSING = 2;
  WITHDRAWAL_STATUS_PAID = 3;
  WITHDRAWAL_STATUS_FAILED = 4;
}

enum BankAccountKind {
  BANK_ACCOUNT_KIND_UNSPECIFIED = 0;
  BANK_ACCOUNT_KIND_SAVINGS = 1;
  BANK_ACCOUNT_KIND_CURRENT = 2;
  BANK_ACCOUNT_KIND_VPA = 3;
}
