// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v7.34.1
// source: merchant/v1/merchant.proto

package v1

import (
	context "context"
	request "github.com/arm-1234/protos/merchant/v1/request"
	response "github.com/arm-1234/protos/merchant/v1/response"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMerchantAddMerchantVpa = "/merchant.v1.Merchant/AddMerchantVpa"
const OperationMerchantDiscoverStores = "/merchant.v1.Merchant/DiscoverStores"
const OperationMerchantGetMerchant = "/merchant.v1.Merchant/GetMerchant"
const OperationMerchantListMerchantVpas = "/merchant.v1.Merchant/ListMerchantVpas"
const OperationMerchantOnboardMerchant = "/merchant.v1.Merchant/OnboardMerchant"
const OperationMerchantRemoveMerchantVpa = "/merchant.v1.Merchant/RemoveMerchantVpa"
const OperationMerchantRequestStoreUpdateOtp = "/merchant.v1.Merchant/RequestStoreUpdateOtp"
const OperationMerchantResolveStoreByVpa = "/merchant.v1.Merchant/ResolveStoreByVpa"
const OperationMerchantSetPrimaryMerchantVpa = "/merchant.v1.Merchant/SetPrimaryMerchantVpa"
const OperationMerchantUpdateMerchant = "/merchant.v1.Merchant/UpdateMerchant"

type MerchantHTTPServer interface {
	AddMerchantVpa(context.Context, *request.AddMerchantVpaRequest) (*response.MerchantVpasResponse, error)
	DiscoverStores(context.Context, *request.DiscoverStoresRequest) (*response.DiscoverStoresResponse, error)
	GetMerchant(context.Context, *request.GetMerchantRequest) (*response.GetMerchantResponse, error)
	ListMerchantVpas(context.Context, *request.ListMerchantVpasRequest) (*response.MerchantVpasResponse, error)
	OnboardMerchant(context.Context, *request.OnboardMerchantRequest) (*response.OnboardMerchantResponse, error)
	RemoveMerchantVpa(context.Context, *request.RemoveMerchantVpaRequest) (*response.MerchantVpasResponse, error)
	RequestStoreUpdateOtp(context.Context, *request.RequestStoreUpdateOtpRequest) (*response.RequestStoreUpdateOtpResponse, error)
	ResolveStoreByVpa(context.Context, *request.ResolveStoreByVpaRequest) (*response.ResolveStoreByVpaResponse, error)
	SetPrimaryMerchantVpa(context.Context, *request.SetPrimaryMerchantVpaRequest) (*response.MerchantVpasResponse, error)
	UpdateMerchant(context.Context, *request.UpdateMerchantRequest) (*response.UpdateMerchantResponse, error)
}

func RegisterMerchantHTTPServer(s *http.Server, srv MerchantHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/merchants", _Merchant_OnboardMerchant0_HTTP_Handler(srv))
	r.GET("/v1/merchants/{merchant_id}", _Merchant_GetMerchant0_HTTP_Handler(srv))
	r.PATCH("/v1/merchants/{merchant_id}", _Merchant_UpdateMerchant0_HTTP_Handler(srv))
	r.POST("/v1/merchants/{merchant_id}:requestUpdateOtp", _Merchant_RequestStoreUpdateOtp0_HTTP_Handler(srv))
	r.GET("/v1/stores:resolve", _Merchant_ResolveStoreByVpa0_HTTP_Handler(srv))
	r.GET("/v1/stores", _Merchant_DiscoverStores0_HTTP_Handler(srv))
	r.GET("/v1/merchants/{merchant_id}/vpas", _Merchant_ListMerchantVpas0_HTTP_Handler(srv))
	r.POST("/v1/merchants/{merchant_id}/vpas", _Merchant_AddMerchantVpa0_HTTP_Handler(srv))
	r.DELETE("/v1/merchants/{merchant_id}/vpas/{vpa_id}", _Merchant_RemoveMerchantVpa0_HTTP_Handler(srv))
	r.PATCH("/v1/merchants/{merchant_id}/vpas/{vpa_id}", _Merchant_SetPrimaryMerchantVpa0_HTTP_Handler(srv))
}

func _Merchant_OnboardMerchant0_HTTP_Handler(srv MerchantHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.OnboardMerchantRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMerchantOnboardMerchant)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.OnboardMerchant(ctx, req.(*request.OnboardMerchantRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.OnboardMerchantResponse)
		return ctx.Result(200, reply)
	}
}

func _Merchant_GetMerchant0_HTTP_Handler(srv MerchantHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.GetMerchantRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMerchantGetMerchant)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMerchant(ctx, req.(*request.GetMerchantRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.GetMerchantResponse)
		return ctx.Result(200, reply)
	}
}

func _Merchant_UpdateMerchant0_HTTP_Handler(srv MerchantHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.UpdateMerchantRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMerchantUpdateMerchant)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateMerchant(ctx, req.(*request.UpdateMerchantRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.UpdateMerchantResponse)
		return ctx.Result(200, reply)
	}
}

func _Merchant_RequestStoreUpdateOtp0_HTTP_Handler(srv MerchantHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.RequestStoreUpdateOtpRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMerchantRequestStoreUpdateOtp)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RequestStoreUpdateOtp(ctx, req.(*request.RequestStoreUpdateOtpRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.RequestStoreUpdateOtpResponse)
		return ctx.Result(200, reply)
	}
}

func _Merchant_ResolveStoreByVpa0_HTTP_Handler(srv MerchantHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.ResolveStoreByVpaRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMerchantResolveStoreByVpa)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ResolveStoreByVpa(ctx, req.(*request.ResolveStoreByVpaRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.ResolveStoreByVpaResponse)
		return ctx.Result(200, reply)
	}
}

func _Merchant_DiscoverStores0_HTTP_Handler(srv MerchantHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.DiscoverStoresRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMerchantDiscoverStores)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DiscoverStores(ctx, req.(*request.DiscoverStoresRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.DiscoverStoresResponse)
		return ctx.Result(200, reply)
	}
}

func _Merchant_ListMerchantVpas0_HTTP_Handler(srv MerchantHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.ListMerchantVpasRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMerchantListMerchantVpas)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMerchantVpas(ctx, req.(*request.ListMerchantVpasRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.MerchantVpasResponse)
		return ctx.Result(200, reply)
	}
}

func _Merchant_AddMerchantVpa0_HTTP_Handler(srv MerchantHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.AddMerchantVpaRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMerchantAddMerchantVpa)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddMerchantVpa(ctx, req.(*request.AddMerchantVpaRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.MerchantVpasResponse)
		return ctx.Result(200, reply)
	}
}

func _Merchant_RemoveMerchantVpa0_HTTP_Handler(srv MerchantHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.RemoveMerchantVpaRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMerchantRemoveMerchantVpa)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RemoveMerchantVpa(ctx, req.(*request.RemoveMerchantVpaRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.MerchantVpasResponse)
		return ctx.Result(200, reply)
	}
}

func _Merchant_SetPrimaryMerchantVpa0_HTTP_Handler(srv MerchantHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in request.SetPrimaryMerchantVpaRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMerchantSetPrimaryMerchantVpa)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetPrimaryMerchantVpa(ctx, req.(*request.SetPrimaryMerchantVpaRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*response.MerchantVpasResponse)
		return ctx.Result(200, reply)
	}
}

type MerchantHTTPClient interface {
	AddMerchantVpa(ctx context.Context, req *request.AddMerchantVpaRequest, opts ...http.CallOption) (rsp *response.MerchantVpasResponse, err error)
	DiscoverStores(ctx context.Context, req *request.DiscoverStoresRequest, opts ...http.CallOption) (rsp *response.DiscoverStoresResponse, err error)
	GetMerchant(ctx context.Context, req *request.GetMerchantRequest, opts ...http.CallOption) (rsp *response.GetMerchantResponse, err error)
	ListMerchantVpas(ctx context.Context, req *request.ListMerchantVpasRequest, opts ...http.CallOption) (rsp *response.MerchantVpasResponse, err error)
	OnboardMerchant(ctx context.Context, req *request.OnboardMerchantRequest, opts ...http.CallOption) (rsp *response.OnboardMerchantResponse, err error)
	RemoveMerchantVpa(ctx context.Context, req *request.RemoveMerchantVpaRequest, opts ...http.CallOption) (rsp *response.MerchantVpasResponse, err error)
	RequestStoreUpdateOtp(ctx context.Context, req *request.RequestStoreUpdateOtpRequest, opts ...http.CallOption) (rsp *response.RequestStoreUpdateOtpResponse, err error)
	ResolveStoreByVpa(ctx context.Context, req *request.ResolveStoreByVpaRequest, opts ...http.CallOption) (rsp *response.ResolveStoreByVpaResponse, err error)
	SetPrimaryMerchantVpa(ctx context.Context, req *request.SetPrimaryMerchantVpaRequest, opts ...http.CallOption) (rsp *response.MerchantVpasResponse, err error)
	UpdateMerchant(ctx context.Context, req *request.UpdateMerchantRequest, opts ...http.CallOption) (rsp *response.UpdateMerchantResponse, err error)
}

type MerchantHTTPClientImpl struct {
	cc *http.Client
}

func NewMerchantHTTPClient(client *http.Client) MerchantHTTPClient {
	return &MerchantHTTPClientImpl{client}
}

func (c *MerchantHTTPClientImpl) AddMerchantVpa(ctx context.Context, in *request.AddMerchantVpaRequest, opts ...http.CallOption) (*response.MerchantVpasResponse, error) {
	var out response.MerchantVpasResponse
	pattern := "/v1/merchants/{merchant_id}/vpas"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMerchantAddMerchantVpa))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MerchantHTTPClientImpl) DiscoverStores(ctx context.Context, in *request.DiscoverStoresRequest, opts ...http.CallOption) (*response.DiscoverStoresResponse, error) {
	var out response.DiscoverStoresResponse
	pattern := "/v1/stores"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMerchantDiscoverStores))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MerchantHTTPClientImpl) GetMerchant(ctx context.Context, in *request.GetMerchantRequest, opts ...http.CallOption) (*response.GetMerchantResponse, error) {
	var out response.GetMerchantResponse
	pattern := "/v1/merchants/{merchant_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMerchantGetMerchant))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MerchantHTTPClientImpl) ListMerchantVpas(ctx context.Context, in *request.ListMerchantVpasRequest, opts ...http.CallOption) (*response.MerchantVpasResponse, error) {
	var out response.MerchantVpasResponse
	pattern := "/v1/merchants/{merchant_id}/vpas"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMerchantListMerchantVpas))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MerchantHTTPClientImpl) OnboardMerchant(ctx context.Context, in *request.OnboardMerchantRequest, opts ...http.CallOption) (*response.OnboardMerchantResponse, error) {
	var out response.OnboardMerchantResponse
	pattern := "/v1/merchants"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMerchantOnboardMerchant))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MerchantHTTPClientImpl) RemoveMerchantVpa(ctx context.Context, in *request.RemoveMerchantVpaRequest, opts ...http.CallOption) (*response.MerchantVpasResponse, error) {
	var out response.MerchantVpasResponse
	pattern := "/v1/merchants/{merchant_id}/vpas/{vpa_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMerchantRemoveMerchantVpa))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MerchantHTTPClientImpl) RequestStoreUpdateOtp(ctx context.Context, in *request.RequestStoreUpdateOtpRequest, opts ...http.CallOption) (*response.RequestStoreUpdateOtpResponse, error) {
	var out response.RequestStoreUpdateOtpResponse
	pattern := "/v1/merchants/{merchant_id}:requestUpdateOtp"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMerchantRequestStoreUpdateOtp))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MerchantHTTPClientImpl) ResolveStoreByVpa(ctx context.Context, in *request.ResolveStoreByVpaRequest, opts ...http.CallOption) (*response.ResolveStoreByVpaResponse, error) {
	var out response.ResolveStoreByVpaResponse
	pattern := "/v1/stores:resolve"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMerchantResolveStoreByVpa))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MerchantHTTPClientImpl) SetPrimaryMerchantVpa(ctx context.Context, in *request.SetPrimaryMerchantVpaRequest, opts ...http.CallOption) (*response.MerchantVpasResponse, error) {
	var out response.MerchantVpasResponse
	pattern := "/v1/merchants/{merchant_id}/vpas/{vpa_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMerchantSetPrimaryMerchantVpa))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MerchantHTTPClientImpl) UpdateMerchant(ctx context.Context, in *request.UpdateMerchantRequest, opts ...http.CallOption) (*response.UpdateMerchantResponse, error) {
	var out response.UpdateMerchantResponse
	pattern := "/v1/merchants/{merchant_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMerchantUpdateMerchant))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
