// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: payment/v1/payment.proto

package v1

import (
	context "context"
	request "github.com/arm-1234/protos/payment/v1/request"
	response "github.com/arm-1234/protos/payment/v1/response"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Payment_InitiatePayment_FullMethodName      = "/payment.v1.Payment/InitiatePayment"
	Payment_VerifyPayment_FullMethodName        = "/payment.v1.Payment/VerifyPayment"
	Payment_GetPaymentStatus_FullMethodName     = "/payment.v1.Payment/GetPaymentStatus"
	Payment_RequestInstantPayout_FullMethodName = "/payment.v1.Payment/RequestInstantPayout"
	Payment_GetPayout_FullMethodName            = "/payment.v1.Payment/GetPayout"
	Payment_GetWallet_FullMethodName            = "/payment.v1.Payment/GetWallet"
	Payment_ListWalletEntries_FullMethodName    = "/payment.v1.Payment/ListWalletEntries"
	Payment_AddBankAccount_FullMethodName       = "/payment.v1.Payment/AddBankAccount"
	Payment_ListBankAccounts_FullMethodName     = "/payment.v1.Payment/ListBankAccounts"
	Payment_DeleteBankAccount_FullMethodName    = "/payment.v1.Payment/DeleteBankAccount"
	Payment_RequestWithdrawal_FullMethodName    = "/payment.v1.Payment/RequestWithdrawal"
	Payment_ListWithdrawals_FullMethodName      = "/payment.v1.Payment/ListWithdrawals"
	Payment_GetWithdrawal_FullMethodName        = "/payment.v1.Payment/GetWithdrawal"
)

// PaymentClient is the client API for Payment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentClient interface {
	InitiatePayment(ctx context.Context, in *request.InitiatePaymentRequest, opts ...grpc.CallOption) (*response.InitiatePaymentResponse, error)
	VerifyPayment(ctx context.Context, in *request.VerifyPaymentRequest, opts ...grpc.CallOption) (*response.VerifyPaymentResponse, error)
	GetPaymentStatus(ctx context.Context, in *request.GetPaymentStatusRequest, opts ...grpc.CallOption) (*response.GetPaymentStatusResponse, error)
	RequestInstantPayout(ctx context.Context, in *request.RequestInstantPayoutRequest, opts ...grpc.CallOption) (*response.RequestInstantPayoutResponse, error)
	GetPayout(ctx context.Context, in *request.GetPayoutRequest, opts ...grpc.CallOption) (*response.GetPayoutResponse, error)
	GetWallet(ctx context.Context, in *request.GetWalletRequest, opts ...grpc.CallOption) (*response.GetWalletResponse, error)
	ListWalletEntries(ctx context.Context, in *request.ListWalletEntriesRequest, opts ...grpc.CallOption) (*response.ListWalletEntriesResponse, error)
	AddBankAccount(ctx context.Context, in *request.AddBankAccountRequest, opts ...grpc.CallOption) (*response.AddBankAccountResponse, error)
	ListBankAccounts(ctx context.Context, in *request.ListBankAccountsRequest, opts ...grpc.CallOption) (*response.ListBankAccountsResponse, error)
	DeleteBankAccount(ctx context.Context, in *request.DeleteBankAccountRequest, opts ...grpc.CallOption) (*response.DeleteBankAccountResponse, error)
	RequestWithdrawal(ctx context.Context, in *request.RequestWithdrawalRequest, opts ...grpc.CallOption) (*response.RequestWithdrawalResponse, error)
	ListWithdrawals(ctx context.Context, in *request.ListWithdrawalsRequest, opts ...grpc.CallOption) (*response.ListWithdrawalsResponse, error)
	GetWithdrawal(ctx context.Context, in *request.GetWithdrawalRequest, opts ...grpc.CallOption) (*response.GetWithdrawalResponse, error)
}

type paymentClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentClient(cc grpc.ClientConnInterface) PaymentClient {
	return &paymentClient{cc}
}

func (c *paymentClient) InitiatePayment(ctx context.Context, in *request.InitiatePaymentRequest, opts ...grpc.CallOption) (*response.InitiatePaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.InitiatePaymentResponse)
	err := c.cc.Invoke(ctx, Payment_InitiatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) VerifyPayment(ctx context.Context, in *request.VerifyPaymentRequest, opts ...grpc.CallOption) (*response.VerifyPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.VerifyPaymentResponse)
	err := c.cc.Invoke(ctx, Payment_VerifyPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) GetPaymentStatus(ctx context.Context, in *request.GetPaymentStatusRequest, opts ...grpc.CallOption) (*response.GetPaymentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.GetPaymentStatusResponse)
	err := c.cc.Invoke(ctx, Payment_GetPaymentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) RequestInstantPayout(ctx context.Context, in *request.RequestInstantPayoutRequest, opts ...grpc.CallOption) (*response.RequestInstantPayoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.RequestInstantPayoutResponse)
	err := c.cc.Invoke(ctx, Payment_RequestInstantPayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) GetPayout(ctx context.Context, in *request.GetPayoutRequest, opts ...grpc.CallOption) (*response.GetPayoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.GetPayoutResponse)
	err := c.cc.Invoke(ctx, Payment_GetPayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) GetWallet(ctx context.Context, in *request.GetWalletRequest, opts ...grpc.CallOption) (*response.GetWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.GetWalletResponse)
	err := c.cc.Invoke(ctx, Payment_GetWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) ListWalletEntries(ctx context.Context, in *request.ListWalletEntriesRequest, opts ...grpc.CallOption) (*response.ListWalletEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.ListWalletEntriesResponse)
	err := c.cc.Invoke(ctx, Payment_ListWalletEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) AddBankAccount(ctx context.Context, in *request.AddBankAccountRequest, opts ...grpc.CallOption) (*response.AddBankAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.AddBankAccountResponse)
	err := c.cc.Invoke(ctx, Payment_AddBankAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) ListBankAccounts(ctx context.Context, in *request.ListBankAccountsRequest, opts ...grpc.CallOption) (*response.ListBankAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.ListBankAccountsResponse)
	err := c.cc.Invoke(ctx, Payment_ListBankAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) DeleteBankAccount(ctx context.Context, in *request.DeleteBankAccountRequest, opts ...grpc.CallOption) (*response.DeleteBankAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.DeleteBankAccountResponse)
	err := c.cc.Invoke(ctx, Payment_DeleteBankAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) RequestWithdrawal(ctx context.Context, in *request.RequestWithdrawalRequest, opts ...grpc.CallOption) (*response.RequestWithdrawalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.RequestWithdrawalResponse)
	err := c.cc.Invoke(ctx, Payment_RequestWithdrawal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) ListWithdrawals(ctx context.Context, in *request.ListWithdrawalsRequest, opts ...grpc.CallOption) (*response.ListWithdrawalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.ListWithdrawalsResponse)
	err := c.cc.Invoke(ctx, Payment_ListWithdrawals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentClient) GetWithdrawal(ctx context.Context, in *request.GetWithdrawalRequest, opts ...grpc.CallOption) (*response.GetWithdrawalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(response.GetWithdrawalResponse)
	err := c.cc.Invoke(ctx, Payment_GetWithdrawal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServer is the server API for Payment service.
// All implementations must embed UnimplementedPaymentServer
// for forward compatibility.
type PaymentServer interface {
	InitiatePayment(context.Context, *request.InitiatePaymentRequest) (*response.InitiatePaymentResponse, error)
	VerifyPayment(context.Context, *request.VerifyPaymentRequest) (*response.VerifyPaymentResponse, error)
	GetPaymentStatus(context.Context, *request.GetPaymentStatusRequest) (*response.GetPaymentStatusResponse, error)
	RequestInstantPayout(context.Context, *request.RequestInstantPayoutRequest) (*response.RequestInstantPayoutResponse, error)
	GetPayout(context.Context, *request.GetPayoutRequest) (*response.GetPayoutResponse, error)
	GetWallet(context.Context, *request.GetWalletRequest) (*response.GetWalletResponse, error)
	ListWalletEntries(context.Context, *request.ListWalletEntriesRequest) (*response.ListWalletEntriesResponse, error)
	AddBankAccount(context.Context, *request.AddBankAccountRequest) (*response.AddBankAccountResponse, error)
	ListBankAccounts(context.Context, *request.ListBankAccountsRequest) (*response.ListBankAccountsResponse, error)
	DeleteBankAccount(context.Context, *request.DeleteBankAccountRequest) (*response.DeleteBankAccountResponse, error)
	RequestWithdrawal(context.Context, *request.RequestWithdrawalRequest) (*response.RequestWithdrawalResponse, error)
	ListWithdrawals(context.Context, *request.ListWithdrawalsRequest) (*response.ListWithdrawalsResponse, error)
	GetWithdrawal(context.Context, *request.GetWithdrawalRequest) (*response.GetWithdrawalResponse, error)
	mustEmbedUnimplementedPaymentServer()
}

// UnimplementedPaymentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentServer struct{}

func (UnimplementedPaymentServer) InitiatePayment(context.Context, *request.InitiatePaymentRequest) (*response.InitiatePaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiatePayment not implemented")
}
func (UnimplementedPaymentServer) VerifyPayment(context.Context, *request.VerifyPaymentRequest) (*response.VerifyPaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyPayment not implemented")
}
func (UnimplementedPaymentServer) GetPaymentStatus(context.Context, *request.GetPaymentStatusRequest) (*response.GetPaymentStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPaymentStatus not implemented")
}
func (UnimplementedPaymentServer) RequestInstantPayout(context.Context, *request.RequestInstantPayoutRequest) (*response.RequestInstantPayoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestInstantPayout not implemented")
}
func (UnimplementedPaymentServer) GetPayout(context.Context, *request.GetPayoutRequest) (*response.GetPayoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPayout not implemented")
}
func (UnimplementedPaymentServer) GetWallet(context.Context, *request.GetWalletRequest) (*response.GetWalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWallet not implemented")
}
func (UnimplementedPaymentServer) ListWalletEntries(context.Context, *request.ListWalletEntriesRequest) (*response.ListWalletEntriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWalletEntries not implemented")
}
func (UnimplementedPaymentServer) AddBankAccount(context.Context, *request.AddBankAccountRequest) (*response.AddBankAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddBankAccount not implemented")
}
func (UnimplementedPaymentServer) ListBankAccounts(context.Context, *request.ListBankAccountsRequest) (*response.ListBankAccountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBankAccounts not implemented")
}
func (UnimplementedPaymentServer) DeleteBankAccount(context.Context, *request.DeleteBankAccountRequest) (*response.DeleteBankAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBankAccount not implemented")
}
func (UnimplementedPaymentServer) RequestWithdrawal(context.Context, *request.RequestWithdrawalRequest) (*response.RequestWithdrawalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestWithdrawal not implemented")
}
func (UnimplementedPaymentServer) ListWithdrawals(context.Context, *request.ListWithdrawalsRequest) (*response.ListWithdrawalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWithdrawals not implemented")
}
func (UnimplementedPaymentServer) GetWithdrawal(context.Context, *request.GetWithdrawalRequest) (*response.GetWithdrawalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWithdrawal not implemented")
}
func (UnimplementedPaymentServer) mustEmbedUnimplementedPaymentServer() {}
func (UnimplementedPaymentServer) testEmbeddedByValue()                 {}

// UnsafePaymentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServer will
// result in compilation errors.
type UnsafePaymentServer interface {
	mustEmbedUnimplementedPaymentServer()
}

func RegisterPaymentServer(s grpc.ServiceRegistrar, srv PaymentServer) {
	// If the following call panics, it indicates UnimplementedPaymentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Payment_ServiceDesc, srv)
}

func _Payment_InitiatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.InitiatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).InitiatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_InitiatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).InitiatePayment(ctx, req.(*request.InitiatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_VerifyPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.VerifyPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).VerifyPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_VerifyPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).VerifyPayment(ctx, req.(*request.VerifyPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_GetPaymentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.GetPaymentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).GetPaymentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_GetPaymentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).GetPaymentStatus(ctx, req.(*request.GetPaymentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_RequestInstantPayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.RequestInstantPayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).RequestInstantPayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_RequestInstantPayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).RequestInstantPayout(ctx, req.(*request.RequestInstantPayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_GetPayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.GetPayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).GetPayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_GetPayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).GetPayout(ctx, req.(*request.GetPayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_GetWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.GetWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).GetWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_GetWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).GetWallet(ctx, req.(*request.GetWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_ListWalletEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.ListWalletEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).ListWalletEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_ListWalletEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).ListWalletEntries(ctx, req.(*request.ListWalletEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_AddBankAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.AddBankAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).AddBankAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_AddBankAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).AddBankAccount(ctx, req.(*request.AddBankAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_ListBankAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.ListBankAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).ListBankAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_ListBankAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).ListBankAccounts(ctx, req.(*request.ListBankAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_DeleteBankAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.DeleteBankAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).DeleteBankAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_DeleteBankAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).DeleteBankAccount(ctx, req.(*request.DeleteBankAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_RequestWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.RequestWithdrawalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).RequestWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_RequestWithdrawal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).RequestWithdrawal(ctx, req.(*request.RequestWithdrawalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_ListWithdrawals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.ListWithdrawalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).ListWithdrawals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_ListWithdrawals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).ListWithdrawals(ctx, req.(*request.ListWithdrawalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payment_GetWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.GetWithdrawalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServer).GetWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Payment_GetWithdrawal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServer).GetWithdrawal(ctx, req.(*request.GetWithdrawalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Payment_ServiceDesc is the grpc.ServiceDesc for Payment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Payment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.v1.Payment",
	HandlerType: (*PaymentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiatePayment",
			Handler:    _Payment_InitiatePayment_Handler,
		},
		{
			MethodName: "VerifyPayment",
			Handler:    _Payment_VerifyPayment_Handler,
		},
		{
			MethodName: "GetPaymentStatus",
			Handler:    _Payment_GetPaymentStatus_Handler,
		},
		{
			MethodName: "RequestInstantPayout",
			Handler:    _Payment_RequestInstantPayout_Handler,
		},
		{
			MethodName: "GetPayout",
			Handler:    _Payment_GetPayout_Handler,
		},
		{
			MethodName: "GetWallet",
			Handler:    _Payment_GetWallet_Handler,
		},
		{
			MethodName: "ListWalletEntries",
			Handler:    _Payment_ListWalletEntries_Handler,
		},
		{
			MethodName: "AddBankAccount",
			Handler:    _Payment_AddBankAccount_Handler,
		},
		{
			MethodName: "ListBankAccounts",
			Handler:    _Payment_ListBankAccounts_Handler,
		},
		{
			MethodName: "DeleteBankAccount",
			Handler:    _Payment_DeleteBankAccount_Handler,
		},
		{
			MethodName: "RequestWithdrawal",
			Handler:    _Payment_RequestWithdrawal_Handler,
		},
		{
			MethodName: "ListWithdrawals",
			Handler:    _Payment_ListWithdrawals_Handler,
		},
		{
			MethodName: "GetWithdrawal",
			Handler:    _Payment_GetWithdrawal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment/v1/payment.proto",
}
