// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: fitness/v1/fitness.proto

package v1

import (
	request "github.com/arm-1234/protos/fitness/v1/request"
	response "github.com/arm-1234/protos/fitness/v1/response"
	_ "github.com/go-kratos/kratos/v2/errors"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_FITNESS_UNSPECIFIED     ErrorReason = 0
	ErrorReason_FITNESS_INVALID_REQUEST ErrorReason = 1
	ErrorReason_FITNESS_FORBIDDEN       ErrorReason = 2
	// Caller is authenticated but is not a USER_TYPE_ADMIN.
	ErrorReason_FITNESS_ADMIN_REQUIRED  ErrorReason = 3
	ErrorReason_FITNESS_UNAUTHENTICATED ErrorReason = 4
	ErrorReason_PROFILE_NOT_FOUND       ErrorReason = 10
	// Home region is locked for a cooldown so users cannot hop to a weak district.
	ErrorReason_PROFILE_REGION_LOCKED ErrorReason = 11
	ErrorReason_REGION_NOT_FOUND      ErrorReason = 12
	// Barred from earning after upheld fraud findings.
	ErrorReason_USER_SUSPENDED             ErrorReason = 13
	ErrorReason_COMPETITION_NOT_FOUND      ErrorReason = 20
	ErrorReason_COMPETITION_NOT_ACTIVE     ErrorReason = 21
	ErrorReason_COMPETITION_ALREADY_JOINED ErrorReason = 22
	ErrorReason_COMPETITION_NOT_JOINED     ErrorReason = 23
	// Home region does not match the competition's scope.
	ErrorReason_COMPETITION_REGION_INELIGIBLE ErrorReason = 24
	ErrorReason_CHALLENGE_NOT_FOUND           ErrorReason = 30
	ErrorReason_CHALLENGE_TEMPLATE_NOT_FOUND  ErrorReason = 31
	ErrorReason_CHALLENGE_DAILY_LIMIT_REACHED ErrorReason = 32
	ErrorReason_CHALLENGE_COOLDOWN_ACTIVE     ErrorReason = 33
	ErrorReason_CHALLENGE_ALREADY_IN_PROGRESS ErrorReason = 34
	ErrorReason_CHALLENGE_EXPIRED             ErrorReason = 35
	ErrorReason_CHALLENGE_NOT_IN_PROGRESS     ErrorReason = 36
	ErrorReason_DAILY_STEP_CAP_REACHED        ErrorReason = 37
	ErrorReason_DAILY_POINTS_CAP_REACHED      ErrorReason = 38
	ErrorReason_SESSION_NOT_FOUND             ErrorReason = 40
	ErrorReason_SESSION_NOT_ACTIVE            ErrorReason = 41
	ErrorReason_SESSION_ALREADY_FINALIZED     ErrorReason = 42
	// Another session is still open for this user.
	ErrorReason_SESSION_ALREADY_ACTIVE          ErrorReason = 43
	ErrorReason_SESSION_SAMPLE_SEQUENCE_INVALID ErrorReason = 44
	ErrorReason_SESSION_TOO_SHORT               ErrorReason = 45
	// Anti-cheat rejections, split so the app can explain what went wrong.
	ErrorReason_ANTI_CHEAT_REJECTED          ErrorReason = 50
	ErrorReason_ANTI_CHEAT_MOCK_LOCATION     ErrorReason = 51
	ErrorReason_ANTI_CHEAT_SPEED_VIOLATION   ErrorReason = 52
	ErrorReason_ANTI_CHEAT_INTEGRITY_FAILED  ErrorReason = 53
	ErrorReason_ANTI_CHEAT_GEOFENCE_MISMATCH ErrorReason = 54
	ErrorReason_ANTI_CHEAT_DEVICE_SHARED     ErrorReason = 55
	ErrorReason_ANTI_CHEAT_CLOCK_SKEW        ErrorReason = 56
	ErrorReason_POINTS_INSUFFICIENT          ErrorReason = 60
	ErrorReason_GIFT_NOT_FOUND               ErrorReason = 61
	ErrorReason_GIFT_OUT_OF_STOCK            ErrorReason = 62
	ErrorReason_GIFT_NOT_AVAILABLE           ErrorReason = 63
	ErrorReason_GIFT_PER_USER_LIMIT_REACHED  ErrorReason = 64
	ErrorReason_REDEMPTION_NOT_FOUND         ErrorReason = 65
	ErrorReason_REDEMPTION_NOT_CANCELLABLE   ErrorReason = 66
	// Redeeming requires a verified email, so throwaway addresses cannot farm gifts.
	ErrorReason_REDEMPTION_EMAIL_NOT_VERIFIED ErrorReason = 67
	ErrorReason_REDEMPTION_NOT_FULFILLABLE    ErrorReason = 68
	ErrorReason_LEADERBOARD_NOT_AVAILABLE     ErrorReason = 70
	ErrorReason_IMAGE_UPLOAD_UNAVAILABLE      ErrorReason = 80
	ErrorReason_IMAGE_TYPE_UNSUPPORTED        ErrorReason = 81
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:  "FITNESS_UNSPECIFIED",
		1:  "FITNESS_INVALID_REQUEST",
		2:  "FITNESS_FORBIDDEN",
		3:  "FITNESS_ADMIN_REQUIRED",
		4:  "FITNESS_UNAUTHENTICATED",
		10: "PROFILE_NOT_FOUND",
		11: "PROFILE_REGION_LOCKED",
		12: "REGION_NOT_FOUND",
		13: "USER_SUSPENDED",
		20: "COMPETITION_NOT_FOUND",
		21: "COMPETITION_NOT_ACTIVE",
		22: "COMPETITION_ALREADY_JOINED",
		23: "COMPETITION_NOT_JOINED",
		24: "COMPETITION_REGION_INELIGIBLE",
		30: "CHALLENGE_NOT_FOUND",
		31: "CHALLENGE_TEMPLATE_NOT_FOUND",
		32: "CHALLENGE_DAILY_LIMIT_REACHED",
		33: "CHALLENGE_COOLDOWN_ACTIVE",
		34: "CHALLENGE_ALREADY_IN_PROGRESS",
		35: "CHALLENGE_EXPIRED",
		36: "CHALLENGE_NOT_IN_PROGRESS",
		37: "DAILY_STEP_CAP_REACHED",
		38: "DAILY_POINTS_CAP_REACHED",
		40: "SESSION_NOT_FOUND",
		41: "SESSION_NOT_ACTIVE",
		42: "SESSION_ALREADY_FINALIZED",
		43: "SESSION_ALREADY_ACTIVE",
		44: "SESSION_SAMPLE_SEQUENCE_INVALID",
		45: "SESSION_TOO_SHORT",
		50: "ANTI_CHEAT_REJECTED",
		51: "ANTI_CHEAT_MOCK_LOCATION",
		52: "ANTI_CHEAT_SPEED_VIOLATION",
		53: "ANTI_CHEAT_INTEGRITY_FAILED",
		54: "ANTI_CHEAT_GEOFENCE_MISMATCH",
		55: "ANTI_CHEAT_DEVICE_SHARED",
		56: "ANTI_CHEAT_CLOCK_SKEW",
		60: "POINTS_INSUFFICIENT",
		61: "GIFT_NOT_FOUND",
		62: "GIFT_OUT_OF_STOCK",
		63: "GIFT_NOT_AVAILABLE",
		64: "GIFT_PER_USER_LIMIT_REACHED",
		65: "REDEMPTION_NOT_FOUND",
		66: "REDEMPTION_NOT_CANCELLABLE",
		67: "REDEMPTION_EMAIL_NOT_VERIFIED",
		68: "REDEMPTION_NOT_FULFILLABLE",
		70: "LEADERBOARD_NOT_AVAILABLE",
		80: "IMAGE_UPLOAD_UNAVAILABLE",
		81: "IMAGE_TYPE_UNSUPPORTED",
	}
	ErrorReason_value = map[string]int32{
		"FITNESS_UNSPECIFIED":             0,
		"FITNESS_INVALID_REQUEST":         1,
		"FITNESS_FORBIDDEN":               2,
		"FITNESS_ADMIN_REQUIRED":          3,
		"FITNESS_UNAUTHENTICATED":         4,
		"PROFILE_NOT_FOUND":               10,
		"PROFILE_REGION_LOCKED":           11,
		"REGION_NOT_FOUND":                12,
		"USER_SUSPENDED":                  13,
		"COMPETITION_NOT_FOUND":           20,
		"COMPETITION_NOT_ACTIVE":          21,
		"COMPETITION_ALREADY_JOINED":      22,
		"COMPETITION_NOT_JOINED":          23,
		"COMPETITION_REGION_INELIGIBLE":   24,
		"CHALLENGE_NOT_FOUND":             30,
		"CHALLENGE_TEMPLATE_NOT_FOUND":    31,
		"CHALLENGE_DAILY_LIMIT_REACHED":   32,
		"CHALLENGE_COOLDOWN_ACTIVE":       33,
		"CHALLENGE_ALREADY_IN_PROGRESS":   34,
		"CHALLENGE_EXPIRED":               35,
		"CHALLENGE_NOT_IN_PROGRESS":       36,
		"DAILY_STEP_CAP_REACHED":          37,
		"DAILY_POINTS_CAP_REACHED":        38,
		"SESSION_NOT_FOUND":               40,
		"SESSION_NOT_ACTIVE":              41,
		"SESSION_ALREADY_FINALIZED":       42,
		"SESSION_ALREADY_ACTIVE":          43,
		"SESSION_SAMPLE_SEQUENCE_INVALID": 44,
		"SESSION_TOO_SHORT":               45,
		"ANTI_CHEAT_REJECTED":             50,
		"ANTI_CHEAT_MOCK_LOCATION":        51,
		"ANTI_CHEAT_SPEED_VIOLATION":      52,
		"ANTI_CHEAT_INTEGRITY_FAILED":     53,
		"ANTI_CHEAT_GEOFENCE_MISMATCH":    54,
		"ANTI_CHEAT_DEVICE_SHARED":        55,
		"ANTI_CHEAT_CLOCK_SKEW":           56,
		"POINTS_INSUFFICIENT":             60,
		"GIFT_NOT_FOUND":                  61,
		"GIFT_OUT_OF_STOCK":               62,
		"GIFT_NOT_AVAILABLE":              63,
		"GIFT_PER_USER_LIMIT_REACHED":     64,
		"REDEMPTION_NOT_FOUND":            65,
		"REDEMPTION_NOT_CANCELLABLE":      66,
		"REDEMPTION_EMAIL_NOT_VERIFIED":   67,
		"REDEMPTION_NOT_FULFILLABLE":      68,
		"LEADERBOARD_NOT_AVAILABLE":       70,
		"IMAGE_UPLOAD_UNAVAILABLE":        80,
		"IMAGE_TYPE_UNSUPPORTED":          81,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_fitness_v1_fitness_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_fitness_v1_fitness_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_fitness_v1_fitness_proto_rawDescGZIP(), []int{0}
}

var File_fitness_v1_fitness_proto protoreflect.FileDescriptor

const file_fitness_v1_fitness_proto_rawDesc = "" +
	"\n" +
	"\x18fitness/v1/fitness.proto\x12\n" +
	"fitness.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x13errors/errors.proto\x1a(fitness/v1/request/fitness_request.proto\x1a*fitness/v1/response/fitness_response.proto*\x87\r\n" +
	"\vErrorReason\x12\x1d\n" +
	"\x13FITNESS_UNSPECIFIED\x10\x00\x1a\x04\xa8E\xf4\x03\x12!\n" +
	"\x17FITNESS_INVALID_REQUEST\x10\x01\x1a\x04\xa8E\x90\x03\x12\x1b\n" +
	"\x11FITNESS_FORBIDDEN\x10\x02\x1a\x04\xa8E\x93\x03\x12 \n" +
	"\x16FITNESS_ADMIN_REQUIRED\x10\x03\x1a\x04\xa8E\x93\x03\x12!\n" +
	"\x17FITNESS_UNAUTHENTICATED\x10\x04\x1a\x04\xa8E\x91\x03\x12\x1b\n" +
	"\x11PROFILE_NOT_FOUND\x10\n" +
	"\x1a\x04\xa8E\x94\x03\x12\x1f\n" +
	"\x15PROFILE_REGION_LOCKED\x10\v\x1a\x04\xa8E\x99\x03\x12\x1a\n" +
	"\x10REGION_NOT_FOUND\x10\f\x1a\x04\xa8E\x94\x03\x12\x18\n" +
	"\x0eUSER_SUSPENDED\x10\r\x1a\x04\xa8E\x93\x03\x12\x1f\n" +
	"\x15COMPETITION_NOT_FOUND\x10\x14\x1a\x04\xa8E\x94\x03\x12 \n" +
	"\x16COMPETITION_NOT_ACTIVE\x10\x15\x1a\x04\xa8E\x99\x03\x12$\n" +
	"\x1aCOMPETITION_ALREADY_JOINED\x10\x16\x1a\x04\xa8E\x99\x03\x12 \n" +
	"\x16COMPETITION_NOT_JOINED\x10\x17\x1a\x04\xa8E\x93\x03\x12'\n" +
	"\x1dCOMPETITION_REGION_INELIGIBLE\x10\x18\x1a\x04\xa8E\x93\x03\x12\x1d\n" +
	"\x13CHALLENGE_NOT_FOUND\x10\x1e\x1a\x04\xa8E\x94\x03\x12&\n" +
	"\x1cCHALLENGE_TEMPLATE_NOT_FOUND\x10\x1f\x1a\x04\xa8E\x94\x03\x12'\n" +
	"\x1dCHALLENGE_DAILY_LIMIT_REACHED\x10 \x1a\x04\xa8E\xad\x03\x12#\n" +
	"\x19CHALLENGE_COOLDOWN_ACTIVE\x10!\x1a\x04\xa8E\xad\x03\x12'\n" +
	"\x1dCHALLENGE_ALREADY_IN_PROGRESS\x10\"\x1a\x04\xa8E\x99\x03\x12\x1b\n" +
	"\x11CHALLENGE_EXPIRED\x10#\x1a\x04\xa8E\x99\x03\x12#\n" +
	"\x19CHALLENGE_NOT_IN_PROGRESS\x10$\x1a\x04\xa8E\x99\x03\x12 \n" +
	"\x16DAILY_STEP_CAP_REACHED\x10%\x1a\x04\xa8E\xad\x03\x12\"\n" +
	"\x18DAILY_POINTS_CAP_REACHED\x10&\x1a\x04\xa8E\xad\x03\x12\x1b\n" +
	"\x11SESSION_NOT_FOUND\x10(\x1a\x04\xa8E\x94\x03\x12\x1c\n" +
	"\x12SESSION_NOT_ACTIVE\x10)\x1a\x04\xa8E\x99\x03\x12#\n" +
	"\x19SESSION_ALREADY_FINALIZED\x10*\x1a\x04\xa8E\x99\x03\x12 \n" +
	"\x16SESSION_ALREADY_ACTIVE\x10+\x1a\x04\xa8E\x99\x03\x12)\n" +
	"\x1fSESSION_SAMPLE_SEQUENCE_INVALID\x10,\x1a\x04\xa8E\x90\x03\x12\x1b\n" +
	"\x11SESSION_TOO_SHORT\x10-\x1a\x04\xa8E\x90\x03\x12\x1d\n" +
	"\x13ANTI_CHEAT_REJECTED\x102\x1a\x04\xa8E\xa6\x03\x12\"\n" +
	"\x18ANTI_CHEAT_MOCK_LOCATION\x103\x1a\x04\xa8E\xa6\x03\x12$\n" +
	"\x1aANTI_CHEAT_SPEED_VIOLATION\x104\x1a\x04\xa8E\xa6\x03\x12%\n" +
	"\x1bANTI_CHEAT_INTEGRITY_FAILED\x105\x1a\x04\xa8E\xa6\x03\x12&\n" +
	"\x1cANTI_CHEAT_GEOFENCE_MISMATCH\x106\x1a\x04\xa8E\xa6\x03\x12\"\n" +
	"\x18ANTI_CHEAT_DEVICE_SHARED\x107\x1a\x04\xa8E\xa6\x03\x12\x1f\n" +
	"\x15ANTI_CHEAT_CLOCK_SKEW\x108\x1a\x04\xa8E\xa6\x03\x12\x1d\n" +
	"\x13POINTS_INSUFFICIENT\x10<\x1a\x04\xa8E\x99\x03\x12\x18\n" +
	"\x0eGIFT_NOT_FOUND\x10=\x1a\x04\xa8E\x94\x03\x12\x1b\n" +
	"\x11GIFT_OUT_OF_STOCK\x10>\x1a\x04\xa8E\x99\x03\x12\x1c\n" +
	"\x12GIFT_NOT_AVAILABLE\x10?\x1a\x04\xa8E\x99\x03\x12%\n" +
	"\x1bGIFT_PER_USER_LIMIT_REACHED\x10@\x1a\x04\xa8E\x99\x03\x12\x1e\n" +
	"\x14REDEMPTION_NOT_FOUND\x10A\x1a\x04\xa8E\x94\x03\x12$\n" +
	"\x1aREDEMPTION_NOT_CANCELLABLE\x10B\x1a\x04\xa8E\x99\x03\x12'\n" +
	"\x1dREDEMPTION_EMAIL_NOT_VERIFIED\x10C\x1a\x04\xa8E\x93\x03\x12$\n" +
	"\x1aREDEMPTION_NOT_FULFILLABLE\x10D\x1a\x04\xa8E\x99\x03\x12#\n" +
	"\x19LEADERBOARD_NOT_AVAILABLE\x10F\x1a\x04\xa8E\xf7\x03\x12\"\n" +
	"\x18IMAGE_UPLOAD_UNAVAILABLE\x10P\x1a\x04\xa8E\xf7\x03\x12 \n" +
	"\x16IMAGE_TYPE_UNSUPPORTED\x10Q\x1a\x04\xa8E\x90\x03\x1a\x04\xa0E\xf4\x032\xda.\n" +
	"\aFitness\x12z\n" +
	"\fGetMyProfile\x12'.fitness.v1.request.GetMyProfileRequest\x1a).fitness.v1.response.GetMyProfileResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/fitness/me\x12\x86\x01\n" +
	"\x0fUpsertMyProfile\x12*.fitness.v1.request.UpsertMyProfileRequest\x1a,.fitness.v1.response.UpsertMyProfileResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/v1/fitness/me\x12|\n" +
	"\vListRegions\x12&.fitness.v1.request.ListRegionsRequest\x1a(.fitness.v1.response.ListRegionsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/fitness/regions\x12\x90\x01\n" +
	"\x10ListCompetitions\x12+.fitness.v1.request.ListCompetitionsRequest\x1a-.fitness.v1.response.ListCompetitionsResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/fitness/competitions\x12\x9b\x01\n" +
	"\x0eGetCompetition\x12).fitness.v1.request.GetCompetitionRequest\x1a+.fitness.v1.response.GetCompetitionResponse\"1\x82\xd3\xe4\x93\x02+\x12)/v1/fitness/competitions/{competition_id}\x12\xa6\x01\n" +
	"\x0fJoinCompetition\x12*.fitness.v1.request.JoinCompetitionRequest\x1a,.fitness.v1.response.JoinCompetitionResponse\"9\x82\xd3\xe4\x93\x023:\x01*\"./v1/fitness/competitions/{competition_id}:join\x12\xaa\x01\n" +
	"\x10LeaveCompetition\x12+.fitness.v1.request.LeaveCompetitionRequest\x1a-.fitness.v1.response.LeaveCompetitionResponse\":\x82\xd3\xe4\x93\x024:\x01*\"//v1/fitness/competitions/{competition_id}:leave\x12\x96\x01\n" +
	"\x11CreateCompetition\x12,.fitness.v1.request.CreateCompetitionRequest\x1a..fitness.v1.response.CreateCompetitionResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/fitness/competitions\x12\xc7\x01\n" +
	"\x16ListChallengeTemplates\x121.fitness.v1.request.ListChallengeTemplatesRequest\x1a3.fitness.v1.response.ListChallengeTemplatesResponse\"E\x82\xd3\xe4\x93\x02?\x12=/v1/fitness/competitions/{competition_id}/challenge-templates\x12\x9e\x01\n" +
	"\rGetDailyQuota\x12(.fitness.v1.request.GetDailyQuotaRequest\x1a*.fitness.v1.response.GetDailyQuotaResponse\"7\x82\xd3\xe4\x93\x021\x12//v1/fitness/competitions/{competition_id}/quota\x12\x8b\x01\n" +
	"\x0eStartChallenge\x12).fitness.v1.request.StartChallengeRequest\x1a+.fitness.v1.response.StartChallengeResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/fitness/challenges\x12\x8e\x01\n" +
	"\x10ListMyChallenges\x12+.fitness.v1.request.ListMyChallengesRequest\x1a-.fitness.v1.response.ListMyChallengesResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/fitness/challenges\x12\xa8\x01\n" +
	"\x10AbandonChallenge\x12+.fitness.v1.request.AbandonChallengeRequest\x1a-.fitness.v1.response.AbandonChallengeResponse\"8\x82\xd3\xe4\x93\x022:\x01*\"-/v1/fitness/challenges/{challenge_id}:abandon\x12\x94\x01\n" +
	"\x10StartWalkSession\x12+.fitness.v1.request.StartWalkSessionRequest\x1a-.fitness.v1.response.StartWalkSessionResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/fitness/walk-sessions\x12\xac\x01\n" +
	"\x11SubmitWalkSamples\x12,.fitness.v1.request.SubmitWalkSamplesRequest\x1a..fitness.v1.response.SubmitWalkSamplesResponse\"9\x82\xd3\xe4\x93\x023:\x01*\"./v1/fitness/walk-sessions/{session_id}/samples\x12\x9f\x01\n" +
	"\x0eEndWalkSession\x12).fitness.v1.request.EndWalkSessionRequest\x1a+.fitness.v1.response.EndWalkSessionResponse\"5\x82\xd3\xe4\x93\x02/:\x01*\"*/v1/fitness/walk-sessions/{session_id}:end\x12\x98\x01\n" +
	"\x0eGetWalkSession\x12).fitness.v1.request.GetWalkSessionRequest\x1a+.fitness.v1.response.GetWalkSessionResponse\".\x82\xd3\xe4\x93\x02(\x12&/v1/fitness/walk-sessions/{session_id}\x12\x97\x01\n" +
	"\x12ListMyWalkSessions\x12-.fitness.v1.request.ListMyWalkSessionsRequest\x1a/.fitness.v1.response.ListMyWalkSessionsResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/fitness/walk-sessions\x12z\n" +
	"\n" +
	"GetMyStats\x12%.fitness.v1.request.GetMyStatsRequest\x1a'.fitness.v1.response.GetMyStatsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/fitness/me/stats\x12\x89\x01\n" +
	"\x0eGetLeaderboard\x12).fitness.v1.request.GetLeaderboardRequest\x1a+.fitness.v1.response.GetLeaderboardResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/fitness/leaderboard\x12\x9d\x01\n" +
	"\x12GetRegionStandings\x12-.fitness.v1.request.GetRegionStandingsRequest\x1a/.fitness.v1.response.GetRegionStandingsResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/fitness/leaderboard/regions\x12\x93\x01\n" +
	"\x12GetMyPointsBalance\x12-.fitness.v1.request.GetMyPointsBalanceRequest\x1a/.fitness.v1.response.GetMyPointsBalanceResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/fitness/me/points\x12\x9a\x01\n" +
	"\x12ListMyPointsLedger\x12-.fitness.v1.request.ListMyPointsLedgerRequest\x1a/.fitness.v1.response.ListMyPointsLedgerResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/fitness/me/points/ledger\x12t\n" +
	"\tListGifts\x12$.fitness.v1.request.ListGiftsRequest\x1a&.fitness.v1.response.ListGiftsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/fitness/gifts\x12x\n" +
	"\aGetGift\x12\".fitness.v1.request.GetGiftRequest\x1a$.fitness.v1.response.GetGiftResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/fitness/gifts/{gift_id}\x12\x8b\x01\n" +
	"\n" +
	"RedeemGift\x12%.fitness.v1.request.RedeemGiftRequest\x1a'.fitness.v1.response.RedeemGiftResponse\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/fitness/gifts/{gift_id}:redeem\x12\x95\x01\n" +
	"\x11ListMyRedemptions\x12,.fitness.v1.request.ListMyRedemptionsRequest\x1a..fitness.v1.response.ListMyRedemptionsResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/fitness/me/redemptions\x12\xac\x01\n" +
	"\x10CancelRedemption\x12+.fitness.v1.request.CancelRedemptionRequest\x1a-.fitness.v1.response.CancelRedemptionResponse\"<\x82\xd3\xe4\x93\x026:\x01*\"1/v1/fitness/me/redemptions/{redemption_id}:cancel\x12\xad\x01\n" +
	"\x11UpdateCompetition\x12,.fitness.v1.request.UpdateCompetitionRequest\x1a..fitness.v1.response.UpdateCompetitionResponse\":\x82\xd3\xe4\x93\x024:\x01*2//v1/fitness/admin/competitions/{competition_id}\x12\xb4\x01\n" +
	"\x11CancelCompetition\x12,.fitness.v1.request.CancelCompetitionRequest\x1a..fitness.v1.response.CancelCompetitionResponse\"A\x82\xd3\xe4\x93\x02;:\x01*\"6/v1/fitness/admin/competitions/{competition_id}:cancel\x12\xd3\x01\n" +
	"\x17CreateChallengeTemplate\x122.fitness.v1.request.CreateChallengeTemplateRequest\x1a4.fitness.v1.response.CreateChallengeTemplateResponse\"N\x82\xd3\xe4\x93\x02H:\x01*\"C/v1/fitness/admin/competitions/{competition_id}/challenge-templates\x12\xcb\x01\n" +
	"\x1cCreateCompetitionImageUpload\x127.fitness.v1.request.CreateCompetitionImageUploadRequest\x1a9.fitness.v1.response.CreateCompetitionImageUploadResponse\"7\x82\xd3\xe4\x93\x021:\x01*\",/v1/fitness/admin/competitions/image-uploads\x12\x80\x01\n" +
	"\n" +
	"CreateGift\x12%.fitness.v1.request.CreateGiftRequest\x1a'.fitness.v1.response.CreateGiftResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/fitness/admin/gifts\x12\x8a\x01\n" +
	"\n" +
	"UpdateGift\x12%.fitness.v1.request.UpdateGiftRequest\x1a'.fitness.v1.response.UpdateGiftResponse\",\x82\xd3\xe4\x93\x02&:\x01*2!/v1/fitness/admin/gifts/{gift_id}\x12\xaf\x01\n" +
	"\x10FulfilRedemption\x12+.fitness.v1.request.FulfilRedemptionRequest\x1a-.fitness.v1.response.FulfilRedemptionResponse\"?\x82\xd3\xe4\x93\x029:\x01*\"4/v1/fitness/admin/redemptions/{redemption_id}:fulfil\x12\x9b\x01\n" +
	"\x12ListAllRedemptions\x12-.fitness.v1.request.ListAllRedemptionsRequest\x1a/.fitness.v1.response.ListAllRedemptionsResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/fitness/admin/redemptions\x12\xa3\x01\n" +
	"\x13ListFlaggedSessions\x12..fitness.v1.request.ListFlaggedSessionsRequest\x1a0.fitness.v1.response.ListFlaggedSessionsResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/fitness/admin/flagged-sessions\x12\xa8\x01\n" +
	"\rReviewSession\x12(.fitness.v1.request.ReviewSessionRequest\x1a*.fitness.v1.response.ReviewSessionResponse\"A\x82\xd3\xe4\x93\x02;:\x01*\"6/v1/fitness/admin/flagged-sessions/{session_id}:reviewB*Z(github.com/arm-1234/protos/fitness/v1;v1b\x06proto3"

var (
	file_fitness_v1_fitness_proto_rawDescOnce sync.Once
	file_fitness_v1_fitness_proto_rawDescData []byte
)

func file_fitness_v1_fitness_proto_rawDescGZIP() []byte {
	file_fitness_v1_fitness_proto_rawDescOnce.Do(func() {
		file_fitness_v1_fitness_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fitness_v1_fitness_proto_rawDesc), len(file_fitness_v1_fitness_proto_rawDesc)))
	})
	return file_fitness_v1_fitness_proto_rawDescData
}

var file_fitness_v1_fitness_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_fitness_v1_fitness_proto_goTypes = []any{
	(ErrorReason)(0),                                      // 0: fitness.v1.ErrorReason
	(*request.GetMyProfileRequest)(nil),                   // 1: fitness.v1.request.GetMyProfileRequest
	(*request.UpsertMyProfileRequest)(nil),                // 2: fitness.v1.request.UpsertMyProfileRequest
	(*request.ListRegionsRequest)(nil),                    // 3: fitness.v1.request.ListRegionsRequest
	(*request.ListCompetitionsRequest)(nil),               // 4: fitness.v1.request.ListCompetitionsRequest
	(*request.GetCompetitionRequest)(nil),                 // 5: fitness.v1.request.GetCompetitionRequest
	(*request.JoinCompetitionRequest)(nil),                // 6: fitness.v1.request.JoinCompetitionRequest
	(*request.LeaveCompetitionRequest)(nil),               // 7: fitness.v1.request.LeaveCompetitionRequest
	(*request.CreateCompetitionRequest)(nil),              // 8: fitness.v1.request.CreateCompetitionRequest
	(*request.ListChallengeTemplatesRequest)(nil),         // 9: fitness.v1.request.ListChallengeTemplatesRequest
	(*request.GetDailyQuotaRequest)(nil),                  // 10: fitness.v1.request.GetDailyQuotaRequest
	(*request.StartChallengeRequest)(nil),                 // 11: fitness.v1.request.StartChallengeRequest
	(*request.ListMyChallengesRequest)(nil),               // 12: fitness.v1.request.ListMyChallengesRequest
	(*request.AbandonChallengeRequest)(nil),               // 13: fitness.v1.request.AbandonChallengeRequest
	(*request.StartWalkSessionRequest)(nil),               // 14: fitness.v1.request.StartWalkSessionRequest
	(*request.SubmitWalkSamplesRequest)(nil),              // 15: fitness.v1.request.SubmitWalkSamplesRequest
	(*request.EndWalkSessionRequest)(nil),                 // 16: fitness.v1.request.EndWalkSessionRequest
	(*request.GetWalkSessionRequest)(nil),                 // 17: fitness.v1.request.GetWalkSessionRequest
	(*request.ListMyWalkSessionsRequest)(nil),             // 18: fitness.v1.request.ListMyWalkSessionsRequest
	(*request.GetMyStatsRequest)(nil),                     // 19: fitness.v1.request.GetMyStatsRequest
	(*request.GetLeaderboardRequest)(nil),                 // 20: fitness.v1.request.GetLeaderboardRequest
	(*request.GetRegionStandingsRequest)(nil),             // 21: fitness.v1.request.GetRegionStandingsRequest
	(*request.GetMyPointsBalanceRequest)(nil),             // 22: fitness.v1.request.GetMyPointsBalanceRequest
	(*request.ListMyPointsLedgerRequest)(nil),             // 23: fitness.v1.request.ListMyPointsLedgerRequest
	(*request.ListGiftsRequest)(nil),                      // 24: fitness.v1.request.ListGiftsRequest
	(*request.GetGiftRequest)(nil),                        // 25: fitness.v1.request.GetGiftRequest
	(*request.RedeemGiftRequest)(nil),                     // 26: fitness.v1.request.RedeemGiftRequest
	(*request.ListMyRedemptionsRequest)(nil),              // 27: fitness.v1.request.ListMyRedemptionsRequest
	(*request.CancelRedemptionRequest)(nil),               // 28: fitness.v1.request.CancelRedemptionRequest
	(*request.UpdateCompetitionRequest)(nil),              // 29: fitness.v1.request.UpdateCompetitionRequest
	(*request.CancelCompetitionRequest)(nil),              // 30: fitness.v1.request.CancelCompetitionRequest
	(*request.CreateChallengeTemplateRequest)(nil),        // 31: fitness.v1.request.CreateChallengeTemplateRequest
	(*request.CreateCompetitionImageUploadRequest)(nil),   // 32: fitness.v1.request.CreateCompetitionImageUploadRequest
	(*request.CreateGiftRequest)(nil),                     // 33: fitness.v1.request.CreateGiftRequest
	(*request.UpdateGiftRequest)(nil),                     // 34: fitness.v1.request.UpdateGiftRequest
	(*request.FulfilRedemptionRequest)(nil),               // 35: fitness.v1.request.FulfilRedemptionRequest
	(*request.ListAllRedemptionsRequest)(nil),             // 36: fitness.v1.request.ListAllRedemptionsRequest
	(*request.ListFlaggedSessionsRequest)(nil),            // 37: fitness.v1.request.ListFlaggedSessionsRequest
	(*request.ReviewSessionRequest)(nil),                  // 38: fitness.v1.request.ReviewSessionRequest
	(*response.GetMyProfileResponse)(nil),                 // 39: fitness.v1.response.GetMyProfileResponse
	(*response.UpsertMyProfileResponse)(nil),              // 40: fitness.v1.response.UpsertMyProfileResponse
	(*response.ListRegionsResponse)(nil),                  // 41: fitness.v1.response.ListRegionsResponse
	(*response.ListCompetitionsResponse)(nil),             // 42: fitness.v1.response.ListCompetitionsResponse
	(*response.GetCompetitionResponse)(nil),               // 43: fitness.v1.response.GetCompetitionResponse
	(*response.JoinCompetitionResponse)(nil),              // 44: fitness.v1.response.JoinCompetitionResponse
	(*response.LeaveCompetitionResponse)(nil),             // 45: fitness.v1.response.LeaveCompetitionResponse
	(*response.CreateCompetitionResponse)(nil),            // 46: fitness.v1.response.CreateCompetitionResponse
	(*response.ListChallengeTemplatesResponse)(nil),       // 47: fitness.v1.response.ListChallengeTemplatesResponse
	(*response.GetDailyQuotaResponse)(nil),                // 48: fitness.v1.response.GetDailyQuotaResponse
	(*response.StartChallengeResponse)(nil),               // 49: fitness.v1.response.StartChallengeResponse
	(*response.ListMyChallengesResponse)(nil),             // 50: fitness.v1.response.ListMyChallengesResponse
	(*response.AbandonChallengeResponse)(nil),             // 51: fitness.v1.response.AbandonChallengeResponse
	(*response.StartWalkSessionResponse)(nil),             // 52: fitness.v1.response.StartWalkSessionResponse
	(*response.SubmitWalkSamplesResponse)(nil),            // 53: fitness.v1.response.SubmitWalkSamplesResponse
	(*response.EndWalkSessionResponse)(nil),               // 54: fitness.v1.response.EndWalkSessionResponse
	(*response.GetWalkSessionResponse)(nil),               // 55: fitness.v1.response.GetWalkSessionResponse
	(*response.ListMyWalkSessionsResponse)(nil),           // 56: fitness.v1.response.ListMyWalkSessionsResponse
	(*response.GetMyStatsResponse)(nil),                   // 57: fitness.v1.response.GetMyStatsResponse
	(*response.GetLeaderboardResponse)(nil),               // 58: fitness.v1.response.GetLeaderboardResponse
	(*response.GetRegionStandingsResponse)(nil),           // 59: fitness.v1.response.GetRegionStandingsResponse
	(*response.GetMyPointsBalanceResponse)(nil),           // 60: fitness.v1.response.GetMyPointsBalanceResponse
	(*response.ListMyPointsLedgerResponse)(nil),           // 61: fitness.v1.response.ListMyPointsLedgerResponse
	(*response.ListGiftsResponse)(nil),                    // 62: fitness.v1.response.ListGiftsResponse
	(*response.GetGiftResponse)(nil),                      // 63: fitness.v1.response.GetGiftResponse
	(*response.RedeemGiftResponse)(nil),                   // 64: fitness.v1.response.RedeemGiftResponse
	(*response.ListMyRedemptionsResponse)(nil),            // 65: fitness.v1.response.ListMyRedemptionsResponse
	(*response.CancelRedemptionResponse)(nil),             // 66: fitness.v1.response.CancelRedemptionResponse
	(*response.UpdateCompetitionResponse)(nil),            // 67: fitness.v1.response.UpdateCompetitionResponse
	(*response.CancelCompetitionResponse)(nil),            // 68: fitness.v1.response.CancelCompetitionResponse
	(*response.CreateChallengeTemplateResponse)(nil),      // 69: fitness.v1.response.CreateChallengeTemplateResponse
	(*response.CreateCompetitionImageUploadResponse)(nil), // 70: fitness.v1.response.CreateCompetitionImageUploadResponse
	(*response.CreateGiftResponse)(nil),                   // 71: fitness.v1.response.CreateGiftResponse
	(*response.UpdateGiftResponse)(nil),                   // 72: fitness.v1.response.UpdateGiftResponse
	(*response.FulfilRedemptionResponse)(nil),             // 73: fitness.v1.response.FulfilRedemptionResponse
	(*response.ListAllRedemptionsResponse)(nil),           // 74: fitness.v1.response.ListAllRedemptionsResponse
	(*response.ListFlaggedSessionsResponse)(nil),          // 75: fitness.v1.response.ListFlaggedSessionsResponse
	(*response.ReviewSessionResponse)(nil),                // 76: fitness.v1.response.ReviewSessionResponse
}
var file_fitness_v1_fitness_proto_depIdxs = []int32{
	1,  // 0: fitness.v1.Fitness.GetMyProfile:input_type -> fitness.v1.request.GetMyProfileRequest
	2,  // 1: fitness.v1.Fitness.UpsertMyProfile:input_type -> fitness.v1.request.UpsertMyProfileRequest
	3,  // 2: fitness.v1.Fitness.ListRegions:input_type -> fitness.v1.request.ListRegionsRequest
	4,  // 3: fitness.v1.Fitness.ListCompetitions:input_type -> fitness.v1.request.ListCompetitionsRequest
	5,  // 4: fitness.v1.Fitness.GetCompetition:input_type -> fitness.v1.request.GetCompetitionRequest
	6,  // 5: fitness.v1.Fitness.JoinCompetition:input_type -> fitness.v1.request.JoinCompetitionRequest
	7,  // 6: fitness.v1.Fitness.LeaveCompetition:input_type -> fitness.v1.request.LeaveCompetitionRequest
	8,  // 7: fitness.v1.Fitness.CreateCompetition:input_type -> fitness.v1.request.CreateCompetitionRequest
	9,  // 8: fitness.v1.Fitness.ListChallengeTemplates:input_type -> fitness.v1.request.ListChallengeTemplatesRequest
	10, // 9: fitness.v1.Fitness.GetDailyQuota:input_type -> fitness.v1.request.GetDailyQuotaRequest
	11, // 10: fitness.v1.Fitness.StartChallenge:input_type -> fitness.v1.request.StartChallengeRequest
	12, // 11: fitness.v1.Fitness.ListMyChallenges:input_type -> fitness.v1.request.ListMyChallengesRequest
	13, // 12: fitness.v1.Fitness.AbandonChallenge:input_type -> fitness.v1.request.AbandonChallengeRequest
	14, // 13: fitness.v1.Fitness.StartWalkSession:input_type -> fitness.v1.request.StartWalkSessionRequest
	15, // 14: fitness.v1.Fitness.SubmitWalkSamples:input_type -> fitness.v1.request.SubmitWalkSamplesRequest
	16, // 15: fitness.v1.Fitness.EndWalkSession:input_type -> fitness.v1.request.EndWalkSessionRequest
	17, // 16: fitness.v1.Fitness.GetWalkSession:input_type -> fitness.v1.request.GetWalkSessionRequest
	18, // 17: fitness.v1.Fitness.ListMyWalkSessions:input_type -> fitness.v1.request.ListMyWalkSessionsRequest
	19, // 18: fitness.v1.Fitness.GetMyStats:input_type -> fitness.v1.request.GetMyStatsRequest
	20, // 19: fitness.v1.Fitness.GetLeaderboard:input_type -> fitness.v1.request.GetLeaderboardRequest
	21, // 20: fitness.v1.Fitness.GetRegionStandings:input_type -> fitness.v1.request.GetRegionStandingsRequest
	22, // 21: fitness.v1.Fitness.GetMyPointsBalance:input_type -> fitness.v1.request.GetMyPointsBalanceRequest
	23, // 22: fitness.v1.Fitness.ListMyPointsLedger:input_type -> fitness.v1.request.ListMyPointsLedgerRequest
	24, // 23: fitness.v1.Fitness.ListGifts:input_type -> fitness.v1.request.ListGiftsRequest
	25, // 24: fitness.v1.Fitness.GetGift:input_type -> fitness.v1.request.GetGiftRequest
	26, // 25: fitness.v1.Fitness.RedeemGift:input_type -> fitness.v1.request.RedeemGiftRequest
	27, // 26: fitness.v1.Fitness.ListMyRedemptions:input_type -> fitness.v1.request.ListMyRedemptionsRequest
	28, // 27: fitness.v1.Fitness.CancelRedemption:input_type -> fitness.v1.request.CancelRedemptionRequest
	29, // 28: fitness.v1.Fitness.UpdateCompetition:input_type -> fitness.v1.request.UpdateCompetitionRequest
	30, // 29: fitness.v1.Fitness.CancelCompetition:input_type -> fitness.v1.request.CancelCompetitionRequest
	31, // 30: fitness.v1.Fitness.CreateChallengeTemplate:input_type -> fitness.v1.request.CreateChallengeTemplateRequest
	32, // 31: fitness.v1.Fitness.CreateCompetitionImageUpload:input_type -> fitness.v1.request.CreateCompetitionImageUploadRequest
	33, // 32: fitness.v1.Fitness.CreateGift:input_type -> fitness.v1.request.CreateGiftRequest
	34, // 33: fitness.v1.Fitness.UpdateGift:input_type -> fitness.v1.request.UpdateGiftRequest
	35, // 34: fitness.v1.Fitness.FulfilRedemption:input_type -> fitness.v1.request.FulfilRedemptionRequest
	36, // 35: fitness.v1.Fitness.ListAllRedemptions:input_type -> fitness.v1.request.ListAllRedemptionsRequest
	37, // 36: fitness.v1.Fitness.ListFlaggedSessions:input_type -> fitness.v1.request.ListFlaggedSessionsRequest
	38, // 37: fitness.v1.Fitness.ReviewSession:input_type -> fitness.v1.request.ReviewSessionRequest
	39, // 38: fitness.v1.Fitness.GetMyProfile:output_type -> fitness.v1.response.GetMyProfileResponse
	40, // 39: fitness.v1.Fitness.UpsertMyProfile:output_type -> fitness.v1.response.UpsertMyProfileResponse
	41, // 40: fitness.v1.Fitness.ListRegions:output_type -> fitness.v1.response.ListRegionsResponse
	42, // 41: fitness.v1.Fitness.ListCompetitions:output_type -> fitness.v1.response.ListCompetitionsResponse
	43, // 42: fitness.v1.Fitness.GetCompetition:output_type -> fitness.v1.response.GetCompetitionResponse
	44, // 43: fitness.v1.Fitness.JoinCompetition:output_type -> fitness.v1.response.JoinCompetitionResponse
	45, // 44: fitness.v1.Fitness.LeaveCompetition:output_type -> fitness.v1.response.LeaveCompetitionResponse
	46, // 45: fitness.v1.Fitness.CreateCompetition:output_type -> fitness.v1.response.CreateCompetitionResponse
	47, // 46: fitness.v1.Fitness.ListChallengeTemplates:output_type -> fitness.v1.response.ListChallengeTemplatesResponse
	48, // 47: fitness.v1.Fitness.GetDailyQuota:output_type -> fitness.v1.response.GetDailyQuotaResponse
	49, // 48: fitness.v1.Fitness.StartChallenge:output_type -> fitness.v1.response.StartChallengeResponse
	50, // 49: fitness.v1.Fitness.ListMyChallenges:output_type -> fitness.v1.response.ListMyChallengesResponse
	51, // 50: fitness.v1.Fitness.AbandonChallenge:output_type -> fitness.v1.response.AbandonChallengeResponse
	52, // 51: fitness.v1.Fitness.StartWalkSession:output_type -> fitness.v1.response.StartWalkSessionResponse
	53, // 52: fitness.v1.Fitness.SubmitWalkSamples:output_type -> fitness.v1.response.SubmitWalkSamplesResponse
	54, // 53: fitness.v1.Fitness.EndWalkSession:output_type -> fitness.v1.response.EndWalkSessionResponse
	55, // 54: fitness.v1.Fitness.GetWalkSession:output_type -> fitness.v1.response.GetWalkSessionResponse
	56, // 55: fitness.v1.Fitness.ListMyWalkSessions:output_type -> fitness.v1.response.ListMyWalkSessionsResponse
	57, // 56: fitness.v1.Fitness.GetMyStats:output_type -> fitness.v1.response.GetMyStatsResponse
	58, // 57: fitness.v1.Fitness.GetLeaderboard:output_type -> fitness.v1.response.GetLeaderboardResponse
	59, // 58: fitness.v1.Fitness.GetRegionStandings:output_type -> fitness.v1.response.GetRegionStandingsResponse
	60, // 59: fitness.v1.Fitness.GetMyPointsBalance:output_type -> fitness.v1.response.GetMyPointsBalanceResponse
	61, // 60: fitness.v1.Fitness.ListMyPointsLedger:output_type -> fitness.v1.response.ListMyPointsLedgerResponse
	62, // 61: fitness.v1.Fitness.ListGifts:output_type -> fitness.v1.response.ListGiftsResponse
	63, // 62: fitness.v1.Fitness.GetGift:output_type -> fitness.v1.response.GetGiftResponse
	64, // 63: fitness.v1.Fitness.RedeemGift:output_type -> fitness.v1.response.RedeemGiftResponse
	65, // 64: fitness.v1.Fitness.ListMyRedemptions:output_type -> fitness.v1.response.ListMyRedemptionsResponse
	66, // 65: fitness.v1.Fitness.CancelRedemption:output_type -> fitness.v1.response.CancelRedemptionResponse
	67, // 66: fitness.v1.Fitness.UpdateCompetition:output_type -> fitness.v1.response.UpdateCompetitionResponse
	68, // 67: fitness.v1.Fitness.CancelCompetition:output_type -> fitness.v1.response.CancelCompetitionResponse
	69, // 68: fitness.v1.Fitness.CreateChallengeTemplate:output_type -> fitness.v1.response.CreateChallengeTemplateResponse
	70, // 69: fitness.v1.Fitness.CreateCompetitionImageUpload:output_type -> fitness.v1.response.CreateCompetitionImageUploadResponse
	71, // 70: fitness.v1.Fitness.CreateGift:output_type -> fitness.v1.response.CreateGiftResponse
	72, // 71: fitness.v1.Fitness.UpdateGift:output_type -> fitness.v1.response.UpdateGiftResponse
	73, // 72: fitness.v1.Fitness.FulfilRedemption:output_type -> fitness.v1.response.FulfilRedemptionResponse
	74, // 73: fitness.v1.Fitness.ListAllRedemptions:output_type -> fitness.v1.response.ListAllRedemptionsResponse
	75, // 74: fitness.v1.Fitness.ListFlaggedSessions:output_type -> fitness.v1.response.ListFlaggedSessionsResponse
	76, // 75: fitness.v1.Fitness.ReviewSession:output_type -> fitness.v1.response.ReviewSessionResponse
	38, // [38:76] is the sub-list for method output_type
	0,  // [0:38] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_fitness_v1_fitness_proto_init() }
func file_fitness_v1_fitness_proto_init() {
	if File_fitness_v1_fitness_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fitness_v1_fitness_proto_rawDesc), len(file_fitness_v1_fitness_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fitness_v1_fitness_proto_goTypes,
		DependencyIndexes: file_fitness_v1_fitness_proto_depIdxs,
		EnumInfos:         file_fitness_v1_fitness_proto_enumTypes,
	}.Build()
	File_fitness_v1_fitness_proto = out.File
	file_fitness_v1_fitness_proto_goTypes = nil
	file_fitness_v1_fitness_proto_depIdxs = nil
}
