// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsFitnessUnspecified(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_FITNESS_UNSPECIFIED.String() && e.Code == 500
}

func ErrorFitnessUnspecified(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_FITNESS_UNSPECIFIED.String(), fmt.Sprintf(format, args...))
}

func IsFitnessInvalidRequest(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_FITNESS_INVALID_REQUEST.String() && e.Code == 400
}

func ErrorFitnessInvalidRequest(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_FITNESS_INVALID_REQUEST.String(), fmt.Sprintf(format, args...))
}

func IsFitnessForbidden(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_FITNESS_FORBIDDEN.String() && e.Code == 403
}

func ErrorFitnessForbidden(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ErrorReason_FITNESS_FORBIDDEN.String(), fmt.Sprintf(format, args...))
}

// Caller is authenticated but is not a USER_TYPE_ADMIN.
func IsFitnessAdminRequired(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_FITNESS_ADMIN_REQUIRED.String() && e.Code == 403
}

// Caller is authenticated but is not a USER_TYPE_ADMIN.
func ErrorFitnessAdminRequired(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ErrorReason_FITNESS_ADMIN_REQUIRED.String(), fmt.Sprintf(format, args...))
}

func IsFitnessUnauthenticated(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_FITNESS_UNAUTHENTICATED.String() && e.Code == 401
}

func ErrorFitnessUnauthenticated(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_FITNESS_UNAUTHENTICATED.String(), fmt.Sprintf(format, args...))
}

func IsProfileNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PROFILE_NOT_FOUND.String() && e.Code == 404
}

func ErrorProfileNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_PROFILE_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

// Home region is locked for a cooldown so users cannot hop to a weak district.
func IsProfileRegionLocked(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_PROFILE_REGION_LOCKED.String() && e.Code == 409
}

// Home region is locked for a cooldown so users cannot hop to a weak district.
func ErrorProfileRegionLocked(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_PROFILE_REGION_LOCKED.String(), fmt.Sprintf(format, args...))
}

func IsRegionNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_REGION_NOT_FOUND.String() && e.Code == 404
}

func ErrorRegionNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_REGION_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

// Barred from earning after upheld fraud findings.
func IsUserSuspended(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_USER_SUSPENDED.String() && e.Code == 403
}

// Barred from earning after upheld fraud findings.
func ErrorUserSuspended(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ErrorReason_USER_SUSPENDED.String(), fmt.Sprintf(format, args...))
}

func IsCompetitionNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_COMPETITION_NOT_FOUND.String() && e.Code == 404
}

func ErrorCompetitionNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_COMPETITION_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsCompetitionNotActive(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_COMPETITION_NOT_ACTIVE.String() && e.Code == 409
}

func ErrorCompetitionNotActive(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_COMPETITION_NOT_ACTIVE.String(), fmt.Sprintf(format, args...))
}

func IsCompetitionAlreadyJoined(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_COMPETITION_ALREADY_JOINED.String() && e.Code == 409
}

func ErrorCompetitionAlreadyJoined(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_COMPETITION_ALREADY_JOINED.String(), fmt.Sprintf(format, args...))
}

func IsCompetitionNotJoined(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_COMPETITION_NOT_JOINED.String() && e.Code == 403
}

func ErrorCompetitionNotJoined(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ErrorReason_COMPETITION_NOT_JOINED.String(), fmt.Sprintf(format, args...))
}

// Home region does not match the competition's scope.
func IsCompetitionRegionIneligible(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_COMPETITION_REGION_INELIGIBLE.String() && e.Code == 403
}

// Home region does not match the competition's scope.
func ErrorCompetitionRegionIneligible(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ErrorReason_COMPETITION_REGION_INELIGIBLE.String(), fmt.Sprintf(format, args...))
}

func IsChallengeNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CHALLENGE_NOT_FOUND.String() && e.Code == 404
}

func ErrorChallengeNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_CHALLENGE_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsChallengeTemplateNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CHALLENGE_TEMPLATE_NOT_FOUND.String() && e.Code == 404
}

func ErrorChallengeTemplateNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_CHALLENGE_TEMPLATE_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsChallengeDailyLimitReached(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CHALLENGE_DAILY_LIMIT_REACHED.String() && e.Code == 429
}

func ErrorChallengeDailyLimitReached(format string, args ...interface{}) *errors.Error {
	return errors.New(429, ErrorReason_CHALLENGE_DAILY_LIMIT_REACHED.String(), fmt.Sprintf(format, args...))
}

func IsChallengeCooldownActive(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CHALLENGE_COOLDOWN_ACTIVE.String() && e.Code == 429
}

func ErrorChallengeCooldownActive(format string, args ...interface{}) *errors.Error {
	return errors.New(429, ErrorReason_CHALLENGE_COOLDOWN_ACTIVE.String(), fmt.Sprintf(format, args...))
}

func IsChallengeAlreadyInProgress(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CHALLENGE_ALREADY_IN_PROGRESS.String() && e.Code == 409
}

func ErrorChallengeAlreadyInProgress(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_CHALLENGE_ALREADY_IN_PROGRESS.String(), fmt.Sprintf(format, args...))
}

func IsChallengeExpired(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CHALLENGE_EXPIRED.String() && e.Code == 409
}

func ErrorChallengeExpired(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_CHALLENGE_EXPIRED.String(), fmt.Sprintf(format, args...))
}

func IsChallengeNotInProgress(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_CHALLENGE_NOT_IN_PROGRESS.String() && e.Code == 409
}

func ErrorChallengeNotInProgress(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_CHALLENGE_NOT_IN_PROGRESS.String(), fmt.Sprintf(format, args...))
}

func IsDailyStepCapReached(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DAILY_STEP_CAP_REACHED.String() && e.Code == 429
}

func ErrorDailyStepCapReached(format string, args ...interface{}) *errors.Error {
	return errors.New(429, ErrorReason_DAILY_STEP_CAP_REACHED.String(), fmt.Sprintf(format, args...))
}

func IsDailyPointsCapReached(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DAILY_POINTS_CAP_REACHED.String() && e.Code == 429
}

func ErrorDailyPointsCapReached(format string, args ...interface{}) *errors.Error {
	return errors.New(429, ErrorReason_DAILY_POINTS_CAP_REACHED.String(), fmt.Sprintf(format, args...))
}

func IsSessionNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SESSION_NOT_FOUND.String() && e.Code == 404
}

func ErrorSessionNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_SESSION_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsSessionNotActive(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SESSION_NOT_ACTIVE.String() && e.Code == 409
}

func ErrorSessionNotActive(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_SESSION_NOT_ACTIVE.String(), fmt.Sprintf(format, args...))
}

func IsSessionAlreadyFinalized(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SESSION_ALREADY_FINALIZED.String() && e.Code == 409
}

func ErrorSessionAlreadyFinalized(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_SESSION_ALREADY_FINALIZED.String(), fmt.Sprintf(format, args...))
}

// Another session is still open for this user.
func IsSessionAlreadyActive(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SESSION_ALREADY_ACTIVE.String() && e.Code == 409
}

// Another session is still open for this user.
func ErrorSessionAlreadyActive(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_SESSION_ALREADY_ACTIVE.String(), fmt.Sprintf(format, args...))
}

func IsSessionSampleSequenceInvalid(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SESSION_SAMPLE_SEQUENCE_INVALID.String() && e.Code == 400
}

func ErrorSessionSampleSequenceInvalid(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_SESSION_SAMPLE_SEQUENCE_INVALID.String(), fmt.Sprintf(format, args...))
}

func IsSessionTooShort(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SESSION_TOO_SHORT.String() && e.Code == 400
}

func ErrorSessionTooShort(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_SESSION_TOO_SHORT.String(), fmt.Sprintf(format, args...))
}

// Anti-cheat rejections, split so the app can explain what went wrong.
func IsAntiCheatRejected(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ANTI_CHEAT_REJECTED.String() && e.Code == 422
}

// Anti-cheat rejections, split so the app can explain what went wrong.
func ErrorAntiCheatRejected(format string, args ...interface{}) *errors.Error {
	return errors.New(422, ErrorReason_ANTI_CHEAT_REJECTED.String(), fmt.Sprintf(format, args...))
}

func IsAntiCheatMockLocation(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ANTI_CHEAT_MOCK_LOCATION.String() && e.Code == 422
}

func ErrorAntiCheatMockLocation(format string, args ...interface{}) *errors.Error {
	return errors.New(422, ErrorReason_ANTI_CHEAT_MOCK_LOCATION.String(), fmt.Sprintf(format, args...))
}

func IsAntiCheatSpeedViolation(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ANTI_CHEAT_SPEED_VIOLATION.String() && e.Code == 422
}

func ErrorAntiCheatSpeedViolation(format string, args ...interface{}) *errors.Error {
	return errors.New(422, ErrorReason_ANTI_CHEAT_SPEED_VIOLATION.String(), fmt.Sprintf(format, args...))
}

func IsAntiCheatIntegrityFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ANTI_CHEAT_INTEGRITY_FAILED.String() && e.Code == 422
}

func ErrorAntiCheatIntegrityFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(422, ErrorReason_ANTI_CHEAT_INTEGRITY_FAILED.String(), fmt.Sprintf(format, args...))
}

func IsAntiCheatGeofenceMismatch(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ANTI_CHEAT_GEOFENCE_MISMATCH.String() && e.Code == 422
}

func ErrorAntiCheatGeofenceMismatch(format string, args ...interface{}) *errors.Error {
	return errors.New(422, ErrorReason_ANTI_CHEAT_GEOFENCE_MISMATCH.String(), fmt.Sprintf(format, args...))
}

func IsAntiCheatDeviceShared(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ANTI_CHEAT_DEVICE_SHARED.String() && e.Code == 422
}

func ErrorAntiCheatDeviceShared(format string, args ...interface{}) *errors.Error {
	return errors.New(422, ErrorReason_ANTI_CHEAT_DEVICE_SHARED.String(), fmt.Sprintf(format, args...))
}

func IsAntiCheatClockSkew(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ANTI_CHEAT_CLOCK_SKEW.String() && e.Code == 422
}

func ErrorAntiCheatClockSkew(format string, args ...interface{}) *errors.Error {
	return errors.New(422, ErrorReason_ANTI_CHEAT_CLOCK_SKEW.String(), fmt.Sprintf(format, args...))
}

func IsPointsInsufficient(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_POINTS_INSUFFICIENT.String() && e.Code == 409
}

func ErrorPointsInsufficient(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_POINTS_INSUFFICIENT.String(), fmt.Sprintf(format, args...))
}

func IsGiftNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_GIFT_NOT_FOUND.String() && e.Code == 404
}

func ErrorGiftNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_GIFT_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsGiftOutOfStock(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_GIFT_OUT_OF_STOCK.String() && e.Code == 409
}

func ErrorGiftOutOfStock(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_GIFT_OUT_OF_STOCK.String(), fmt.Sprintf(format, args...))
}

func IsGiftNotAvailable(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_GIFT_NOT_AVAILABLE.String() && e.Code == 409
}

func ErrorGiftNotAvailable(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_GIFT_NOT_AVAILABLE.String(), fmt.Sprintf(format, args...))
}

func IsGiftPerUserLimitReached(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_GIFT_PER_USER_LIMIT_REACHED.String() && e.Code == 409
}

func ErrorGiftPerUserLimitReached(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_GIFT_PER_USER_LIMIT_REACHED.String(), fmt.Sprintf(format, args...))
}

func IsRedemptionNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_REDEMPTION_NOT_FOUND.String() && e.Code == 404
}

func ErrorRedemptionNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_REDEMPTION_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsRedemptionNotCancellable(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_REDEMPTION_NOT_CANCELLABLE.String() && e.Code == 409
}

func ErrorRedemptionNotCancellable(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_REDEMPTION_NOT_CANCELLABLE.String(), fmt.Sprintf(format, args...))
}

// Redeeming requires a verified email, so throwaway addresses cannot farm gifts.
func IsRedemptionEmailNotVerified(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_REDEMPTION_EMAIL_NOT_VERIFIED.String() && e.Code == 403
}

// Redeeming requires a verified email, so throwaway addresses cannot farm gifts.
func ErrorRedemptionEmailNotVerified(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ErrorReason_REDEMPTION_EMAIL_NOT_VERIFIED.String(), fmt.Sprintf(format, args...))
}

func IsRedemptionNotFulfillable(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_REDEMPTION_NOT_FULFILLABLE.String() && e.Code == 409
}

func ErrorRedemptionNotFulfillable(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_REDEMPTION_NOT_FULFILLABLE.String(), fmt.Sprintf(format, args...))
}

func IsLeaderboardNotAvailable(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_LEADERBOARD_NOT_AVAILABLE.String() && e.Code == 503
}

func ErrorLeaderboardNotAvailable(format string, args ...interface{}) *errors.Error {
	return errors.New(503, ErrorReason_LEADERBOARD_NOT_AVAILABLE.String(), fmt.Sprintf(format, args...))
}
